// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumWebMapServiceRasterOverlay : CesiumRasterOverlay
{
	public CesiumWebMapServiceRasterOverlay() : base(NativeName)
	{
	}
	protected CesiumWebMapServiceRasterOverlay(StringName @class) : base(@class)
	{
	}
	protected CesiumWebMapServiceRasterOverlay(Variant variant) : base(variant)
	{
	}
	protected CesiumWebMapServiceRasterOverlay([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(CesiumWebMapServiceRasterOverlay self) => self?._object;
	public static implicit operator Variant(CesiumWebMapServiceRasterOverlay self) => self?._object;
	public static explicit operator CesiumWebMapServiceRasterOverlay(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : CesiumRasterOverlay.PropertyName
	{
		public static readonly StringName BaseUrl = "base_url";
		public static readonly StringName Layers = "layers";
		public static readonly StringName Version = "version";
		public static readonly StringName Format = "format";
		public static readonly StringName TileWidth = "tile_width";
		public static readonly StringName TileHeight = "tile_height";
		public static readonly StringName MinimumLevel = "minimum_level";
		public static readonly StringName MaximumLevel = "maximum_level";
		public static readonly StringName RequestHeaders = "request_headers";
	}

	public new class MethodName : CesiumRasterOverlay.MethodName
	{
		public static readonly StringName SetBaseUrl = "set_base_url";
		public static readonly StringName GetBaseUrl = "get_base_url";
		public static readonly StringName SetLayers = "set_layers";
		public static readonly StringName GetLayers = "get_layers";
		public static readonly StringName SetVersion = "set_version";
		public static readonly StringName GetVersion = "get_version";
		public static readonly StringName SetFormat = "set_format";
		public static readonly StringName GetFormat = "get_format";
		public static readonly StringName SetTileWidth = "set_tile_width";
		public static readonly StringName GetTileWidth = "get_tile_width";
		public static readonly StringName SetTileHeight = "set_tile_height";
		public static readonly StringName GetTileHeight = "get_tile_height";
		public static readonly StringName SetMinimumLevel = "set_minimum_level";
		public static readonly StringName GetMinimumLevel = "get_minimum_level";
		public static readonly StringName SetMaximumLevel = "set_maximum_level";
		public static readonly StringName GetMaximumLevel = "get_maximum_level";
		public static readonly StringName SetRequestHeaders = "set_request_headers";
		public static readonly StringName GetRequestHeaders = "get_request_headers";
	}

	public new class SignalName : CesiumRasterOverlay.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumWebMapServiceRasterOverlay";

	#region Properties

	public string BaseUrl
	{
		get => (string)_object.Get(PropertyName.BaseUrl);
		set => _object.Set(PropertyName.BaseUrl, value);
	}

	public string Layers
	{
		get => (string)_object.Get(PropertyName.Layers);
		set => _object.Set(PropertyName.Layers, value);
	}

	public string Version
	{
		get => (string)_object.Get(PropertyName.Version);
		set => _object.Set(PropertyName.Version, value);
	}

	public string Format
	{
		get => (string)_object.Get(PropertyName.Format);
		set => _object.Set(PropertyName.Format, value);
	}

	public int TileWidth
	{
		get => (int)_object.Get(PropertyName.TileWidth);
		set => _object.Set(PropertyName.TileWidth, value);
	}

	public int TileHeight
	{
		get => (int)_object.Get(PropertyName.TileHeight);
		set => _object.Set(PropertyName.TileHeight, value);
	}

	public int MinimumLevel
	{
		get => (int)_object.Get(PropertyName.MinimumLevel);
		set => _object.Set(PropertyName.MinimumLevel, value);
	}

	public int MaximumLevel
	{
		get => (int)_object.Get(PropertyName.MaximumLevel);
		set => _object.Set(PropertyName.MaximumLevel, value);
	}

	public Godot.Collections.Dictionary RequestHeaders
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.RequestHeaders);
		set => _object.Set(PropertyName.RequestHeaders, value);
	}

	#endregion

	#region Methods

	public void SetBaseUrl(string @value)
	{
		_object.Call(MethodName.SetBaseUrl, @value);
	}

	public string GetBaseUrl()
	{
		return (string)_object.Call(MethodName.GetBaseUrl);
	}

	public void SetLayers(string @value)
	{
		_object.Call(MethodName.SetLayers, @value);
	}

	public string GetLayers()
	{
		return (string)_object.Call(MethodName.GetLayers);
	}

	public void SetVersion(string @value)
	{
		_object.Call(MethodName.SetVersion, @value);
	}

	public string GetVersion()
	{
		return (string)_object.Call(MethodName.GetVersion);
	}

	public void SetFormat(string @value)
	{
		_object.Call(MethodName.SetFormat, @value);
	}

	public string GetFormat()
	{
		return (string)_object.Call(MethodName.GetFormat);
	}

	public void SetTileWidth(int @value)
	{
		_object.Call(MethodName.SetTileWidth, @value);
	}

	public int GetTileWidth()
	{
		return (int)_object.Call(MethodName.GetTileWidth);
	}

	public void SetTileHeight(int @value)
	{
		_object.Call(MethodName.SetTileHeight, @value);
	}

	public int GetTileHeight()
	{
		return (int)_object.Call(MethodName.GetTileHeight);
	}

	public void SetMinimumLevel(int @value)
	{
		_object.Call(MethodName.SetMinimumLevel, @value);
	}

	public int GetMinimumLevel()
	{
		return (int)_object.Call(MethodName.GetMinimumLevel);
	}

	public void SetMaximumLevel(int @value)
	{
		_object.Call(MethodName.SetMaximumLevel, @value);
	}

	public int GetMaximumLevel()
	{
		return (int)_object.Call(MethodName.GetMaximumLevel);
	}

	public void SetRequestHeaders(Godot.Collections.Dictionary @value)
	{
		_object.Call(MethodName.SetRequestHeaders, @value);
	}

	public Godot.Collections.Dictionary GetRequestHeaders()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetRequestHeaders);
	}

	#endregion
}
