// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumFeatureIdSet
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumFeatureIdSet() : this(NativeName)
	{
	}
	protected CesiumFeatureIdSet(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumFeatureIdSet(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumFeatureIdSet([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumFeatureIdSet self) => self?._object;
	public static implicit operator Variant(CesiumFeatureIdSet self) => self?._object;
	public static explicit operator CesiumFeatureIdSet(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName FeatureIdSetType = "feature_id_set_type";
		public static readonly StringName FeatureIdSetTypeName = "feature_id_set_type_name";
		public static readonly StringName Status = "status";
		public static readonly StringName StatusName = "status_name";
		public static readonly StringName FeatureCount = "feature_count";
		public static readonly StringName NullFeatureId = "null_feature_id";
		public static readonly StringName PropertyTableIndex = "property_table_index";
		public static readonly StringName Label = "label";
		public static readonly StringName AttributeIndex = "attribute_index";
		public static readonly StringName TextureCoordinateSetIndex = "texture_coordinate_set_index";
		public static readonly StringName VertexCount = "vertex_count";
		public static readonly StringName InstanceCount = "instance_count";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetFeatureIdSetType = "get_feature_id_set_type";
		public static readonly StringName GetFeatureIdSetTypeName = "get_feature_id_set_type_name";
		public static readonly StringName GetStatus = "get_status";
		public static readonly StringName GetStatusName = "get_status_name";
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName GetFeatureCount = "get_feature_count";
		public static readonly StringName GetNullFeatureId = "get_null_feature_id";
		public static readonly StringName GetPropertyTableIndex = "get_property_table_index";
		public static readonly StringName GetLabel = "get_label";
		public static readonly StringName GetAttributeIndex = "get_attribute_index";
		public static readonly StringName GetTextureCoordinateSetIndex = "get_texture_coordinate_set_index";
		public static readonly StringName GetVertexCount = "get_vertex_count";
		public static readonly StringName GetInstanceCount = "get_instance_count";
		public static readonly StringName GetFeatureIdForVertex = "get_feature_id_for_vertex";
		public static readonly StringName GetFeatureIdForInstance = "get_feature_id_for_instance";
		public static readonly StringName GetFeatureIdForTextureCoordinate = "get_feature_id_for_texture_coordinate";
		public static readonly StringName IsNullFeatureId = "is_null_feature_id";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumFeatureIdSet";

	#region Enums

	public enum Type : long
	{
		None = 0L,
		Attribute = 1L,
		Texture = 2L,
		Implicit = 3L,
		Instance = 4L,
		InstanceImplicit = 5L,
	}

	public enum StatusEnum : long
	{
		Valid = 0L,
		ErrorInvalidDefinition = 1L,
		ErrorInvalidAccessor = 2L,
		ErrorInvalidTexture = 3L,
	}

	#endregion

	#region Properties

	public int FeatureIdSetType
	{
		get => (int)_object.Get(PropertyName.FeatureIdSetType);
	}

	public string FeatureIdSetTypeName
	{
		get => (string)_object.Get(PropertyName.FeatureIdSetTypeName);
	}

	public int Status
	{
		get => (int)_object.Get(PropertyName.Status);
	}

	public string StatusName
	{
		get => (string)_object.Get(PropertyName.StatusName);
	}

	public int FeatureCount
	{
		get => (int)_object.Get(PropertyName.FeatureCount);
	}

	public int NullFeatureId
	{
		get => (int)_object.Get(PropertyName.NullFeatureId);
	}

	public int PropertyTableIndex
	{
		get => (int)_object.Get(PropertyName.PropertyTableIndex);
	}

	public string Label
	{
		get => (string)_object.Get(PropertyName.Label);
	}

	public int AttributeIndex
	{
		get => (int)_object.Get(PropertyName.AttributeIndex);
	}

	public int TextureCoordinateSetIndex
	{
		get => (int)_object.Get(PropertyName.TextureCoordinateSetIndex);
	}

	public int VertexCount
	{
		get => (int)_object.Get(PropertyName.VertexCount);
	}

	public int InstanceCount
	{
		get => (int)_object.Get(PropertyName.InstanceCount);
	}

	#endregion

	#region Methods

	public int GetFeatureIdSetType()
	{
		return (int)_object.Call(MethodName.GetFeatureIdSetType);
	}

	public string GetFeatureIdSetTypeName()
	{
		return (string)_object.Call(MethodName.GetFeatureIdSetTypeName);
	}

	public int GetStatus()
	{
		return (int)_object.Call(MethodName.GetStatus);
	}

	public string GetStatusName()
	{
		return (string)_object.Call(MethodName.GetStatusName);
	}

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public int GetFeatureCount()
	{
		return (int)_object.Call(MethodName.GetFeatureCount);
	}

	public int GetNullFeatureId()
	{
		return (int)_object.Call(MethodName.GetNullFeatureId);
	}

	public int GetPropertyTableIndex()
	{
		return (int)_object.Call(MethodName.GetPropertyTableIndex);
	}

	public string GetLabel()
	{
		return (string)_object.Call(MethodName.GetLabel);
	}

	public int GetAttributeIndex()
	{
		return (int)_object.Call(MethodName.GetAttributeIndex);
	}

	public int GetTextureCoordinateSetIndex()
	{
		return (int)_object.Call(MethodName.GetTextureCoordinateSetIndex);
	}

	public int GetVertexCount()
	{
		return (int)_object.Call(MethodName.GetVertexCount);
	}

	public int GetInstanceCount()
	{
		return (int)_object.Call(MethodName.GetInstanceCount);
	}

	public int GetFeatureIdForVertex(int @vertex_index)
	{
		return (int)_object.Call(MethodName.GetFeatureIdForVertex, @vertex_index);
	}

	public int GetFeatureIdForInstance(int @instance_index)
	{
		return (int)_object.Call(MethodName.GetFeatureIdForInstance, @instance_index);
	}

	public int GetFeatureIdForTextureCoordinate(Godot.Vector2 @texture_coordinate)
	{
		return (int)_object.Call(MethodName.GetFeatureIdForTextureCoordinate, @texture_coordinate);
	}

	public bool IsNullFeatureId(int @feature_id)
	{
		return (bool)_object.Call(MethodName.IsNullFeatureId, @feature_id);
	}

	#endregion
}
