// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGeoJsonDocumentRasterOverlay : CesiumRasterOverlay
{
	public CesiumGeoJsonDocumentRasterOverlay() : base(NativeName)
	{
	}
	protected CesiumGeoJsonDocumentRasterOverlay(StringName @class) : base(@class)
	{
	}
	protected CesiumGeoJsonDocumentRasterOverlay(Variant variant) : base(variant)
	{
	}
	protected CesiumGeoJsonDocumentRasterOverlay([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(CesiumGeoJsonDocumentRasterOverlay self) => self?._object;
	public static implicit operator Variant(CesiumGeoJsonDocumentRasterOverlay self) => self?._object;
	public static explicit operator CesiumGeoJsonDocumentRasterOverlay(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : CesiumRasterOverlay.PropertyName
	{
		public static readonly StringName Source = "source";
		public static readonly StringName Document = "document";
		public static readonly StringName GeoJson = "geo_json";
		public static readonly StringName Url = "url";
		public static readonly StringName RequestHeaders = "request_headers";
		public static readonly StringName IonAssetId = "ion_asset_id";
		public static readonly StringName IonAccessToken = "ion_access_token";
		public static readonly StringName IonApiUrl = "ion_api_url";
		public static readonly StringName MipLevels = "mip_levels";
		public static readonly StringName DefaultStyle = "default_style";
		public static readonly StringName LastDocumentErrors = "last_document_errors";
		public static readonly StringName LastDocumentWarnings = "last_document_warnings";
	}

	public new class MethodName : CesiumRasterOverlay.MethodName
	{
		public static readonly StringName SetSource = "set_source";
		public static readonly StringName GetSource = "get_source";
		public static readonly StringName SetDocument = "set_document";
		public static readonly StringName GetDocument = "get_document";
		public static readonly StringName SetGeoJson = "set_geo_json";
		public static readonly StringName GetGeoJson = "get_geo_json";
		public static readonly StringName SetUrl = "set_url";
		public static readonly StringName GetUrl = "get_url";
		public static readonly StringName SetRequestHeaders = "set_request_headers";
		public static readonly StringName GetRequestHeaders = "get_request_headers";
		public static readonly StringName SetIonAssetId = "set_ion_asset_id";
		public static readonly StringName GetIonAssetId = "get_ion_asset_id";
		public static readonly StringName SetIonAccessToken = "set_ion_access_token";
		public static readonly StringName GetIonAccessToken = "get_ion_access_token";
		public static readonly StringName SetIonApiUrl = "set_ion_api_url";
		public static readonly StringName GetIonApiUrl = "get_ion_api_url";
		public static readonly StringName SetMipLevels = "set_mip_levels";
		public static readonly StringName GetMipLevels = "get_mip_levels";
		public static readonly StringName SetDefaultStyle = "set_default_style";
		public static readonly StringName GetDefaultStyle = "get_default_style";
		public static readonly StringName GetLastDocumentErrors = "get_last_document_errors";
		public static readonly StringName GetLastDocumentWarnings = "get_last_document_warnings";
	}

	public new class SignalName : CesiumRasterOverlay.SignalName
	{
		public static readonly StringName DocumentLoaded = "document_loaded";
		public static readonly StringName DocumentLoadFailed = "document_load_failed";
	}

	private static readonly StringName NativeName = "CesiumGeoJsonDocumentRasterOverlay";

	#region Enums

	public enum SourceEnum : long
	{
		Document = 0L,
		String = 1L,
		Url = 2L,
		CesiumIon = 3L,
	}

	#endregion

	#region Properties

	public int Source
	{
		get => (int)_object.Get(PropertyName.Source);
		set => _object.Set(PropertyName.Source, value);
	}

	public CesiumGeoJsonDocument Document
	{
		get => (CesiumGeoJsonDocument)_object.Get(PropertyName.Document);
		set => _object.Set(PropertyName.Document, value);
	}

	public string GeoJson
	{
		get => (string)_object.Get(PropertyName.GeoJson);
		set => _object.Set(PropertyName.GeoJson, value);
	}

	public string Url
	{
		get => (string)_object.Get(PropertyName.Url);
		set => _object.Set(PropertyName.Url, value);
	}

	public Godot.Collections.Dictionary RequestHeaders
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.RequestHeaders);
		set => _object.Set(PropertyName.RequestHeaders, value);
	}

	public int IonAssetId
	{
		get => (int)_object.Get(PropertyName.IonAssetId);
		set => _object.Set(PropertyName.IonAssetId, value);
	}

	public string IonAccessToken
	{
		get => (string)_object.Get(PropertyName.IonAccessToken);
		set => _object.Set(PropertyName.IonAccessToken, value);
	}

	public string IonApiUrl
	{
		get => (string)_object.Get(PropertyName.IonApiUrl);
		set => _object.Set(PropertyName.IonApiUrl, value);
	}

	public int MipLevels
	{
		get => (int)_object.Get(PropertyName.MipLevels);
		set => _object.Set(PropertyName.MipLevels, value);
	}

	public CesiumVectorStyle DefaultStyle
	{
		get => (CesiumVectorStyle)_object.Get(PropertyName.DefaultStyle);
		set => _object.Set(PropertyName.DefaultStyle, value);
	}

	public string[] LastDocumentErrors
	{
		get => (string[])_object.Get(PropertyName.LastDocumentErrors);
	}

	public string[] LastDocumentWarnings
	{
		get => (string[])_object.Get(PropertyName.LastDocumentWarnings);
	}

	#endregion

	#region Methods

	public void SetSource(int @source)
	{
		_object.Call(MethodName.SetSource, @source);
	}

	public int GetSource()
	{
		return (int)_object.Call(MethodName.GetSource);
	}

	public void SetDocument(CesiumGeoJsonDocument @document)
	{
		_object.Call(MethodName.SetDocument, @document);
	}

	public CesiumGeoJsonDocument GetDocument()
	{
		return (CesiumGeoJsonDocument)_object.Call(MethodName.GetDocument);
	}

	public void SetGeoJson(string @geo_json)
	{
		_object.Call(MethodName.SetGeoJson, @geo_json);
	}

	public string GetGeoJson()
	{
		return (string)_object.Call(MethodName.GetGeoJson);
	}

	public void SetUrl(string @url)
	{
		_object.Call(MethodName.SetUrl, @url);
	}

	public string GetUrl()
	{
		return (string)_object.Call(MethodName.GetUrl);
	}

	public void SetRequestHeaders(Godot.Collections.Dictionary @headers)
	{
		_object.Call(MethodName.SetRequestHeaders, @headers);
	}

	public Godot.Collections.Dictionary GetRequestHeaders()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetRequestHeaders);
	}

	public void SetIonAssetId(int @asset_id)
	{
		_object.Call(MethodName.SetIonAssetId, @asset_id);
	}

	public int GetIonAssetId()
	{
		return (int)_object.Call(MethodName.GetIonAssetId);
	}

	public void SetIonAccessToken(string @token)
	{
		_object.Call(MethodName.SetIonAccessToken, @token);
	}

	public string GetIonAccessToken()
	{
		return (string)_object.Call(MethodName.GetIonAccessToken);
	}

	public void SetIonApiUrl(string @url)
	{
		_object.Call(MethodName.SetIonApiUrl, @url);
	}

	public string GetIonApiUrl()
	{
		return (string)_object.Call(MethodName.GetIonApiUrl);
	}

	public void SetMipLevels(int @levels)
	{
		_object.Call(MethodName.SetMipLevels, @levels);
	}

	public int GetMipLevels()
	{
		return (int)_object.Call(MethodName.GetMipLevels);
	}

	public void SetDefaultStyle(CesiumVectorStyle @style)
	{
		_object.Call(MethodName.SetDefaultStyle, @style);
	}

	public CesiumVectorStyle GetDefaultStyle()
	{
		return (CesiumVectorStyle)_object.Call(MethodName.GetDefaultStyle);
	}

	public string[] GetLastDocumentErrors()
	{
		return (string[])_object.Call(MethodName.GetLastDocumentErrors);
	}

	public string[] GetLastDocumentWarnings()
	{
		return (string[])_object.Call(MethodName.GetLastDocumentWarnings);
	}

	#endregion

	#region Signals

	public event Action<GodotObject> DocumentLoaded
	{
		add
		{
			_object.Connect(SignalName.DocumentLoaded, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.DocumentLoaded, Callable.From(value));
		}
	}

	public event Action<string[], string[]> DocumentLoadFailed
	{
		add
		{
			_object.Connect(SignalName.DocumentLoadFailed, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.DocumentLoadFailed, Callable.From(value));
		}
	}

	#endregion
}
