// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumCartographicPolygon
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public Resource NativeObject => _object;

	public CesiumCartographicPolygon() : this(NativeName)
	{
	}
	protected CesiumCartographicPolygon(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumCartographicPolygon(Variant variant) : this((Resource) variant)
	{
	}
	protected CesiumCartographicPolygon([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(CesiumCartographicPolygon self) => self?._object;
	public static implicit operator Variant(CesiumCartographicPolygon self) => self?._object;
	public static explicit operator CesiumCartographicPolygon(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName VerticesDegrees = "vertices_degrees";
		public static readonly StringName VerticesDegreesExact = "vertices_degrees_exact";
		public static readonly StringName VertexCount = "vertex_count";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName SetVerticesDegrees = "set_vertices_degrees";
		public static readonly StringName GetVerticesDegrees = "get_vertices_degrees";
		public static readonly StringName SetVerticesDegreesExact = "set_vertices_degrees_exact";
		public static readonly StringName GetVerticesDegreesExact = "get_vertices_degrees_exact";
		public static readonly StringName SetVerticesFromEcefExact = "set_vertices_from_ecef_exact";
		public static readonly StringName GetVertexCount = "get_vertex_count";
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName GetTriangulatedIndices = "get_triangulated_indices";
		public static readonly StringName GetBoundingRectangleDegrees = "get_bounding_rectangle_degrees";
		public static readonly StringName RectangleIsCompletelyInsideDegrees = "rectangle_is_completely_inside_degrees";
		public static readonly StringName RectangleIsCompletelyOutsideDegrees = "rectangle_is_completely_outside_degrees";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumCartographicPolygon";

	#region Properties

	public Godot.Vector2[] VerticesDegrees
	{
		get => (Godot.Vector2[])_object.Get(PropertyName.VerticesDegrees);
		set => _object.Set(PropertyName.VerticesDegrees, value);
	}

	public double[] VerticesDegreesExact
	{
		get => (double[])_object.Get(PropertyName.VerticesDegreesExact);
		set => _object.Set(PropertyName.VerticesDegreesExact, value);
	}

	public int VertexCount
	{
		get => (int)_object.Get(PropertyName.VertexCount);
	}

	#endregion

	#region Methods

	public void SetVerticesDegrees(Godot.Vector2[] @vertices)
	{
		_object.Call(MethodName.SetVerticesDegrees, @vertices);
	}

	public Godot.Vector2[] GetVerticesDegrees()
	{
		return (Godot.Vector2[])_object.Call(MethodName.GetVerticesDegrees);
	}

	public bool SetVerticesDegreesExact(double[] @components)
	{
		return (bool)_object.Call(MethodName.SetVerticesDegreesExact, @components);
	}

	public double[] GetVerticesDegreesExact()
	{
		return (double[])_object.Call(MethodName.GetVerticesDegreesExact);
	}

	public bool SetVerticesFromEcefExact(double[] @ecef_components, CesiumEllipsoid @ellipsoid)
	{
		return (bool)_object.Call(MethodName.SetVerticesFromEcefExact, @ecef_components, @ellipsoid);
	}

	public int GetVertexCount()
	{
		return (int)_object.Call(MethodName.GetVertexCount);
	}

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public int[] GetTriangulatedIndices()
	{
		return (int[])_object.Call(MethodName.GetTriangulatedIndices);
	}

	public double[] GetBoundingRectangleDegrees()
	{
		return (double[])_object.Call(MethodName.GetBoundingRectangleDegrees);
	}

	public bool RectangleIsCompletelyInsideDegrees(double[] @west_south_east_north)
	{
		return (bool)_object.Call(MethodName.RectangleIsCompletelyInsideDegrees, @west_south_east_north);
	}

	public bool RectangleIsCompletelyOutsideDegrees(double[] @west_south_east_north)
	{
		return (bool)_object.Call(MethodName.RectangleIsCompletelyOutsideDegrees, @west_south_east_north);
	}

	#endregion
}
