// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumCredit
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumCredit() : this(NativeName)
	{
	}
	protected CesiumCredit(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumCredit(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumCredit([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumCredit self) => self?._object;
	public static implicit operator Variant(CesiumCredit self) => self?._object;
	public static explicit operator CesiumCredit(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Html = "html";
		public static readonly StringName PlainText = "plain_text";
		public static readonly StringName AccessibleText = "accessible_text";
		public static readonly StringName ShowOnScreen = "show_on_screen";
		public static readonly StringName Runs = "runs";
		public static readonly StringName Links = "links";
		public static readonly StringName ImageUrls = "image_urls";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetHtml = "get_html";
		public static readonly StringName GetPlainText = "get_plain_text";
		public static readonly StringName GetAccessibleText = "get_accessible_text";
		public static readonly StringName GetShowOnScreen = "get_show_on_screen";
		public static readonly StringName GetRuns = "get_runs";
		public static readonly StringName GetLinks = "get_links";
		public static readonly StringName GetImageUrls = "get_image_urls";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumCredit";

	#region Properties

	public string Html
	{
		get => (string)_object.Get(PropertyName.Html);
	}

	public string PlainText
	{
		get => (string)_object.Get(PropertyName.PlainText);
	}

	public string AccessibleText
	{
		get => (string)_object.Get(PropertyName.AccessibleText);
	}

	public bool ShowOnScreen
	{
		get => (bool)_object.Get(PropertyName.ShowOnScreen);
	}

	public Godot.Collections.Array Runs
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.Runs);
	}

	public Godot.Collections.Array Links
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.Links);
	}

	public string[] ImageUrls
	{
		get => (string[])_object.Get(PropertyName.ImageUrls);
	}

	#endregion

	#region Methods

	public string GetHtml()
	{
		return (string)_object.Call(MethodName.GetHtml);
	}

	public string GetPlainText()
	{
		return (string)_object.Call(MethodName.GetPlainText);
	}

	public string GetAccessibleText()
	{
		return (string)_object.Call(MethodName.GetAccessibleText);
	}

	public bool GetShowOnScreen()
	{
		return (bool)_object.Call(MethodName.GetShowOnScreen);
	}

	public Godot.Collections.Array GetRuns()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetRuns);
	}

	public Godot.Collections.Array GetLinks()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetLinks);
	}

	public string[] GetImageUrls()
	{
		return (string[])_object.Call(MethodName.GetImageUrls);
	}

	#endregion
}
