// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumLoadedTilePrimitive
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumLoadedTilePrimitive() : this(NativeName)
	{
	}
	protected CesiumLoadedTilePrimitive(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumLoadedTilePrimitive(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumLoadedTilePrimitive([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumLoadedTilePrimitive self) => self?._object;
	public static implicit operator Variant(CesiumLoadedTilePrimitive self) => self?._object;
	public static explicit operator CesiumLoadedTilePrimitive(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName LoadedTile = "loaded_tile";
		public static readonly StringName RenderNode = "render_node";
		public static readonly StringName TileId = "tile_id";
		public static readonly StringName TileExtras = "tile_extras";
		public static readonly StringName SurfaceIndex = "surface_index";
		public static readonly StringName MeshSurfaceIndex = "mesh_surface_index";
		public static readonly StringName GpuInstanced = "gpu_instanced";
		public static readonly StringName InstanceCount = "instance_count";
		public static readonly StringName NodeIndex = "node_index";
		public static readonly StringName MeshIndex = "mesh_index";
		public static readonly StringName PrimitiveIndex = "primitive_index";
		public static readonly StringName MaterialIndex = "material_index";
		public static readonly StringName PrimitiveMode = "primitive_mode";
		public static readonly StringName PrimitiveModeName = "primitive_mode_name";
		public static readonly StringName PointPrimitive = "point_primitive";
		public static readonly StringName LinePrimitive = "line_primitive";
		public static readonly StringName TrianglePrimitive = "triangle_primitive";
		public static readonly StringName Translucent = "translucent";
		public static readonly StringName TranslucencyIsolated = "translucency_isolated";
		public static readonly StringName PointCount = "point_count";
		public static readonly StringName PointDiameter = "point_diameter";
		public static readonly StringName PrimitiveDimensions = "primitive_dimensions";
		public static readonly StringName TileGeometricError = "tile_geometric_error";
		public static readonly StringName UsesAdditiveRefinement = "uses_additive_refinement";
		public static readonly StringName PointCloudParameters = "point_cloud_parameters";
		public static readonly StringName Attributes = "attributes";
		public static readonly StringName GltfMaterial = "gltf_material";
		public static readonly StringName TextureCoordinateMappings = "texture_coordinate_mappings";
		public static readonly StringName DefaultMaterial = "default_material";
		public static readonly StringName SelectedBaseMaterial = "selected_base_material";
		public static readonly StringName ActiveMaterial = "active_material";
		public static readonly StringName UsesCustomMaterial = "uses_custom_material";
		public static readonly StringName RasterOverlayBindings = "raster_overlay_bindings";
		public static readonly StringName RenderDiagnostics = "render_diagnostics";
		public static readonly StringName PrimitiveFeatures = "primitive_features";
		public static readonly StringName InstanceFeatures = "instance_features";
		public static readonly StringName PrimitiveMetadata = "primitive_metadata";
		public static readonly StringName ModelMetadata = "model_metadata";
		public static readonly StringName AbsoluteOrigin = "absolute_origin";
		public static readonly StringName AbsoluteOriginHigh = "absolute_origin_high";
		public static readonly StringName AbsoluteOriginLow = "absolute_origin_low";
		public static readonly StringName LocalToAbsoluteBasis = "local_to_absolute_basis";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetLoadedTile = "get_loaded_tile";
		public static readonly StringName GetRenderNode = "get_render_node";
		public static readonly StringName GetTileId = "get_tile_id";
		public static readonly StringName GetTileExtras = "get_tile_extras";
		public static readonly StringName GetSurfaceIndex = "get_surface_index";
		public static readonly StringName GetMeshSurfaceIndex = "get_mesh_surface_index";
		public static readonly StringName IsGpuInstanced = "is_gpu_instanced";
		public static readonly StringName GetInstanceCount = "get_instance_count";
		public static readonly StringName GetNodeIndex = "get_node_index";
		public static readonly StringName GetMeshIndex = "get_mesh_index";
		public static readonly StringName GetPrimitiveIndex = "get_primitive_index";
		public static readonly StringName GetMaterialIndex = "get_material_index";
		public static readonly StringName GetPrimitiveMode = "get_primitive_mode";
		public static readonly StringName GetPrimitiveModeName = "get_primitive_mode_name";
		public static readonly StringName IsPointPrimitive = "is_point_primitive";
		public static readonly StringName IsLinePrimitive = "is_line_primitive";
		public static readonly StringName IsTrianglePrimitive = "is_triangle_primitive";
		public static readonly StringName IsTranslucent = "is_translucent";
		public static readonly StringName IsTranslucencyIsolated = "is_translucency_isolated";
		public static readonly StringName GetPointCount = "get_point_count";
		public static readonly StringName GetPointDiameter = "get_point_diameter";
		public static readonly StringName GetPrimitiveDimensions = "get_primitive_dimensions";
		public static readonly StringName GetTileGeometricError = "get_tile_geometric_error";
		public static readonly StringName GetUsesAdditiveRefinement = "get_uses_additive_refinement";
		public static readonly StringName GetPointCloudParameters = "get_point_cloud_parameters";
		public static readonly StringName GetAttributes = "get_attributes";
		public static readonly StringName GetGltfMaterial = "get_gltf_material";
		public static readonly StringName GetTextureCoordinateMappings = "get_texture_coordinate_mappings";
		public static readonly StringName GetDefaultMaterial = "get_default_material";
		public static readonly StringName GetSelectedBaseMaterial = "get_selected_base_material";
		public static readonly StringName GetActiveMaterial = "get_active_material";
		public static readonly StringName GetUsesCustomMaterial = "get_uses_custom_material";
		public static readonly StringName GetRasterOverlayBindings = "get_raster_overlay_bindings";
		public static readonly StringName GetRenderDiagnostics = "get_render_diagnostics";
		public static readonly StringName GetPrimitiveFeatures = "get_primitive_features";
		public static readonly StringName GetInstanceFeatures = "get_instance_features";
		public static readonly StringName GetPrimitiveMetadata = "get_primitive_metadata";
		public static readonly StringName GetModelMetadata = "get_model_metadata";
		public static readonly StringName GetTextureCoordinateIndex = "get_texture_coordinate_index";
		public static readonly StringName GetOverlayTextureCoordinateIndex = "get_overlay_texture_coordinate_index";
		public static readonly StringName GetAbsoluteOrigin = "get_absolute_origin";
		public static readonly StringName GetAbsoluteOriginHigh = "get_absolute_origin_high";
		public static readonly StringName GetAbsoluteOriginLow = "get_absolute_origin_low";
		public static readonly StringName GetLocalToAbsoluteBasis = "get_local_to_absolute_basis";
		public static readonly StringName ApplyWorldCoordinateParameters = "apply_world_coordinate_parameters";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumLoadedTilePrimitive";

	#region Properties

	public GodotObject LoadedTile
	{
		get => (GodotObject)_object.Get(PropertyName.LoadedTile);
	}

	public GodotObject RenderNode
	{
		get => (GodotObject)_object.Get(PropertyName.RenderNode);
	}

	public string TileId
	{
		get => (string)_object.Get(PropertyName.TileId);
	}

	public Variant TileExtras
	{
		get => (Variant)_object.Get(PropertyName.TileExtras);
	}

	public int SurfaceIndex
	{
		get => (int)_object.Get(PropertyName.SurfaceIndex);
	}

	public int MeshSurfaceIndex
	{
		get => (int)_object.Get(PropertyName.MeshSurfaceIndex);
	}

	public bool GpuInstanced
	{
		get => (bool)_object.Get(PropertyName.GpuInstanced);
	}

	public int InstanceCount
	{
		get => (int)_object.Get(PropertyName.InstanceCount);
	}

	public int NodeIndex
	{
		get => (int)_object.Get(PropertyName.NodeIndex);
	}

	public int MeshIndex
	{
		get => (int)_object.Get(PropertyName.MeshIndex);
	}

	public int PrimitiveIndex
	{
		get => (int)_object.Get(PropertyName.PrimitiveIndex);
	}

	public int MaterialIndex
	{
		get => (int)_object.Get(PropertyName.MaterialIndex);
	}

	public int PrimitiveMode
	{
		get => (int)_object.Get(PropertyName.PrimitiveMode);
	}

	public string PrimitiveModeName
	{
		get => (string)_object.Get(PropertyName.PrimitiveModeName);
	}

	public bool PointPrimitive
	{
		get => (bool)_object.Get(PropertyName.PointPrimitive);
	}

	public bool LinePrimitive
	{
		get => (bool)_object.Get(PropertyName.LinePrimitive);
	}

	public bool TrianglePrimitive
	{
		get => (bool)_object.Get(PropertyName.TrianglePrimitive);
	}

	public bool Translucent
	{
		get => (bool)_object.Get(PropertyName.Translucent);
	}

	public bool TranslucencyIsolated
	{
		get => (bool)_object.Get(PropertyName.TranslucencyIsolated);
	}

	public int PointCount
	{
		get => (int)_object.Get(PropertyName.PointCount);
	}

	public int PointDiameter
	{
		get => (int)_object.Get(PropertyName.PointDiameter);
	}

	public Godot.Vector3 PrimitiveDimensions
	{
		get => (Godot.Vector3)_object.Get(PropertyName.PrimitiveDimensions);
	}

	public float TileGeometricError
	{
		get => (float)_object.Get(PropertyName.TileGeometricError);
	}

	public bool UsesAdditiveRefinement
	{
		get => (bool)_object.Get(PropertyName.UsesAdditiveRefinement);
	}

	public Godot.Collections.Dictionary PointCloudParameters
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.PointCloudParameters);
	}

	public Godot.Collections.Dictionary Attributes
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.Attributes);
	}

	public Godot.Collections.Dictionary GltfMaterial
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.GltfMaterial);
	}

	public Godot.Collections.Dictionary TextureCoordinateMappings
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.TextureCoordinateMappings);
	}

	public Material DefaultMaterial
	{
		get => (Material)_object.Get(PropertyName.DefaultMaterial);
	}

	public Material SelectedBaseMaterial
	{
		get => (Material)_object.Get(PropertyName.SelectedBaseMaterial);
	}

	public Material ActiveMaterial
	{
		get => (Material)_object.Get(PropertyName.ActiveMaterial);
	}

	public bool UsesCustomMaterial
	{
		get => (bool)_object.Get(PropertyName.UsesCustomMaterial);
	}

	public Godot.Collections.Array RasterOverlayBindings
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.RasterOverlayBindings);
	}

	public Godot.Collections.Dictionary RenderDiagnostics
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.RenderDiagnostics);
	}

	public CesiumPrimitiveFeatures PrimitiveFeatures
	{
		get => (CesiumPrimitiveFeatures)_object.Get(PropertyName.PrimitiveFeatures);
	}

	public CesiumPrimitiveFeatures InstanceFeatures
	{
		get => (CesiumPrimitiveFeatures)_object.Get(PropertyName.InstanceFeatures);
	}

	public CesiumPrimitiveMetadata PrimitiveMetadata
	{
		get => (CesiumPrimitiveMetadata)_object.Get(PropertyName.PrimitiveMetadata);
	}

	public CesiumModelMetadata ModelMetadata
	{
		get => (CesiumModelMetadata)_object.Get(PropertyName.ModelMetadata);
	}

	public Godot.Vector3 AbsoluteOrigin
	{
		get => (Godot.Vector3)_object.Get(PropertyName.AbsoluteOrigin);
	}

	public Godot.Vector3 AbsoluteOriginHigh
	{
		get => (Godot.Vector3)_object.Get(PropertyName.AbsoluteOriginHigh);
	}

	public Godot.Vector3 AbsoluteOriginLow
	{
		get => (Godot.Vector3)_object.Get(PropertyName.AbsoluteOriginLow);
	}

	public Godot.Basis LocalToAbsoluteBasis
	{
		get => (Godot.Basis)_object.Get(PropertyName.LocalToAbsoluteBasis);
	}

	#endregion

	#region Methods

	public Cesium3DTile GetLoadedTile()
	{
		return (Cesium3DTile)_object.Call(MethodName.GetLoadedTile);
	}

	public GeometryInstance3D GetRenderNode()
	{
		return (GeometryInstance3D)_object.Call(MethodName.GetRenderNode);
	}

	public string GetTileId()
	{
		return (string)_object.Call(MethodName.GetTileId);
	}

	public Variant GetTileExtras()
	{
		return (Variant)_object.Call(MethodName.GetTileExtras);
	}

	public int GetSurfaceIndex()
	{
		return (int)_object.Call(MethodName.GetSurfaceIndex);
	}

	public int GetMeshSurfaceIndex()
	{
		return (int)_object.Call(MethodName.GetMeshSurfaceIndex);
	}

	public bool IsGpuInstanced()
	{
		return (bool)_object.Call(MethodName.IsGpuInstanced);
	}

	public int GetInstanceCount()
	{
		return (int)_object.Call(MethodName.GetInstanceCount);
	}

	public int GetNodeIndex()
	{
		return (int)_object.Call(MethodName.GetNodeIndex);
	}

	public int GetMeshIndex()
	{
		return (int)_object.Call(MethodName.GetMeshIndex);
	}

	public int GetPrimitiveIndex()
	{
		return (int)_object.Call(MethodName.GetPrimitiveIndex);
	}

	public int GetMaterialIndex()
	{
		return (int)_object.Call(MethodName.GetMaterialIndex);
	}

	public int GetPrimitiveMode()
	{
		return (int)_object.Call(MethodName.GetPrimitiveMode);
	}

	public string GetPrimitiveModeName()
	{
		return (string)_object.Call(MethodName.GetPrimitiveModeName);
	}

	public bool IsPointPrimitive()
	{
		return (bool)_object.Call(MethodName.IsPointPrimitive);
	}

	public bool IsLinePrimitive()
	{
		return (bool)_object.Call(MethodName.IsLinePrimitive);
	}

	public bool IsTrianglePrimitive()
	{
		return (bool)_object.Call(MethodName.IsTrianglePrimitive);
	}

	public bool IsTranslucent()
	{
		return (bool)_object.Call(MethodName.IsTranslucent);
	}

	public bool IsTranslucencyIsolated()
	{
		return (bool)_object.Call(MethodName.IsTranslucencyIsolated);
	}

	public int GetPointCount()
	{
		return (int)_object.Call(MethodName.GetPointCount);
	}

	public int GetPointDiameter()
	{
		return (int)_object.Call(MethodName.GetPointDiameter);
	}

	public Godot.Vector3 GetPrimitiveDimensions()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetPrimitiveDimensions);
	}

	public float GetTileGeometricError()
	{
		return (float)_object.Call(MethodName.GetTileGeometricError);
	}

	public bool GetUsesAdditiveRefinement()
	{
		return (bool)_object.Call(MethodName.GetUsesAdditiveRefinement);
	}

	public Godot.Collections.Dictionary GetPointCloudParameters()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetPointCloudParameters);
	}

	public Godot.Collections.Dictionary GetAttributes()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetAttributes);
	}

	public Godot.Collections.Dictionary GetGltfMaterial()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetGltfMaterial);
	}

	public Godot.Collections.Dictionary GetTextureCoordinateMappings()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetTextureCoordinateMappings);
	}

	public Material GetDefaultMaterial()
	{
		return (Material)_object.Call(MethodName.GetDefaultMaterial);
	}

	public Material GetSelectedBaseMaterial()
	{
		return (Material)_object.Call(MethodName.GetSelectedBaseMaterial);
	}

	public Material GetActiveMaterial()
	{
		return (Material)_object.Call(MethodName.GetActiveMaterial);
	}

	public bool GetUsesCustomMaterial()
	{
		return (bool)_object.Call(MethodName.GetUsesCustomMaterial);
	}

	public Godot.Collections.Array GetRasterOverlayBindings()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetRasterOverlayBindings);
	}

	public Godot.Collections.Dictionary GetRenderDiagnostics()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetRenderDiagnostics);
	}

	public CesiumPrimitiveFeatures GetPrimitiveFeatures()
	{
		return (CesiumPrimitiveFeatures)_object.Call(MethodName.GetPrimitiveFeatures);
	}

	public CesiumPrimitiveFeatures GetInstanceFeatures()
	{
		return (CesiumPrimitiveFeatures)_object.Call(MethodName.GetInstanceFeatures);
	}

	public CesiumPrimitiveMetadata GetPrimitiveMetadata()
	{
		return (CesiumPrimitiveMetadata)_object.Call(MethodName.GetPrimitiveMetadata);
	}

	public CesiumModelMetadata GetModelMetadata()
	{
		return (CesiumModelMetadata)_object.Call(MethodName.GetModelMetadata);
	}

	public int GetTextureCoordinateIndex(string @semantic)
	{
		return (int)_object.Call(MethodName.GetTextureCoordinateIndex, @semantic);
	}

	public int GetOverlayTextureCoordinateIndex(int @texture_coordinate_id)
	{
		return (int)_object.Call(MethodName.GetOverlayTextureCoordinateIndex, @texture_coordinate_id);
	}

	public Godot.Vector3 GetAbsoluteOrigin()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetAbsoluteOrigin);
	}

	public Godot.Vector3 GetAbsoluteOriginHigh()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetAbsoluteOriginHigh);
	}

	public Godot.Vector3 GetAbsoluteOriginLow()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetAbsoluteOriginLow);
	}

	public Godot.Basis GetLocalToAbsoluteBasis()
	{
		return (Godot.Basis)_object.Call(MethodName.GetLocalToAbsoluteBasis);
	}

	public bool ApplyWorldCoordinateParameters(Material @material, string @parameter_prefix = "cesium")
	{
		return (bool)_object.Call(MethodName.ApplyWorldCoordinateParameters, @material, @parameter_prefix);
	}

	#endregion
}
