// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class Cesium3DTile : GeoreferencedMesh
{
	public Cesium3DTile() : base(NativeName)
	{
	}
	protected Cesium3DTile(StringName @class) : base(@class)
	{
	}
	protected Cesium3DTile(Variant variant) : base(variant)
	{
	}
	protected Cesium3DTile([NotNull] MeshInstance3D @object) : base(@object)
	{
	}

	public static implicit operator MeshInstance3D(Cesium3DTile self) => self?._object;
	public static implicit operator Variant(Cesium3DTile self) => self?._object;
	public static explicit operator Cesium3DTile(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : GeoreferencedMesh.PropertyName
	{
		public static readonly StringName TileId = "tile_id";
		public static readonly StringName ModelMetadata = "model_metadata";
		public static readonly StringName PrimitiveFeatures = "primitive_features";
		public static readonly StringName TileExtras = "tile_extras";
		public static readonly StringName TileBounds = "tile_bounds";
		public static readonly StringName ContentBounds = "content_bounds";
		public static readonly StringName ViewerRequestBounds = "viewer_request_bounds";
		public static readonly StringName LoadedTilePrimitives = "loaded_tile_primitives";
		public static readonly StringName RasterOverlayBindings = "raster_overlay_bindings";
	}

	public new class MethodName : GeoreferencedMesh.MethodName
	{
		public static readonly StringName GetMetadataTable = "get_metadata_table";
		public static readonly StringName GetModelMetadata = "get_model_metadata";
		public static readonly StringName GetAllPrimitiveFeatures = "get_all_primitive_features";
		public static readonly StringName GetPrimitiveFeatures = "get_primitive_features";
		public static readonly StringName GetTableCount = "get_table_count";
		public static readonly StringName GenerateTileCollision = "generate_tile_collision";
		public static readonly StringName GetStructuralMetadata = "get_structural_metadata";
		public static readonly StringName GetTileId = "get_tile_id";
		public static readonly StringName GetTileExtras = "get_tile_extras";
		public static readonly StringName GetTileBounds = "get_tile_bounds";
		public static readonly StringName GetContentBounds = "get_content_bounds";
		public static readonly StringName GetViewerRequestBounds = "get_viewer_request_bounds";
		public static readonly StringName GetTileSourceAabb = "get_tile_source_aabb";
		public static readonly StringName GetLoadedTilePrimitives = "get_loaded_tile_primitives";
		public static readonly StringName GetLoadedTilePrimitiveCount = "get_loaded_tile_primitive_count";
		public static readonly StringName GetLoadedTilePrimitive = "get_loaded_tile_primitive";
		public static readonly StringName GetLoadedTilePrimitiveForMeshSurface = "get_loaded_tile_primitive_for_mesh_surface";
		public static readonly StringName GetAllRasterOverlayBindings = "get_all_raster_overlay_bindings";
		public static readonly StringName GetRasterOverlayBindings = "get_raster_overlay_bindings";
	}

	public new class SignalName : GeoreferencedMesh.SignalName
	{

	}

	private static readonly StringName NativeName = "Cesium3DTile";

	#region Properties

	public string TileId
	{
		get => (string)_object.Get(PropertyName.TileId);
	}

	public CesiumModelMetadata ModelMetadata
	{
		get => (CesiumModelMetadata)_object.Get(PropertyName.ModelMetadata);
	}

	public Godot.Collections.Array PrimitiveFeatures
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.PrimitiveFeatures);
	}

	public Variant TileExtras
	{
		get => (Variant)_object.Get(PropertyName.TileExtras);
	}

	public CesiumBoundingVolume TileBounds
	{
		get => (CesiumBoundingVolume)_object.Get(PropertyName.TileBounds);
	}

	public CesiumBoundingVolume ContentBounds
	{
		get => (CesiumBoundingVolume)_object.Get(PropertyName.ContentBounds);
	}

	public CesiumBoundingVolume ViewerRequestBounds
	{
		get => (CesiumBoundingVolume)_object.Get(PropertyName.ViewerRequestBounds);
	}

	public Godot.Collections.Array LoadedTilePrimitives
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.LoadedTilePrimitives);
	}

	public Godot.Collections.Array RasterOverlayBindings
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.RasterOverlayBindings);
	}

	#endregion

	#region Methods

	public Godot.Collections.Dictionary GetMetadataTable(int @index)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetMetadataTable, @index);
	}

	public CesiumModelMetadata GetModelMetadata()
	{
		return (CesiumModelMetadata)_object.Call(MethodName.GetModelMetadata);
	}

	public Godot.Collections.Array GetAllPrimitiveFeatures()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetAllPrimitiveFeatures);
	}

	public CesiumPrimitiveFeatures GetPrimitiveFeatures(int @surface_index)
	{
		return (CesiumPrimitiveFeatures)_object.Call(MethodName.GetPrimitiveFeatures, @surface_index);
	}

	public int GetTableCount()
	{
		return (int)_object.Call(MethodName.GetTableCount);
	}

	public void GenerateTileCollision()
	{
		_object.Call(MethodName.GenerateTileCollision);
	}

	public Godot.Collections.Dictionary GetStructuralMetadata()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetStructuralMetadata);
	}

	public string GetTileId()
	{
		return (string)_object.Call(MethodName.GetTileId);
	}

	public Variant GetTileExtras()
	{
		return (Variant)_object.Call(MethodName.GetTileExtras);
	}

	public CesiumBoundingVolume GetTileBounds()
	{
		return (CesiumBoundingVolume)_object.Call(MethodName.GetTileBounds);
	}

	public CesiumBoundingVolume GetContentBounds()
	{
		return (CesiumBoundingVolume)_object.Call(MethodName.GetContentBounds);
	}

	public CesiumBoundingVolume GetViewerRequestBounds()
	{
		return (CesiumBoundingVolume)_object.Call(MethodName.GetViewerRequestBounds);
	}

	public Godot.Aabb GetTileSourceAabb()
	{
		return (Godot.Aabb)_object.Call(MethodName.GetTileSourceAabb);
	}

	public Godot.Collections.Array GetLoadedTilePrimitives()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetLoadedTilePrimitives);
	}

	public int GetLoadedTilePrimitiveCount()
	{
		return (int)_object.Call(MethodName.GetLoadedTilePrimitiveCount);
	}

	public CesiumLoadedTilePrimitive GetLoadedTilePrimitive(int @surface_index)
	{
		return (CesiumLoadedTilePrimitive)_object.Call(MethodName.GetLoadedTilePrimitive, @surface_index);
	}

	public CesiumLoadedTilePrimitive GetLoadedTilePrimitiveForMeshSurface(int @mesh_surface_index)
	{
		return (CesiumLoadedTilePrimitive)_object.Call(MethodName.GetLoadedTilePrimitiveForMeshSurface, @mesh_surface_index);
	}

	public Godot.Collections.Array GetAllRasterOverlayBindings()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetAllRasterOverlayBindings);
	}

	public Godot.Collections.Array GetRasterOverlayBindings(int @surface_index = -1)
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetRasterOverlayBindings, @surface_index);
	}

	#endregion
}
