// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGeocoderService
{
	// Engine object used for calling engine methods
	protected Node _object;

	public Node NativeObject => _object;

	public CesiumGeocoderService() : this(NativeName)
	{
	}
	protected CesiumGeocoderService(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGeocoderService(Variant variant) : this((Node) variant)
	{
	}
	protected CesiumGeocoderService([NotNull] Node @object)
	{
		_object = @object;
	}

	public static implicit operator Node(CesiumGeocoderService self) => self?._object;
	public static implicit operator Variant(CesiumGeocoderService self) => self?._object;
	public static explicit operator CesiumGeocoderService(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node.PropertyName
	{
		public static readonly StringName AccessToken = "access_token";
		public static readonly StringName ApiUrl = "api_url";
		public static readonly StringName WorkerThreadCount = "worker_thread_count";
		public static readonly StringName MaximumNetworkRetries = "maximum_network_retries";
		public static readonly StringName NetworkRetryInitialDelaySeconds = "network_retry_initial_delay_seconds";
		public static readonly StringName NetworkRetryMaximumDelaySeconds = "network_retry_maximum_delay_seconds";
		public static readonly StringName PendingRequestCount = "pending_request_count";
	}

	public class MethodName : Node.MethodName
	{
		public static readonly StringName SetAccessToken = "set_access_token";
		public static readonly StringName GetAccessToken = "get_access_token";
		public static readonly StringName SetApiUrl = "set_api_url";
		public static readonly StringName GetApiUrl = "get_api_url";
		public static readonly StringName SetWorkerThreadCount = "set_worker_thread_count";
		public static readonly StringName GetWorkerThreadCount = "get_worker_thread_count";
		public static readonly StringName SetMaximumNetworkRetries = "set_maximum_network_retries";
		public static readonly StringName GetMaximumNetworkRetries = "get_maximum_network_retries";
		public static readonly StringName SetNetworkRetryInitialDelaySeconds = "set_network_retry_initial_delay_seconds";
		public static readonly StringName GetNetworkRetryInitialDelaySeconds = "get_network_retry_initial_delay_seconds";
		public static readonly StringName SetNetworkRetryMaximumDelaySeconds = "set_network_retry_maximum_delay_seconds";
		public static readonly StringName GetNetworkRetryMaximumDelaySeconds = "get_network_retry_maximum_delay_seconds";
		public static readonly StringName Geocode = "geocode";
		public static readonly StringName Search = "search";
		public static readonly StringName Autocomplete = "autocomplete";
		public static readonly StringName CancelRequest = "cancel_request";
		public static readonly StringName CancelAll = "cancel_all";
		public static readonly StringName GetPendingRequestCount = "get_pending_request_count";
		public static readonly StringName GetConfiguration = "get_configuration";
	}

	public class SignalName : Node.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumGeocoderService";

	#region Enums

	public enum Provider : long
	{
		Google = 0L,
		Bing = 1L,
		Default = 2L,
	}

	public enum RequestType : long
	{
		Search = 0L,
		Autocomplete = 1L,
	}

	#endregion

	#region Properties

	public string AccessToken
	{
		get => (string)_object.Get(PropertyName.AccessToken);
		set => _object.Set(PropertyName.AccessToken, value);
	}

	public string ApiUrl
	{
		get => (string)_object.Get(PropertyName.ApiUrl);
		set => _object.Set(PropertyName.ApiUrl, value);
	}

	public int WorkerThreadCount
	{
		get => (int)_object.Get(PropertyName.WorkerThreadCount);
		set => _object.Set(PropertyName.WorkerThreadCount, value);
	}

	public int MaximumNetworkRetries
	{
		get => (int)_object.Get(PropertyName.MaximumNetworkRetries);
		set => _object.Set(PropertyName.MaximumNetworkRetries, value);
	}

	public float NetworkRetryInitialDelaySeconds
	{
		get => (float)_object.Get(PropertyName.NetworkRetryInitialDelaySeconds);
		set => _object.Set(PropertyName.NetworkRetryInitialDelaySeconds, value);
	}

	public float NetworkRetryMaximumDelaySeconds
	{
		get => (float)_object.Get(PropertyName.NetworkRetryMaximumDelaySeconds);
		set => _object.Set(PropertyName.NetworkRetryMaximumDelaySeconds, value);
	}

	public int PendingRequestCount
	{
		get => (int)_object.Get(PropertyName.PendingRequestCount);
	}

	#endregion

	#region Methods

	public void SetAccessToken(string @value)
	{
		_object.Call(MethodName.SetAccessToken, @value);
	}

	public string GetAccessToken()
	{
		return (string)_object.Call(MethodName.GetAccessToken);
	}

	public void SetApiUrl(string @value)
	{
		_object.Call(MethodName.SetApiUrl, @value);
	}

	public string GetApiUrl()
	{
		return (string)_object.Call(MethodName.GetApiUrl);
	}

	public void SetWorkerThreadCount(int @value)
	{
		_object.Call(MethodName.SetWorkerThreadCount, @value);
	}

	public int GetWorkerThreadCount()
	{
		return (int)_object.Call(MethodName.GetWorkerThreadCount);
	}

	public void SetMaximumNetworkRetries(int @value)
	{
		_object.Call(MethodName.SetMaximumNetworkRetries, @value);
	}

	public int GetMaximumNetworkRetries()
	{
		return (int)_object.Call(MethodName.GetMaximumNetworkRetries);
	}

	public void SetNetworkRetryInitialDelaySeconds(float @value)
	{
		_object.Call(MethodName.SetNetworkRetryInitialDelaySeconds, @value);
	}

	public float GetNetworkRetryInitialDelaySeconds()
	{
		return (float)_object.Call(MethodName.GetNetworkRetryInitialDelaySeconds);
	}

	public void SetNetworkRetryMaximumDelaySeconds(float @value)
	{
		_object.Call(MethodName.SetNetworkRetryMaximumDelaySeconds, @value);
	}

	public float GetNetworkRetryMaximumDelaySeconds()
	{
		return (float)_object.Call(MethodName.GetNetworkRetryMaximumDelaySeconds);
	}

	public CesiumGeocoderRequest Geocode(string @query, int @provider = 2, int @request_type = 0)
	{
		return (CesiumGeocoderRequest)_object.Call(MethodName.Geocode, @query, @provider, @request_type);
	}

	public CesiumGeocoderRequest Search(string @query, int @provider = 2)
	{
		return (CesiumGeocoderRequest)_object.Call(MethodName.Search, @query, @provider);
	}

	public CesiumGeocoderRequest Autocomplete(string @query, int @provider = 2)
	{
		return (CesiumGeocoderRequest)_object.Call(MethodName.Autocomplete, @query, @provider);
	}

	public void CancelRequest(int @request_id)
	{
		_object.Call(MethodName.CancelRequest, @request_id);
	}

	public void CancelAll()
	{
		_object.Call(MethodName.CancelAll);
	}

	public int GetPendingRequestCount()
	{
		return (int)_object.Call(MethodName.GetPendingRequestCount);
	}

	public Godot.Collections.Dictionary GetConfiguration()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetConfiguration);
	}

	#endregion
}
