// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGDPanel
{
	// Engine object used for calling engine methods
	protected GodotObject _object;

	public GodotObject NativeObject => _object;

	public CesiumGDPanel() : this(NativeName)
	{
	}
	protected CesiumGDPanel(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGDPanel(Variant variant) : this((GodotObject) variant)
	{
	}
	protected CesiumGDPanel([NotNull] GodotObject @object)
	{
		_object = @object;
	}

	public static implicit operator GodotObject(CesiumGDPanel self) => self?._object;
	public static implicit operator Variant(CesiumGDPanel self) => self?._object;
	public static explicit operator CesiumGDPanel(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : GodotObject.PropertyName
	{

	}

	public class MethodName : GodotObject.MethodName
	{
		public static readonly StringName OpenLearnPage = "open_learn_page";
		public static readonly StringName OpenHelpPage = "open_help_page";
	}

	public class SignalName : GodotObject.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumGDPanel";

	#region Methods

	public static void OpenLearnPage()
	{
		ClassDB.ClassCallStatic(NativeName, MethodName.OpenLearnPage);
	}

	public static void OpenHelpPage()
	{
		ClassDB.ClassCallStatic(NativeName, MethodName.OpenHelpPage);
	}

	#endregion
}
