// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumPropertyAttributeProperty : CesiumMetadataProperty
{
	public CesiumPropertyAttributeProperty() : base(NativeName)
	{
	}
	protected CesiumPropertyAttributeProperty(StringName @class) : base(@class)
	{
	}
	protected CesiumPropertyAttributeProperty(Variant variant) : base(variant)
	{
	}
	protected CesiumPropertyAttributeProperty([NotNull] RefCounted @object) : base(@object)
	{
	}

	public static implicit operator RefCounted(CesiumPropertyAttributeProperty self) => self?._object;
	public static implicit operator Variant(CesiumPropertyAttributeProperty self) => self?._object;
	public static explicit operator CesiumPropertyAttributeProperty(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : CesiumMetadataProperty.PropertyName
	{

	}

	public new class MethodName : CesiumMetadataProperty.MethodName
	{

	}

	public new class SignalName : CesiumMetadataProperty.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumPropertyAttributeProperty";
}
