// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGeoJsonObject
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public Resource NativeObject => _object;

	public CesiumGeoJsonObject() : this(NativeName)
	{
	}
	protected CesiumGeoJsonObject(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGeoJsonObject(Variant variant) : this((Resource) variant)
	{
	}
	protected CesiumGeoJsonObject([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(CesiumGeoJsonObject self) => self?._object;
	public static implicit operator Variant(CesiumGeoJsonObject self) => self?._object;
	public static explicit operator CesiumGeoJsonObject(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName Valid = "valid";
		public static readonly StringName ObjectType = "object_type";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName GetObjectType = "get_object_type";
		public static readonly StringName GetObjectTypeName = "get_object_type_name";
		public static readonly StringName HasBoundingBox = "has_bounding_box";
		public static readonly StringName GetBoundingBox = "get_bounding_box";
		public static readonly StringName GetForeignMembers = "get_foreign_members";
		public static readonly StringName HasStyle = "has_style";
		public static readonly StringName GetStyle = "get_style";
		public static readonly StringName SetStyle = "set_style";
		public static readonly StringName ClearStyle = "clear_style";
		public static readonly StringName GetPointsExact = "get_points_exact";
		public static readonly StringName GetLineStringsExact = "get_line_strings_exact";
		public static readonly StringName GetPolygonsExact = "get_polygons_exact";
		public static readonly StringName GetChildren = "get_children";
		public static readonly StringName IsFeature = "is_feature";
		public static readonly StringName GetFeatureId = "get_feature_id";
		public static readonly StringName GetFeatureProperties = "get_feature_properties";
		public static readonly StringName GetFeatureGeometry = "get_feature_geometry";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumGeoJsonObject";

	#region Enums

	public enum ObjectTypeEnum : long
	{
		Point = 0L,
		MultiPoint = 1L,
		LineString = 2L,
		MultiLineString = 3L,
		Polygon = 4L,
		MultiPolygon = 5L,
		GeometryCollection = 6L,
		Feature = 7L,
		FeatureCollection = 8L,
		Invalid = -1L,
	}

	#endregion

	#region Properties

	public bool Valid
	{
		get => (bool)_object.Get(PropertyName.Valid);
	}

	public int ObjectType
	{
		get => (int)_object.Get(PropertyName.ObjectType);
	}

	#endregion

	#region Methods

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public int GetObjectType()
	{
		return (int)_object.Call(MethodName.GetObjectType);
	}

	public string GetObjectTypeName()
	{
		return (string)_object.Call(MethodName.GetObjectTypeName);
	}

	public bool HasBoundingBox()
	{
		return (bool)_object.Call(MethodName.HasBoundingBox);
	}

	public Godot.Aabb GetBoundingBox()
	{
		return (Godot.Aabb)_object.Call(MethodName.GetBoundingBox);
	}

	public Godot.Collections.Dictionary GetForeignMembers()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetForeignMembers);
	}

	public bool HasStyle()
	{
		return (bool)_object.Call(MethodName.HasStyle);
	}

	public CesiumVectorStyle GetStyle()
	{
		return (CesiumVectorStyle)_object.Call(MethodName.GetStyle);
	}

	public bool SetStyle(CesiumVectorStyle @style)
	{
		return (bool)_object.Call(MethodName.SetStyle, @style);
	}

	public void ClearStyle()
	{
		_object.Call(MethodName.ClearStyle);
	}

	public double[] GetPointsExact()
	{
		return (double[])_object.Call(MethodName.GetPointsExact);
	}

	public Godot.Collections.Array GetLineStringsExact()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetLineStringsExact);
	}

	public Godot.Collections.Array GetPolygonsExact()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetPolygonsExact);
	}

	public Godot.Collections.Array GetChildren()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetChildren);
	}

	public bool IsFeature()
	{
		return (bool)_object.Call(MethodName.IsFeature);
	}

	public Variant GetFeatureId()
	{
		return (Variant)_object.Call(MethodName.GetFeatureId);
	}

	public Godot.Collections.Dictionary GetFeatureProperties()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetFeatureProperties);
	}

	public CesiumGeoJsonObject GetFeatureGeometry()
	{
		return (CesiumGeoJsonObject)_object.Call(MethodName.GetFeatureGeometry);
	}

	#endregion
}
