// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGeocoderResult
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public Resource NativeObject => _object;

	public CesiumGeocoderResult() : this(NativeName)
	{
	}
	protected CesiumGeocoderResult(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGeocoderResult(Variant variant) : this((Resource) variant)
	{
	}
	protected CesiumGeocoderResult([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(CesiumGeocoderResult self) => self?._object;
	public static implicit operator Variant(CesiumGeocoderResult self) => self?._object;
	public static explicit operator CesiumGeocoderResult(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName Attributions = "attributions";
		public static readonly StringName Features = "features";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName GetAttributions = "get_attributions";
		public static readonly StringName GetFeatures = "get_features";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumGeocoderResult";

	#region Properties

	public Godot.Collections.Array Attributions
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.Attributions);
	}

	public Godot.Collections.Array Features
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.Features);
	}

	#endregion

	#region Methods

	public Godot.Collections.Array GetAttributions()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetAttributions);
	}

	public Godot.Collections.Array GetFeatures()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetFeatures);
	}

	#endregion
}
