// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class Cesium3DTilesetLifecycleEventReceiver
{
	// Engine object used for calling engine methods
	protected Node _object;

	public Node NativeObject => _object;

	public Cesium3DTilesetLifecycleEventReceiver() : this(NativeName)
	{
	}
	protected Cesium3DTilesetLifecycleEventReceiver(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected Cesium3DTilesetLifecycleEventReceiver(Variant variant) : this((Node) variant)
	{
	}
	protected Cesium3DTilesetLifecycleEventReceiver([NotNull] Node @object)
	{
		_object = @object;
	}

	public static implicit operator Node(Cesium3DTilesetLifecycleEventReceiver self) => self?._object;
	public static implicit operator Variant(Cesium3DTilesetLifecycleEventReceiver self) => self?._object;
	public static explicit operator Cesium3DTilesetLifecycleEventReceiver(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node.PropertyName
	{
		public static readonly StringName MaterialSelector = "material_selector";
	}

	public class MethodName : Node.MethodName
	{
		public static readonly StringName SetMaterialSelector = "set_material_selector";
		public static readonly StringName GetMaterialSelector = "get_material_selector";
	}

	public class SignalName : Node.SignalName
	{
		public static readonly StringName MaterialCustomizing = "material_customizing";
		public static readonly StringName TileMeshPrimitiveLoaded = "tile_mesh_primitive_loaded";
		public static readonly StringName RasterOverlayAttached = "raster_overlay_attached";
		public static readonly StringName RasterOverlayDetaching = "raster_overlay_detaching";
		public static readonly StringName TileLoaded = "tile_loaded";
		public static readonly StringName TileVisibilityChanged = "tile_visibility_changed";
		public static readonly StringName TileUnloading = "tile_unloading";
	}

	private static readonly StringName NativeName = "Cesium3DTilesetLifecycleEventReceiver";

	#region Properties

	public Godot.Callable MaterialSelector
	{
		get => (Godot.Callable)_object.Get(PropertyName.MaterialSelector);
		set => _object.Set(PropertyName.MaterialSelector, value);
	}

	#endregion

	#region Methods

	public void SetMaterialSelector(Godot.Callable @selector)
	{
		_object.Call(MethodName.SetMaterialSelector, @selector);
	}

	public Godot.Callable GetMaterialSelector()
	{
		return (Godot.Callable)_object.Call(MethodName.GetMaterialSelector);
	}

	#endregion

	#region Signals

	public event Action<GodotObject, Material> MaterialCustomizing
	{
		add
		{
			_object.Connect(SignalName.MaterialCustomizing, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.MaterialCustomizing, Callable.From(value));
		}
	}

	public event Action<GodotObject> TileMeshPrimitiveLoaded
	{
		add
		{
			_object.Connect(SignalName.TileMeshPrimitiveLoaded, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.TileMeshPrimitiveLoaded, Callable.From(value));
		}
	}

	public event Action<GodotObject> RasterOverlayAttached
	{
		add
		{
			_object.Connect(SignalName.RasterOverlayAttached, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.RasterOverlayAttached, Callable.From(value));
		}
	}

	public event Action<GodotObject> RasterOverlayDetaching
	{
		add
		{
			_object.Connect(SignalName.RasterOverlayDetaching, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.RasterOverlayDetaching, Callable.From(value));
		}
	}

	public event Action<GodotObject> TileLoaded
	{
		add
		{
			_object.Connect(SignalName.TileLoaded, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.TileLoaded, Callable.From(value));
		}
	}

	public event Action<GodotObject, bool> TileVisibilityChanged
	{
		add
		{
			_object.Connect(SignalName.TileVisibilityChanged, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.TileVisibilityChanged, Callable.From(value));
		}
	}

	public event Action<GodotObject> TileUnloading
	{
		add
		{
			_object.Connect(SignalName.TileUnloading, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.TileUnloading, Callable.From(value));
		}
	}

	#endregion
}
