// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumUrlUtility
{
	// Engine object used for calling engine methods
	protected GodotObject _object;

	public GodotObject NativeObject => _object;

	public CesiumUrlUtility() : this(NativeName)
	{
	}
	protected CesiumUrlUtility(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumUrlUtility(Variant variant) : this((GodotObject) variant)
	{
	}
	protected CesiumUrlUtility([NotNull] GodotObject @object)
	{
		_object = @object;
	}

	public static implicit operator GodotObject(CesiumUrlUtility self) => self?._object;
	public static implicit operator Variant(CesiumUrlUtility self) => self?._object;
	public static explicit operator CesiumUrlUtility(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : GodotObject.PropertyName
	{

	}

	public class MethodName : GodotObject.MethodName
	{
		public static readonly StringName LocalPathToFileUrl = "local_path_to_file_url";
	}

	public class SignalName : GodotObject.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumUrlUtility";

	#region Methods

	public static string LocalPathToFileUrl(string @path)
	{
		return (string)ClassDB.ClassCallStatic(NativeName, MethodName.LocalPathToFileUrl, @path);
	}

	#endregion
}
