// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGeocoderFeature
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public Resource NativeObject => _object;

	public CesiumGeocoderFeature() : this(NativeName)
	{
	}
	protected CesiumGeocoderFeature(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGeocoderFeature(Variant variant) : this((Resource) variant)
	{
	}
	protected CesiumGeocoderFeature([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(CesiumGeocoderFeature self) => self?._object;
	public static implicit operator Variant(CesiumGeocoderFeature self) => self?._object;
	public static explicit operator CesiumGeocoderFeature(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName DisplayName = "display_name";
		public static readonly StringName LongitudeLatitudeHeight = "longitude_latitude_height";
		public static readonly StringName LongitudeLatitudeHeightComponents = "longitude_latitude_height_components";
		public static readonly StringName GlobeRectangleComponents = "globe_rectangle_components";
		public static readonly StringName IsPoint = "is_point";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName GetDisplayName = "get_display_name";
		public static readonly StringName GetLongitudeLatitudeHeight = "get_longitude_latitude_height";
		public static readonly StringName GetLongitudeLatitudeHeightComponents = "get_longitude_latitude_height_components";
		public static readonly StringName GetGlobeRectangleComponents = "get_globe_rectangle_components";
		public static readonly StringName GetIsPoint = "get_is_point";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumGeocoderFeature";

	#region Properties

	public string DisplayName
	{
		get => (string)_object.Get(PropertyName.DisplayName);
	}

	public Godot.Vector3 LongitudeLatitudeHeight
	{
		get => (Godot.Vector3)_object.Get(PropertyName.LongitudeLatitudeHeight);
	}

	public double[] LongitudeLatitudeHeightComponents
	{
		get => (double[])_object.Get(PropertyName.LongitudeLatitudeHeightComponents);
	}

	public double[] GlobeRectangleComponents
	{
		get => (double[])_object.Get(PropertyName.GlobeRectangleComponents);
	}

	public bool IsPoint
	{
		get => (bool)_object.Get(PropertyName.IsPoint);
	}

	#endregion

	#region Methods

	public string GetDisplayName()
	{
		return (string)_object.Call(MethodName.GetDisplayName);
	}

	public Godot.Vector3 GetLongitudeLatitudeHeight()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetLongitudeLatitudeHeight);
	}

	public double[] GetLongitudeLatitudeHeightComponents()
	{
		return (double[])_object.Call(MethodName.GetLongitudeLatitudeHeightComponents);
	}

	public double[] GetGlobeRectangleComponents()
	{
		return (double[])_object.Call(MethodName.GetGlobeRectangleComponents);
	}

	public bool GetIsPoint()
	{
		return (bool)_object.Call(MethodName.GetIsPoint);
	}

	#endregion
}
