// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumTileDebugState
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumTileDebugState() : this(NativeName)
	{
	}
	protected CesiumTileDebugState(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumTileDebugState(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumTileDebugState([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumTileDebugState self) => self?._object;
	public static implicit operator Variant(CesiumTileDebugState self) => self?._object;
	public static explicit operator CesiumTileDebugState(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName FrameNumber = "frame_number";
		public static readonly StringName TileId = "tile_id";
		public static readonly StringName ParentTileId = "parent_tile_id";
		public static readonly StringName HierarchyPath = "hierarchy_path";
		public static readonly StringName ParentHierarchyPath = "parent_hierarchy_path";
		public static readonly StringName Depth = "depth";
		public static readonly StringName SelectionRole = "selection_role";
		public static readonly StringName SelectionRoleName = "selection_role_name";
		public static readonly StringName LoadState = "load_state";
		public static readonly StringName LoadStateName = "load_state_name";
		public static readonly StringName RefineMode = "refine_mode";
		public static readonly StringName RefineModeName = "refine_mode_name";
		public static readonly StringName GeometricError = "geometric_error";
		public static readonly StringName ChildCount = "child_count";
		public static readonly StringName ReferenceCount = "reference_count";
		public static readonly StringName NeedsWorkerThreadLoading = "needs_worker_thread_loading";
		public static readonly StringName NeedsMainThreadLoading = "needs_main_thread_loading";
		public static readonly StringName Renderable = "renderable";
		public static readonly StringName HasRenderContent = "has_render_content";
		public static readonly StringName HasExternalContent = "has_external_content";
		public static readonly StringName HasEmptyContent = "has_empty_content";
		public static readonly StringName TileBounds = "tile_bounds";
		public static readonly StringName ContentBounds = "content_bounds";
		public static readonly StringName ViewerRequestBounds = "viewer_request_bounds";
		public static readonly StringName WorldBoundsTransform = "world_bounds_transform";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetFrameNumber = "get_frame_number";
		public static readonly StringName GetTileId = "get_tile_id";
		public static readonly StringName GetParentTileId = "get_parent_tile_id";
		public static readonly StringName GetHierarchyPath = "get_hierarchy_path";
		public static readonly StringName GetParentHierarchyPath = "get_parent_hierarchy_path";
		public static readonly StringName GetDepth = "get_depth";
		public static readonly StringName GetSelectionRole = "get_selection_role";
		public static readonly StringName GetSelectionRoleName = "get_selection_role_name";
		public static readonly StringName GetLoadState = "get_load_state";
		public static readonly StringName GetLoadStateName = "get_load_state_name";
		public static readonly StringName GetRefineMode = "get_refine_mode";
		public static readonly StringName GetRefineModeName = "get_refine_mode_name";
		public static readonly StringName GetGeometricError = "get_geometric_error";
		public static readonly StringName GetChildCount = "get_child_count";
		public static readonly StringName GetNeedsWorkerThreadLoading = "get_needs_worker_thread_loading";
		public static readonly StringName GetNeedsMainThreadLoading = "get_needs_main_thread_loading";
		public static readonly StringName GetRenderable = "get_renderable";
		public static readonly StringName GetHasRenderContent = "get_has_render_content";
		public static readonly StringName GetHasExternalContent = "get_has_external_content";
		public static readonly StringName GetHasEmptyContent = "get_has_empty_content";
		public static readonly StringName GetTileBounds = "get_tile_bounds";
		public static readonly StringName GetContentBounds = "get_content_bounds";
		public static readonly StringName GetViewerRequestBounds = "get_viewer_request_bounds";
		public static readonly StringName GetWorldBoundsTransform = "get_world_bounds_transform";
		public static readonly StringName ToDictionary = "to_dictionary";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumTileDebugState";

	#region Enums

	public enum SelectionRoleEnum : long
	{
		Unknown = 0L,
		Selected = 1L,
		Fading = 2L,
		Ancestor = 3L,
		Child = 4L,
	}

	public enum LoadStateEnum : long
	{
		Unloading = -2L,
		FailedTemporarily = -1L,
		Unloaded = 0L,
		ContentLoading = 1L,
		ContentLoaded = 2L,
		Done = 3L,
		Failed = 4L,
	}

	public enum RefineModeEnum : long
	{
		Add = 0L,
		Replace = 1L,
	}

	#endregion

	#region Properties

	public int FrameNumber
	{
		get => (int)_object.Get(PropertyName.FrameNumber);
	}

	public string TileId
	{
		get => (string)_object.Get(PropertyName.TileId);
	}

	public string ParentTileId
	{
		get => (string)_object.Get(PropertyName.ParentTileId);
	}

	public string HierarchyPath
	{
		get => (string)_object.Get(PropertyName.HierarchyPath);
	}

	public string ParentHierarchyPath
	{
		get => (string)_object.Get(PropertyName.ParentHierarchyPath);
	}

	public int Depth
	{
		get => (int)_object.Get(PropertyName.Depth);
	}

	public int SelectionRole
	{
		get => (int)_object.Get(PropertyName.SelectionRole);
	}

	public string SelectionRoleName
	{
		get => (string)_object.Get(PropertyName.SelectionRoleName);
	}

	public int LoadState
	{
		get => (int)_object.Get(PropertyName.LoadState);
	}

	public string LoadStateName
	{
		get => (string)_object.Get(PropertyName.LoadStateName);
	}

	public int RefineMode
	{
		get => (int)_object.Get(PropertyName.RefineMode);
	}

	public string RefineModeName
	{
		get => (string)_object.Get(PropertyName.RefineModeName);
	}

	public float GeometricError
	{
		get => (float)_object.Get(PropertyName.GeometricError);
	}

	public int ChildCount
	{
		get => (int)_object.Get(PropertyName.ChildCount);
	}

	public int ReferenceCount
	{
		get => (int)_object.Get(PropertyName.ReferenceCount);
	}

	public bool NeedsWorkerThreadLoading
	{
		get => (bool)_object.Get(PropertyName.NeedsWorkerThreadLoading);
	}

	public bool NeedsMainThreadLoading
	{
		get => (bool)_object.Get(PropertyName.NeedsMainThreadLoading);
	}

	public bool Renderable
	{
		get => (bool)_object.Get(PropertyName.Renderable);
	}

	public bool HasRenderContent
	{
		get => (bool)_object.Get(PropertyName.HasRenderContent);
	}

	public bool HasExternalContent
	{
		get => (bool)_object.Get(PropertyName.HasExternalContent);
	}

	public bool HasEmptyContent
	{
		get => (bool)_object.Get(PropertyName.HasEmptyContent);
	}

	public GodotObject TileBounds
	{
		get => (GodotObject)_object.Get(PropertyName.TileBounds);
	}

	public GodotObject ContentBounds
	{
		get => (GodotObject)_object.Get(PropertyName.ContentBounds);
	}

	public GodotObject ViewerRequestBounds
	{
		get => (GodotObject)_object.Get(PropertyName.ViewerRequestBounds);
	}

	public Godot.Transform3D WorldBoundsTransform
	{
		get => (Godot.Transform3D)_object.Get(PropertyName.WorldBoundsTransform);
	}

	#endregion

	#region Methods

	public int GetFrameNumber()
	{
		return (int)_object.Call(MethodName.GetFrameNumber);
	}

	public string GetTileId()
	{
		return (string)_object.Call(MethodName.GetTileId);
	}

	public string GetParentTileId()
	{
		return (string)_object.Call(MethodName.GetParentTileId);
	}

	public string GetHierarchyPath()
	{
		return (string)_object.Call(MethodName.GetHierarchyPath);
	}

	public string GetParentHierarchyPath()
	{
		return (string)_object.Call(MethodName.GetParentHierarchyPath);
	}

	public int GetDepth()
	{
		return (int)_object.Call(MethodName.GetDepth);
	}

	public int GetSelectionRole()
	{
		return (int)_object.Call(MethodName.GetSelectionRole);
	}

	public string GetSelectionRoleName()
	{
		return (string)_object.Call(MethodName.GetSelectionRoleName);
	}

	public int GetLoadState()
	{
		return (int)_object.Call(MethodName.GetLoadState);
	}

	public string GetLoadStateName()
	{
		return (string)_object.Call(MethodName.GetLoadStateName);
	}

	public int GetRefineMode()
	{
		return (int)_object.Call(MethodName.GetRefineMode);
	}

	public string GetRefineModeName()
	{
		return (string)_object.Call(MethodName.GetRefineModeName);
	}

	public float GetGeometricError()
	{
		return (float)_object.Call(MethodName.GetGeometricError);
	}

	public int GetChildCount()
	{
		return (int)_object.Call(MethodName.GetChildCount);
	}

	public int GetReferenceCount()
	{
		return (int)_object.Call(MethodName.GetReferenceCount);
	}

	public bool GetNeedsWorkerThreadLoading()
	{
		return (bool)_object.Call(MethodName.GetNeedsWorkerThreadLoading);
	}

	public bool GetNeedsMainThreadLoading()
	{
		return (bool)_object.Call(MethodName.GetNeedsMainThreadLoading);
	}

	public bool GetRenderable()
	{
		return (bool)_object.Call(MethodName.GetRenderable);
	}

	public bool GetHasRenderContent()
	{
		return (bool)_object.Call(MethodName.GetHasRenderContent);
	}

	public bool GetHasExternalContent()
	{
		return (bool)_object.Call(MethodName.GetHasExternalContent);
	}

	public bool GetHasEmptyContent()
	{
		return (bool)_object.Call(MethodName.GetHasEmptyContent);
	}

	public CesiumBoundingVolume GetTileBounds()
	{
		return (CesiumBoundingVolume)_object.Call(MethodName.GetTileBounds);
	}

	public CesiumBoundingVolume GetContentBounds()
	{
		return (CesiumBoundingVolume)_object.Call(MethodName.GetContentBounds);
	}

	public CesiumBoundingVolume GetViewerRequestBounds()
	{
		return (CesiumBoundingVolume)_object.Call(MethodName.GetViewerRequestBounds);
	}

	public Godot.Transform3D GetWorldBoundsTransform()
	{
		return (Godot.Transform3D)_object.Call(MethodName.GetWorldBoundsTransform);
	}

	public Godot.Collections.Dictionary ToDictionary()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.ToDictionary);
	}

	#endregion
}
