// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumHTTPRequestNode
{
	// Engine object used for calling engine methods
	protected HttpRequest _object;

	public HttpRequest NativeObject => _object;

	public CesiumHTTPRequestNode() : this(NativeName)
	{
	}
	protected CesiumHTTPRequestNode(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumHTTPRequestNode(Variant variant) : this((HttpRequest) variant)
	{
	}
	protected CesiumHTTPRequestNode([NotNull] HttpRequest @object)
	{
		_object = @object;
	}

	public static implicit operator HttpRequest(CesiumHTTPRequestNode self) => self?._object;
	public static implicit operator Variant(CesiumHTTPRequestNode self) => self?._object;
	public static explicit operator CesiumHTTPRequestNode(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : HttpRequest.PropertyName
	{

	}

	public class MethodName : HttpRequest.MethodName
	{
		public static readonly StringName OnRequestCompleted = "on_request_completed";
	}

	public class SignalName : HttpRequest.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumHTTPRequestNode";

	#region Methods

	public void OnRequestCompleted(int @result, int @responseCode, string[] @headers, byte[] @body)
	{
		_object.Call(MethodName.OnRequestCompleted, @result, @responseCode, @headers, @body);
	}

	#endregion
}
