// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumIonRasterOverlay : CesiumRasterOverlay
{
	public CesiumIonRasterOverlay() : base(NativeName)
	{
	}
	protected CesiumIonRasterOverlay(StringName @class) : base(@class)
	{
	}
	protected CesiumIonRasterOverlay(Variant variant) : base(variant)
	{
	}
	protected CesiumIonRasterOverlay([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(CesiumIonRasterOverlay self) => self?._object;
	public static implicit operator Variant(CesiumIonRasterOverlay self) => self?._object;
	public static explicit operator CesiumIonRasterOverlay(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : CesiumRasterOverlay.PropertyName
	{
		public static readonly StringName AssetId = "asset_id";
		public static readonly StringName IonAccessToken = "ion_access_token";
		public static readonly StringName IonApiUrl = "ion_api_url";
		public static readonly StringName AssetOptions = "asset_options";
		public static readonly StringName DataSource = "data_source";
		public static readonly StringName Url = "url";
	}

	public new class MethodName : CesiumRasterOverlay.MethodName
	{
		public static readonly StringName SetAssetId = "set_asset_id";
		public static readonly StringName GetAssetId = "get_asset_id";
		public static readonly StringName SetIonAccessToken = "set_ion_access_token";
		public static readonly StringName GetIonAccessToken = "get_ion_access_token";
		public static readonly StringName SetIonApiUrl = "set_ion_api_url";
		public static readonly StringName GetIonApiUrl = "get_ion_api_url";
		public static readonly StringName SetAssetOptions = "set_asset_options";
		public static readonly StringName GetAssetOptions = "get_asset_options";
		public static readonly StringName SetDataSource = "set_data_source";
		public static readonly StringName GetDataSource = "get_data_source";
		public static readonly StringName SetUrl = "set_url";
		public static readonly StringName GetUrl = "get_url";
	}

	public new class SignalName : CesiumRasterOverlay.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumIonRasterOverlay";

	#region Enums

	public enum CesiumDataSource : long
	{
		CesiumIon = 0L,
		Url = 1L,
	}

	#endregion

	#region Properties

	public int AssetId
	{
		get => (int)_object.Get(PropertyName.AssetId);
		set => _object.Set(PropertyName.AssetId, value);
	}

	public string IonAccessToken
	{
		get => (string)_object.Get(PropertyName.IonAccessToken);
		set => _object.Set(PropertyName.IonAccessToken, value);
	}

	public string IonApiUrl
	{
		get => (string)_object.Get(PropertyName.IonApiUrl);
		set => _object.Set(PropertyName.IonApiUrl, value);
	}

	public string AssetOptions
	{
		get => (string)_object.Get(PropertyName.AssetOptions);
		set => _object.Set(PropertyName.AssetOptions, value);
	}

	public int DataSource
	{
		get => (int)_object.Get(PropertyName.DataSource);
		set => _object.Set(PropertyName.DataSource, value);
	}

	public string Url
	{
		get => (string)_object.Get(PropertyName.Url);
		set => _object.Set(PropertyName.Url, value);
	}

	#endregion

	#region Methods

	public void SetAssetId(int @id)
	{
		_object.Call(MethodName.SetAssetId, @id);
	}

	public int GetAssetId()
	{
		return (int)_object.Call(MethodName.GetAssetId);
	}

	public void SetIonAccessToken(string @token)
	{
		_object.Call(MethodName.SetIonAccessToken, @token);
	}

	public string GetIonAccessToken()
	{
		return (string)_object.Call(MethodName.GetIonAccessToken);
	}

	public void SetIonApiUrl(string @url)
	{
		_object.Call(MethodName.SetIonApiUrl, @url);
	}

	public string GetIonApiUrl()
	{
		return (string)_object.Call(MethodName.GetIonApiUrl);
	}

	public void SetAssetOptions(string @options)
	{
		_object.Call(MethodName.SetAssetOptions, @options);
	}

	public string GetAssetOptions()
	{
		return (string)_object.Call(MethodName.GetAssetOptions);
	}

	public void SetDataSource(int @data_source)
	{
		_object.Call(MethodName.SetDataSource, @data_source);
	}

	public int GetDataSource()
	{
		return (int)_object.Call(MethodName.GetDataSource);
	}

	public void SetUrl(string @url)
	{
		_object.Call(MethodName.SetUrl, @url);
	}

	public string GetUrl()
	{
		return (string)_object.Call(MethodName.GetUrl);
	}

	#endregion
}
