// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumCameraManager
{
	// Engine object used for calling engine methods
	protected Node _object;

	public Node NativeObject => _object;

	public CesiumCameraManager() : this(NativeName)
	{
	}
	protected CesiumCameraManager(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumCameraManager(Variant variant) : this((Node) variant)
	{
	}
	protected CesiumCameraManager([NotNull] Node @object)
	{
		_object = @object;
	}

	public static implicit operator Node(CesiumCameraManager self) => self?._object;
	public static implicit operator Variant(CesiumCameraManager self) => self?._object;
	public static explicit operator CesiumCameraManager(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node.PropertyName
	{
		public static readonly StringName UseViewportCamera = "use_viewport_camera";
		public static readonly StringName AdditionalCameraPaths = "additional_camera_paths";
		public static readonly StringName AdditionalCameraEnabled = "additional_camera_enabled";
	}

	public class MethodName : Node.MethodName
	{
		public static readonly StringName SetUseViewportCamera = "set_use_viewport_camera";
		public static readonly StringName GetUseViewportCamera = "get_use_viewport_camera";
		public static readonly StringName SetAdditionalCameraPaths = "set_additional_camera_paths";
		public static readonly StringName GetAdditionalCameraPaths = "get_additional_camera_paths";
		public static readonly StringName SetAdditionalCameraEnabled = "set_additional_camera_enabled";
		public static readonly StringName GetAdditionalCameraEnabled = "get_additional_camera_enabled";
		public static readonly StringName AddCamera = "add_camera";
		public static readonly StringName RemoveCameraAt = "remove_camera_at";
		public static readonly StringName MoveCamera = "move_camera";
		public static readonly StringName SetCameraPath = "set_camera_path";
		public static readonly StringName GetCameraPath = "get_camera_path";
		public static readonly StringName SetCameraEnabled = "set_camera_enabled";
		public static readonly StringName GetCameraEnabled = "get_camera_enabled";
		public static readonly StringName GetCameraCount = "get_camera_count";
		public static readonly StringName ClearCameras = "clear_cameras";
		public static readonly StringName GetResolvedCameras = "get_resolved_cameras";
		public static readonly StringName GetResolutionDiagnostics = "get_resolution_diagnostics";
	}

	public class SignalName : Node.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumCameraManager";

	#region Properties

	public bool UseViewportCamera
	{
		get => (bool)_object.Get(PropertyName.UseViewportCamera);
		set => _object.Set(PropertyName.UseViewportCamera, value);
	}

	public Godot.Collections.Array AdditionalCameraPaths
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.AdditionalCameraPaths);
		set => _object.Set(PropertyName.AdditionalCameraPaths, value);
	}

	public Godot.Collections.Array AdditionalCameraEnabled
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.AdditionalCameraEnabled);
		set => _object.Set(PropertyName.AdditionalCameraEnabled, value);
	}

	#endregion

	#region Methods

	public void SetUseViewportCamera(bool @use_viewport_camera)
	{
		_object.Call(MethodName.SetUseViewportCamera, @use_viewport_camera);
	}

	public bool GetUseViewportCamera()
	{
		return (bool)_object.Call(MethodName.GetUseViewportCamera);
	}

	public void SetAdditionalCameraPaths(Godot.Collections.Array @paths)
	{
		_object.Call(MethodName.SetAdditionalCameraPaths, @paths);
	}

	public Godot.Collections.Array GetAdditionalCameraPaths()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetAdditionalCameraPaths);
	}

	public void SetAdditionalCameraEnabled(Godot.Collections.Array @enabled)
	{
		_object.Call(MethodName.SetAdditionalCameraEnabled, @enabled);
	}

	public Godot.Collections.Array GetAdditionalCameraEnabled()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetAdditionalCameraEnabled);
	}

	public int AddCamera(Godot.NodePath @camera_path, bool @enabled = true)
	{
		return (int)_object.Call(MethodName.AddCamera, @camera_path, @enabled);
	}

	public bool RemoveCameraAt(int @index)
	{
		return (bool)_object.Call(MethodName.RemoveCameraAt, @index);
	}

	public bool MoveCamera(int @from_index, int @to_index)
	{
		return (bool)_object.Call(MethodName.MoveCamera, @from_index, @to_index);
	}

	public bool SetCameraPath(int @index, Godot.NodePath @camera_path)
	{
		return (bool)_object.Call(MethodName.SetCameraPath, @index, @camera_path);
	}

	public Godot.NodePath GetCameraPath(int @index)
	{
		return (Godot.NodePath)_object.Call(MethodName.GetCameraPath, @index);
	}

	public bool SetCameraEnabled(int @index, bool @enabled)
	{
		return (bool)_object.Call(MethodName.SetCameraEnabled, @index, @enabled);
	}

	public bool GetCameraEnabled(int @index)
	{
		return (bool)_object.Call(MethodName.GetCameraEnabled, @index);
	}

	public int GetCameraCount()
	{
		return (int)_object.Call(MethodName.GetCameraCount);
	}

	public void ClearCameras()
	{
		_object.Call(MethodName.ClearCameras);
	}

	public Godot.Collections.Array GetResolvedCameras(Node3D @world_context)
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetResolvedCameras, @world_context);
	}

	public Godot.Collections.Dictionary GetResolutionDiagnostics(Node3D @world_context)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetResolutionDiagnostics, @world_context);
	}

	#endregion
}
