// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumPropertyTable
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumPropertyTable() : this(NativeName)
	{
	}
	protected CesiumPropertyTable(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumPropertyTable(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumPropertyTable([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumPropertyTable self) => self?._object;
	public static implicit operator Variant(CesiumPropertyTable self) => self?._object;
	public static explicit operator CesiumPropertyTable(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName TableName = "table_name";
		public static readonly StringName ClassName = "class_name";
		public static readonly StringName Count = "count";
		public static readonly StringName Properties = "properties";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName GetTableName = "get_table_name";
		public static readonly StringName GetClassName = "get_class_name";
		public static readonly StringName GetCount = "get_count";
		public static readonly StringName GetProperties = "get_properties";
		public static readonly StringName GetPropertyNames = "get_property_names";
		public static readonly StringName FindProperty = "find_property";
		public static readonly StringName GetMetadataValuesForFeature = "get_metadata_values_for_feature";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumPropertyTable";

	#region Properties

	public string TableName
	{
		get => (string)_object.Get(PropertyName.TableName);
	}

	public string ClassName
	{
		get => (string)_object.Get(PropertyName.ClassName);
	}

	public int Count
	{
		get => (int)_object.Get(PropertyName.Count);
	}

	public Godot.Collections.Dictionary Properties
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.Properties);
	}

	#endregion

	#region Methods

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public string GetTableName()
	{
		return (string)_object.Call(MethodName.GetTableName);
	}

	public string GetClassName()
	{
		return (string)_object.Call(MethodName.GetClassName);
	}

	public int GetCount()
	{
		return (int)_object.Call(MethodName.GetCount);
	}

	public Godot.Collections.Dictionary GetProperties()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetProperties);
	}

	public Godot.Collections.Array GetPropertyNames()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetPropertyNames);
	}

	public CesiumMetadataProperty FindProperty(string @property_id)
	{
		return (CesiumMetadataProperty)_object.Call(MethodName.FindProperty, @property_id);
	}

	public Godot.Collections.Dictionary GetMetadataValuesForFeature(int @feature_id)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetMetadataValuesForFeature, @feature_id);
	}

	#endregion
}
