// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumMetadataProperty
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumMetadataProperty() : this(NativeName)
	{
	}
	protected CesiumMetadataProperty(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumMetadataProperty(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumMetadataProperty([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumMetadataProperty self) => self?._object;
	public static implicit operator Variant(CesiumMetadataProperty self) => self?._object;
	public static explicit operator CesiumMetadataProperty(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Status = "status";
		public static readonly StringName StatusName = "status_name";
		public static readonly StringName PropertyId = "property_id";
		public static readonly StringName ValueType = "value_type";
		public static readonly StringName ComponentType = "component_type";
		public static readonly StringName EnumType = "enum_type";
		public static readonly StringName IsArray = "is_array";
		public static readonly StringName Normalized = "normalized";
		public static readonly StringName FixedArrayCount = "fixed_array_count";
		public static readonly StringName Size = "size";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetStatus = "get_status";
		public static readonly StringName GetStatusName = "get_status_name";
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName GetPropertyId = "get_property_id";
		public static readonly StringName GetValueType = "get_value_type";
		public static readonly StringName GetComponentType = "get_component_type";
		public static readonly StringName GetEnumType = "get_enum_type";
		public static readonly StringName GetIsArray = "get_is_array";
		public static readonly StringName GetNormalized = "get_normalized";
		public static readonly StringName GetFixedArrayCount = "get_fixed_array_count";
		public static readonly StringName GetSize = "get_size";
		public static readonly StringName GetValue = "get_value";
		public static readonly StringName GetRawValue = "get_raw_value";
		public static readonly StringName GetValues = "get_values";
		public static readonly StringName GetRawValues = "get_raw_values";
		public static readonly StringName GetValueTransformDetails = "get_value_transform_details";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumMetadataProperty";

	#region Enums

	public enum StatusEnum : long
	{
		Valid = 0L,
		EmptyPropertyWithDefault = 1L,
		ErrorInvalidProperty = 2L,
		ErrorInvalidPropertyData = 3L,
	}

	#endregion

	#region Properties

	public int Status
	{
		get => (int)_object.Get(PropertyName.Status);
	}

	public string StatusName
	{
		get => (string)_object.Get(PropertyName.StatusName);
	}

	public string PropertyId
	{
		get => (string)_object.Get(PropertyName.PropertyId);
	}

	public string ValueType
	{
		get => (string)_object.Get(PropertyName.ValueType);
	}

	public string ComponentType
	{
		get => (string)_object.Get(PropertyName.ComponentType);
	}

	public string EnumType
	{
		get => (string)_object.Get(PropertyName.EnumType);
	}

	public bool IsArray
	{
		get => (bool)_object.Get(PropertyName.IsArray);
	}

	public bool Normalized
	{
		get => (bool)_object.Get(PropertyName.Normalized);
	}

	public int FixedArrayCount
	{
		get => (int)_object.Get(PropertyName.FixedArrayCount);
	}

	public int Size
	{
		get => (int)_object.Get(PropertyName.Size);
	}

	#endregion

	#region Methods

	public int GetStatus()
	{
		return (int)_object.Call(MethodName.GetStatus);
	}

	public string GetStatusName()
	{
		return (string)_object.Call(MethodName.GetStatusName);
	}

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public string GetPropertyId()
	{
		return (string)_object.Call(MethodName.GetPropertyId);
	}

	public string GetValueType()
	{
		return (string)_object.Call(MethodName.GetValueType);
	}

	public string GetComponentType()
	{
		return (string)_object.Call(MethodName.GetComponentType);
	}

	public string GetEnumType()
	{
		return (string)_object.Call(MethodName.GetEnumType);
	}

	public bool GetIsArray()
	{
		return (bool)_object.Call(MethodName.GetIsArray);
	}

	public bool GetNormalized()
	{
		return (bool)_object.Call(MethodName.GetNormalized);
	}

	public int GetFixedArrayCount()
	{
		return (int)_object.Call(MethodName.GetFixedArrayCount);
	}

	public int GetSize()
	{
		return (int)_object.Call(MethodName.GetSize);
	}

	public Variant GetValue(int @feature_id)
	{
		return (Variant)_object.Call(MethodName.GetValue, @feature_id);
	}

	public Variant GetRawValue(int @feature_id)
	{
		return (Variant)_object.Call(MethodName.GetRawValue, @feature_id);
	}

	public Godot.Collections.Array GetValues()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetValues);
	}

	public Godot.Collections.Array GetRawValues()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetRawValues);
	}

	public Godot.Collections.Dictionary GetValueTransformDetails()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetValueTransformDetails);
	}

	#endregion
}
