// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGDCreditSystem
{
	// Engine object used for calling engine methods
	protected BoxContainer _object;

	public BoxContainer NativeObject => _object;

	public CesiumGDCreditSystem() : this(NativeName)
	{
	}
	protected CesiumGDCreditSystem(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGDCreditSystem(Variant variant) : this((BoxContainer) variant)
	{
	}
	protected CesiumGDCreditSystem([NotNull] BoxContainer @object)
	{
		_object = @object;
	}

	public static implicit operator BoxContainer(CesiumGDCreditSystem self) => self?._object;
	public static implicit operator Variant(CesiumGDCreditSystem self) => self?._object;
	public static explicit operator CesiumGDCreditSystem(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : BoxContainer.PropertyName
	{
		public static readonly StringName CurrentCredits = "current_credits";
		public static readonly StringName CurrentCreditCount = "current_credit_count";
		public static readonly StringName CurrentHtml = "current_html";
		public static readonly StringName CurrentPlainText = "current_plain_text";
		public static readonly StringName OnScreenText = "on_screen_text";
		public static readonly StringName PopupText = "popup_text";
		public static readonly StringName CreditsUpdated = "credits_updated";
		public static readonly StringName HasHiddenCredits = "has_hidden_credits";
		public static readonly StringName LoadedCreditImageCount = "loaded_credit_image_count";
		public static readonly StringName PendingCreditImageCount = "pending_credit_image_count";
		public static readonly StringName FailedCreditImageCount = "failed_credit_image_count";
		public static readonly StringName PresenterEnabled = "presenter_enabled";
		public static readonly StringName OpenLinksExternally = "open_links_externally";
		public static readonly StringName RemoteCreditImagesEnabled = "remote_credit_images_enabled";
	}

	public class MethodName : BoxContainer.MethodName
	{
		public static readonly StringName GetCurrentCredits = "get_current_credits";
		public static readonly StringName GetCurrentCreditCount = "get_current_credit_count";
		public static readonly StringName GetCurrentHtml = "get_current_html";
		public static readonly StringName GetCurrentPlainText = "get_current_plain_text";
		public static readonly StringName GetOnScreenText = "get_on_screen_text";
		public static readonly StringName GetPopupText = "get_popup_text";
		public static readonly StringName GetCreditsUpdated = "get_credits_updated";
		public static readonly StringName GetHasHiddenCredits = "get_has_hidden_credits";
		public static readonly StringName GetLoadedCreditImageCount = "get_loaded_credit_image_count";
		public static readonly StringName GetPendingCreditImageCount = "get_pending_credit_image_count";
		public static readonly StringName GetFailedCreditImageCount = "get_failed_credit_image_count";
		public static readonly StringName GetCreditImage = "get_credit_image";
		public static readonly StringName SetPresenterEnabled = "set_presenter_enabled";
		public static readonly StringName GetPresenterEnabled = "get_presenter_enabled";
		public static readonly StringName SetOpenLinksExternally = "set_open_links_externally";
		public static readonly StringName GetOpenLinksExternally = "get_open_links_externally";
		public static readonly StringName SetRemoteCreditImagesEnabled = "set_remote_credit_images_enabled";
		public static readonly StringName GetRemoteCreditImagesEnabled = "get_remote_credit_images_enabled";
		public static readonly StringName RetryFailedCreditImages = "retry_failed_credit_images";
		public static readonly StringName ShowAttributionPopup = "show_attribution_popup";
		public static readonly StringName HideAttributionPopup = "hide_attribution_popup";
		public static readonly StringName IsAttributionPopupVisible = "is_attribution_popup_visible";
		public static readonly StringName UpdateCredits = "update_credits";
		public static readonly StringName TurnOn = "turn_on";
		public static readonly StringName TurnOff = "turn_off";
	}

	public class SignalName : BoxContainer.SignalName
	{
		public static readonly StringName CreditsChanged = "credits_changed";
		public static readonly StringName CreditLinkClicked = "credit_link_clicked";
		public static readonly StringName CreditImageLoaded = "credit_image_loaded";
		public static readonly StringName CreditImageFailed = "credit_image_failed";
		public static readonly StringName PresenterEnabledChanged = "presenter_enabled_changed";
	}

	private static readonly StringName NativeName = "CesiumGDCreditSystem";

	#region Properties

	public Godot.Collections.Array CurrentCredits
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.CurrentCredits);
	}

	public int CurrentCreditCount
	{
		get => (int)_object.Get(PropertyName.CurrentCreditCount);
	}

	public string CurrentHtml
	{
		get => (string)_object.Get(PropertyName.CurrentHtml);
	}

	public string CurrentPlainText
	{
		get => (string)_object.Get(PropertyName.CurrentPlainText);
	}

	public string OnScreenText
	{
		get => (string)_object.Get(PropertyName.OnScreenText);
	}

	public string PopupText
	{
		get => (string)_object.Get(PropertyName.PopupText);
	}

	public bool CreditsUpdated
	{
		get => (bool)_object.Get(PropertyName.CreditsUpdated);
	}

	public bool HasHiddenCredits
	{
		get => (bool)_object.Get(PropertyName.HasHiddenCredits);
	}

	public int LoadedCreditImageCount
	{
		get => (int)_object.Get(PropertyName.LoadedCreditImageCount);
	}

	public int PendingCreditImageCount
	{
		get => (int)_object.Get(PropertyName.PendingCreditImageCount);
	}

	public int FailedCreditImageCount
	{
		get => (int)_object.Get(PropertyName.FailedCreditImageCount);
	}

	public bool PresenterEnabled
	{
		get => (bool)_object.Get(PropertyName.PresenterEnabled);
		set => _object.Set(PropertyName.PresenterEnabled, value);
	}

	public bool OpenLinksExternally
	{
		get => (bool)_object.Get(PropertyName.OpenLinksExternally);
		set => _object.Set(PropertyName.OpenLinksExternally, value);
	}

	public bool RemoteCreditImagesEnabled
	{
		get => (bool)_object.Get(PropertyName.RemoteCreditImagesEnabled);
		set => _object.Set(PropertyName.RemoteCreditImagesEnabled, value);
	}

	#endregion

	#region Methods

	public Godot.Collections.Array GetCurrentCredits()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetCurrentCredits);
	}

	public int GetCurrentCreditCount()
	{
		return (int)_object.Call(MethodName.GetCurrentCreditCount);
	}

	public string GetCurrentHtml()
	{
		return (string)_object.Call(MethodName.GetCurrentHtml);
	}

	public string GetCurrentPlainText()
	{
		return (string)_object.Call(MethodName.GetCurrentPlainText);
	}

	public string GetOnScreenText()
	{
		return (string)_object.Call(MethodName.GetOnScreenText);
	}

	public string GetPopupText()
	{
		return (string)_object.Call(MethodName.GetPopupText);
	}

	public bool GetCreditsUpdated()
	{
		return (bool)_object.Call(MethodName.GetCreditsUpdated);
	}

	public bool GetHasHiddenCredits()
	{
		return (bool)_object.Call(MethodName.GetHasHiddenCredits);
	}

	public int GetLoadedCreditImageCount()
	{
		return (int)_object.Call(MethodName.GetLoadedCreditImageCount);
	}

	public int GetPendingCreditImageCount()
	{
		return (int)_object.Call(MethodName.GetPendingCreditImageCount);
	}

	public int GetFailedCreditImageCount()
	{
		return (int)_object.Call(MethodName.GetFailedCreditImageCount);
	}

	public Texture2D GetCreditImage(string @url)
	{
		return (Texture2D)_object.Call(MethodName.GetCreditImage, @url);
	}

	public void SetPresenterEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetPresenterEnabled, @enabled);
	}

	public bool GetPresenterEnabled()
	{
		return (bool)_object.Call(MethodName.GetPresenterEnabled);
	}

	public void SetOpenLinksExternally(bool @enabled)
	{
		_object.Call(MethodName.SetOpenLinksExternally, @enabled);
	}

	public bool GetOpenLinksExternally()
	{
		return (bool)_object.Call(MethodName.GetOpenLinksExternally);
	}

	public void SetRemoteCreditImagesEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetRemoteCreditImagesEnabled, @enabled);
	}

	public bool GetRemoteCreditImagesEnabled()
	{
		return (bool)_object.Call(MethodName.GetRemoteCreditImagesEnabled);
	}

	public void RetryFailedCreditImages()
	{
		_object.Call(MethodName.RetryFailedCreditImages);
	}

	public void ShowAttributionPopup()
	{
		_object.Call(MethodName.ShowAttributionPopup);
	}

	public void HideAttributionPopup()
	{
		_object.Call(MethodName.HideAttributionPopup);
	}

	public bool IsAttributionPopupVisible()
	{
		return (bool)_object.Call(MethodName.IsAttributionPopupVisible);
	}

	public void UpdateCredits()
	{
		_object.Call(MethodName.UpdateCredits);
	}

	public static void TurnOn()
	{
		ClassDB.ClassCallStatic(NativeName, MethodName.TurnOn);
	}

	public static void TurnOff()
	{
		ClassDB.ClassCallStatic(NativeName, MethodName.TurnOff);
	}

	#endregion

	#region Signals

	public event Action<Godot.Collections.Array> CreditsChanged
	{
		add
		{
			_object.Connect(SignalName.CreditsChanged, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.CreditsChanged, Callable.From(value));
		}
	}

	public event Action<string> CreditLinkClicked
	{
		add
		{
			_object.Connect(SignalName.CreditLinkClicked, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.CreditLinkClicked, Callable.From(value));
		}
	}

	public event Action<string> CreditImageLoaded
	{
		add
		{
			_object.Connect(SignalName.CreditImageLoaded, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.CreditImageLoaded, Callable.From(value));
		}
	}

	public event Action<string, string> CreditImageFailed
	{
		add
		{
			_object.Connect(SignalName.CreditImageFailed, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.CreditImageFailed, Callable.From(value));
		}
	}

	public event Action<bool> PresenterEnabledChanged
	{
		add
		{
			_object.Connect(SignalName.PresenterEnabledChanged, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.PresenterEnabledChanged, Callable.From(value));
		}
	}

	#endregion
}
