// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumModelMetadata
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumModelMetadata() : this(NativeName)
	{
	}
	protected CesiumModelMetadata(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumModelMetadata(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumModelMetadata([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumModelMetadata self) => self?._object;
	public static implicit operator Variant(CesiumModelMetadata self) => self?._object;
	public static explicit operator CesiumModelMetadata(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Enums = "enums";
		public static readonly StringName PropertyTables = "property_tables";
		public static readonly StringName PropertyTextures = "property_textures";
		public static readonly StringName PropertyTextureBytes = "property_texture_bytes";
		public static readonly StringName RetainedMemoryBytes = "retained_memory_bytes";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetEnums = "get_enums";
		public static readonly StringName GetEnumCount = "get_enum_count";
		public static readonly StringName GetEnum = "get_enum";
		public static readonly StringName FindEnum = "find_enum";
		public static readonly StringName GetPropertyTables = "get_property_tables";
		public static readonly StringName GetPropertyTableCount = "get_property_table_count";
		public static readonly StringName GetPropertyTable = "get_property_table";
		public static readonly StringName GetPropertyTextures = "get_property_textures";
		public static readonly StringName GetPropertyTextureCount = "get_property_texture_count";
		public static readonly StringName GetPropertyTexture = "get_property_texture";
		public static readonly StringName GetPropertyTextureBytes = "get_property_texture_bytes";
		public static readonly StringName GetRetainedMemoryBytes = "get_retained_memory_bytes";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumModelMetadata";

	#region Properties

	public Godot.Collections.Array Enums
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.Enums);
	}

	public Godot.Collections.Array PropertyTables
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.PropertyTables);
	}

	public Godot.Collections.Array PropertyTextures
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.PropertyTextures);
	}

	public int PropertyTextureBytes
	{
		get => (int)_object.Get(PropertyName.PropertyTextureBytes);
	}

	public int RetainedMemoryBytes
	{
		get => (int)_object.Get(PropertyName.RetainedMemoryBytes);
	}

	#endregion

	#region Methods

	public Godot.Collections.Array GetEnums()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetEnums);
	}

	public int GetEnumCount()
	{
		return (int)_object.Call(MethodName.GetEnumCount);
	}

	public CesiumMetadataEnum GetEnum(int @index)
	{
		return (CesiumMetadataEnum)_object.Call(MethodName.GetEnum, @index);
	}

	public CesiumMetadataEnum FindEnum(string @enum_id)
	{
		return (CesiumMetadataEnum)_object.Call(MethodName.FindEnum, @enum_id);
	}

	public Godot.Collections.Array GetPropertyTables()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetPropertyTables);
	}

	public int GetPropertyTableCount()
	{
		return (int)_object.Call(MethodName.GetPropertyTableCount);
	}

	public CesiumPropertyTable GetPropertyTable(int @index)
	{
		return (CesiumPropertyTable)_object.Call(MethodName.GetPropertyTable, @index);
	}

	public Godot.Collections.Array GetPropertyTextures()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetPropertyTextures);
	}

	public int GetPropertyTextureCount()
	{
		return (int)_object.Call(MethodName.GetPropertyTextureCount);
	}

	public CesiumPropertyTexture GetPropertyTexture(int @index)
	{
		return (CesiumPropertyTexture)_object.Call(MethodName.GetPropertyTexture, @index);
	}

	public int GetPropertyTextureBytes()
	{
		return (int)_object.Call(MethodName.GetPropertyTextureBytes);
	}

	public int GetRetainedMemoryBytes()
	{
		return (int)_object.Call(MethodName.GetRetainedMemoryBytes);
	}

	#endregion
}
