// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumPropertyTexture
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumPropertyTexture() : this(NativeName)
	{
	}
	protected CesiumPropertyTexture(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumPropertyTexture(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumPropertyTexture([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumPropertyTexture self) => self?._object;
	public static implicit operator Variant(CesiumPropertyTexture self) => self?._object;
	public static explicit operator CesiumPropertyTexture(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Status = "status";
		public static readonly StringName StatusName = "status_name";
		public static readonly StringName TextureName = "texture_name";
		public static readonly StringName ClassName = "class_name";
		public static readonly StringName Properties = "properties";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetStatus = "get_status";
		public static readonly StringName GetStatusName = "get_status_name";
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName GetTextureName = "get_texture_name";
		public static readonly StringName GetClassName = "get_class_name";
		public static readonly StringName GetProperties = "get_properties";
		public static readonly StringName GetPropertyNames = "get_property_names";
		public static readonly StringName FindProperty = "find_property";
		public static readonly StringName GetMetadataValuesForUv = "get_metadata_values_for_uv";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumPropertyTexture";

	#region Enums

	public enum StatusEnum : long
	{
		Valid = 0L,
		ErrorInvalidPropertyTexture = 1L,
		ErrorInvalidPropertyTextureClass = 2L,
	}

	#endregion

	#region Properties

	public int Status
	{
		get => (int)_object.Get(PropertyName.Status);
	}

	public string StatusName
	{
		get => (string)_object.Get(PropertyName.StatusName);
	}

	public string TextureName
	{
		get => (string)_object.Get(PropertyName.TextureName);
	}

	public string ClassName
	{
		get => (string)_object.Get(PropertyName.ClassName);
	}

	public Godot.Collections.Array Properties
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.Properties);
	}

	#endregion

	#region Methods

	public int GetStatus()
	{
		return (int)_object.Call(MethodName.GetStatus);
	}

	public string GetStatusName()
	{
		return (string)_object.Call(MethodName.GetStatusName);
	}

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public string GetTextureName()
	{
		return (string)_object.Call(MethodName.GetTextureName);
	}

	public string GetClassName()
	{
		return (string)_object.Call(MethodName.GetClassName);
	}

	public Godot.Collections.Array GetProperties()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetProperties);
	}

	public Godot.Collections.Array GetPropertyNames()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetPropertyNames);
	}

	public CesiumPropertyTextureProperty FindProperty(string @property_id)
	{
		return (CesiumPropertyTextureProperty)_object.Call(MethodName.FindProperty, @property_id);
	}

	public Godot.Collections.Dictionary GetMetadataValuesForUv(Godot.Vector2 @texture_coordinates)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetMetadataValuesForUv, @texture_coordinates);
	}

	#endregion
}
