// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGeocoderAttribution
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public Resource NativeObject => _object;

	public CesiumGeocoderAttribution() : this(NativeName)
	{
	}
	protected CesiumGeocoderAttribution(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGeocoderAttribution(Variant variant) : this((Resource) variant)
	{
	}
	protected CesiumGeocoderAttribution([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(CesiumGeocoderAttribution self) => self?._object;
	public static implicit operator Variant(CesiumGeocoderAttribution self) => self?._object;
	public static explicit operator CesiumGeocoderAttribution(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName Html = "html";
		public static readonly StringName ShowOnScreen = "show_on_screen";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName GetHtml = "get_html";
		public static readonly StringName GetShowOnScreen = "get_show_on_screen";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumGeocoderAttribution";

	#region Properties

	public string Html
	{
		get => (string)_object.Get(PropertyName.Html);
	}

	public bool ShowOnScreen
	{
		get => (bool)_object.Get(PropertyName.ShowOnScreen);
	}

	#endregion

	#region Methods

	public string GetHtml()
	{
		return (string)_object.Call(MethodName.GetHtml);
	}

	public bool GetShowOnScreen()
	{
		return (bool)_object.Call(MethodName.GetShowOnScreen);
	}

	#endregion
}
