// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumRasterOverlay
{
	// Engine object used for calling engine methods
	protected Node3D _object;

	public Node3D NativeObject => _object;

	public CesiumRasterOverlay() : this(NativeName)
	{
	}
	protected CesiumRasterOverlay(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumRasterOverlay(Variant variant) : this((Node3D) variant)
	{
	}
	protected CesiumRasterOverlay([NotNull] Node3D @object)
	{
		_object = @object;
	}

	public static implicit operator Node3D(CesiumRasterOverlay self) => self?._object;
	public static implicit operator Variant(CesiumRasterOverlay self) => self?._object;
	public static explicit operator CesiumRasterOverlay(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node3D.PropertyName
	{
		public static readonly StringName Key = "key";
		public static readonly StringName MaximumScreenSpaceError = "maximum_screen_space_error";
		public static readonly StringName MaximumTextureSize = "maximum_texture_size";
		public static readonly StringName MaximumSimultaneousTileLoads = "maximum_simultaneous_tile_loads";
		public static readonly StringName SubTileCacheBytes = "sub_tile_cache_bytes";
		public static readonly StringName ShowCreditsOnScreen = "show_credits_on_screen";
		public static readonly StringName GenerateMipmaps = "generate_mipmaps";
	}

	public class MethodName : Node3D.MethodName
	{
		public static readonly StringName SetMaterialKey = "set_material_key";
		public static readonly StringName GetMaterialKey = "get_material_key";
		public static readonly StringName SetMaximumScreenSpaceError = "set_maximum_screen_space_error";
		public static readonly StringName GetMaximumScreenSpaceError = "get_maximum_screen_space_error";
		public static readonly StringName SetMaximumTextureSize = "set_maximum_texture_size";
		public static readonly StringName GetMaximumTextureSize = "get_maximum_texture_size";
		public static readonly StringName SetMaximumSimultaneousTileLoads = "set_maximum_simultaneous_tile_loads";
		public static readonly StringName GetMaximumSimultaneousTileLoads = "get_maximum_simultaneous_tile_loads";
		public static readonly StringName SetSubTileCacheBytes = "set_sub_tile_cache_bytes";
		public static readonly StringName GetSubTileCacheBytes = "get_sub_tile_cache_bytes";
		public static readonly StringName SetShowCreditsOnScreen = "set_show_credits_on_screen";
		public static readonly StringName GetShowCreditsOnScreen = "get_show_credits_on_screen";
		public static readonly StringName SetGenerateMipmaps = "set_generate_mipmaps";
		public static readonly StringName GetGenerateMipmaps = "get_generate_mipmaps";
		public static readonly StringName AddToTileset = "add_to_tileset";
		public static readonly StringName RemoveFromTileset = "remove_from_tileset";
		public static readonly StringName Refresh = "refresh";
		public static readonly StringName IsAddedToTileset = "is_added_to_tileset";
		public static readonly StringName GetProviderType = "get_provider_type";
		public static readonly StringName GetConfiguration = "get_configuration";
	}

	public class SignalName : Node3D.SignalName
	{
		public static readonly StringName LoadFailure = "load_failure";
	}

	private static readonly StringName NativeName = "CesiumRasterOverlay";

	#region Properties

	public string Key
	{
		get => (string)_object.Get(PropertyName.Key);
		set => _object.Set(PropertyName.Key, value);
	}

	public float MaximumScreenSpaceError
	{
		get => (float)_object.Get(PropertyName.MaximumScreenSpaceError);
		set => _object.Set(PropertyName.MaximumScreenSpaceError, value);
	}

	public int MaximumTextureSize
	{
		get => (int)_object.Get(PropertyName.MaximumTextureSize);
		set => _object.Set(PropertyName.MaximumTextureSize, value);
	}

	public int MaximumSimultaneousTileLoads
	{
		get => (int)_object.Get(PropertyName.MaximumSimultaneousTileLoads);
		set => _object.Set(PropertyName.MaximumSimultaneousTileLoads, value);
	}

	public int SubTileCacheBytes
	{
		get => (int)_object.Get(PropertyName.SubTileCacheBytes);
		set => _object.Set(PropertyName.SubTileCacheBytes, value);
	}

	public bool ShowCreditsOnScreen
	{
		get => (bool)_object.Get(PropertyName.ShowCreditsOnScreen);
		set => _object.Set(PropertyName.ShowCreditsOnScreen, value);
	}

	public bool GenerateMipmaps
	{
		get => (bool)_object.Get(PropertyName.GenerateMipmaps);
		set => _object.Set(PropertyName.GenerateMipmaps, value);
	}

	#endregion

	#region Methods

	public void SetMaterialKey(string @key)
	{
		_object.Call(MethodName.SetMaterialKey, @key);
	}

	public string GetMaterialKey()
	{
		return (string)_object.Call(MethodName.GetMaterialKey);
	}

	public void SetMaximumScreenSpaceError(float @value)
	{
		_object.Call(MethodName.SetMaximumScreenSpaceError, @value);
	}

	public float GetMaximumScreenSpaceError()
	{
		return (float)_object.Call(MethodName.GetMaximumScreenSpaceError);
	}

	public void SetMaximumTextureSize(int @value)
	{
		_object.Call(MethodName.SetMaximumTextureSize, @value);
	}

	public int GetMaximumTextureSize()
	{
		return (int)_object.Call(MethodName.GetMaximumTextureSize);
	}

	public void SetMaximumSimultaneousTileLoads(int @value)
	{
		_object.Call(MethodName.SetMaximumSimultaneousTileLoads, @value);
	}

	public int GetMaximumSimultaneousTileLoads()
	{
		return (int)_object.Call(MethodName.GetMaximumSimultaneousTileLoads);
	}

	public void SetSubTileCacheBytes(int @value)
	{
		_object.Call(MethodName.SetSubTileCacheBytes, @value);
	}

	public int GetSubTileCacheBytes()
	{
		return (int)_object.Call(MethodName.GetSubTileCacheBytes);
	}

	public void SetShowCreditsOnScreen(bool @value)
	{
		_object.Call(MethodName.SetShowCreditsOnScreen, @value);
	}

	public bool GetShowCreditsOnScreen()
	{
		return (bool)_object.Call(MethodName.GetShowCreditsOnScreen);
	}

	public void SetGenerateMipmaps(bool @value)
	{
		_object.Call(MethodName.SetGenerateMipmaps, @value);
	}

	public bool GetGenerateMipmaps()
	{
		return (bool)_object.Call(MethodName.GetGenerateMipmaps);
	}

	public Godot.Error AddToTileset(Cesium3DTileset @tileset)
	{
		return (Godot.Error)(int)_object.Call(MethodName.AddToTileset, @tileset);
	}

	public void RemoveFromTileset(Cesium3DTileset @tileset = default)
	{
		_object.Call(MethodName.RemoveFromTileset, @tileset);
	}

	public void Refresh()
	{
		_object.Call(MethodName.Refresh);
	}

	public bool IsAddedToTileset()
	{
		return (bool)_object.Call(MethodName.IsAddedToTileset);
	}

	public string GetProviderType()
	{
		return (string)_object.Call(MethodName.GetProviderType);
	}

	public Godot.Collections.Dictionary GetConfiguration()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetConfiguration);
	}

	#endregion

	#region Signals

	public event Action<GodotObject> LoadFailure
	{
		add
		{
			_object.Connect(SignalName.LoadFailure, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.LoadFailure, Callable.From(value));
		}
	}

	#endregion
}
