// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class DocumentContainer
{
	// Engine object used for calling engine methods
	protected Control _object;

	public Control NativeObject => _object;

	public DocumentContainer() : this(NativeName)
	{
	}
	protected DocumentContainer(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected DocumentContainer(Variant variant) : this((Control) variant)
	{
	}
	protected DocumentContainer([NotNull] Control @object)
	{
		_object = @object;
	}

	public static implicit operator Control(DocumentContainer self) => self?._object;
	public static implicit operator Variant(DocumentContainer self) => self?._object;
	public static explicit operator DocumentContainer(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Control.PropertyName
	{

	}

	public class MethodName : Control.MethodName
	{
		public static readonly StringName SetHtml = "set_html";
	}

	public class SignalName : Control.SignalName
	{

	}

	private static readonly StringName NativeName = "DocumentContainer";

	#region Methods

	public void SetHtml(string @html)
	{
		_object.Call(MethodName.SetHtml, @html);
	}

	#endregion
}
