// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class GeoreferencedMesh
{
	// Engine object used for calling engine methods
	protected MeshInstance3D _object;

	public MeshInstance3D NativeObject => _object;

	public GeoreferencedMesh() : this(NativeName)
	{
	}
	protected GeoreferencedMesh(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected GeoreferencedMesh(Variant variant) : this((MeshInstance3D) variant)
	{
	}
	protected GeoreferencedMesh([NotNull] MeshInstance3D @object)
	{
		_object = @object;
	}

	public static implicit operator MeshInstance3D(GeoreferencedMesh self) => self?._object;
	public static implicit operator Variant(GeoreferencedMesh self) => self?._object;
	public static explicit operator GeoreferencedMesh(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : MeshInstance3D.PropertyName
	{
		public static readonly StringName Tileset = "tileset";
	}

	public class MethodName : MeshInstance3D.MethodName
	{
		public static readonly StringName GetEnginePosition = "get_engine_position";
		public static readonly StringName SetEnginePosition = "set_engine_position";
		public static readonly StringName GetEcefPosition = "get_ecef_position";
		public static readonly StringName SetEcefPosition = "set_ecef_position";
		public static readonly StringName SetTileset = "set_tileset";
		public static readonly StringName GetTileset = "get_tileset";
		public static readonly StringName GetGeoreference = "get_georeference";
	}

	public class SignalName : MeshInstance3D.SignalName
	{

	}

	private static readonly StringName NativeName = "GeoreferencedMesh";

	#region Properties

	public GodotObject Tileset
	{
		get => (GodotObject)_object.Get(PropertyName.Tileset);
		set => _object.Set(PropertyName.Tileset, value);
	}

	#endregion

	#region Methods

	public Godot.Vector3 GetEnginePosition()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetEnginePosition);
	}

	public void SetEnginePosition(Godot.Vector3 @position)
	{
		_object.Call(MethodName.SetEnginePosition, @position);
	}

	public Godot.Vector3 GetEcefPosition()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetEcefPosition);
	}

	public void SetEcefPosition(Godot.Vector3 @position)
	{
		_object.Call(MethodName.SetEcefPosition, @position);
	}

	public void SetTileset(Cesium3DTileset @tileset)
	{
		_object.Call(MethodName.SetTileset, @tileset);
	}

	public Cesium3DTileset GetTileset()
	{
		return (Cesium3DTileset)_object.Call(MethodName.GetTileset);
	}

	public CesiumGeoreference GetGeoreference()
	{
		return (CesiumGeoreference)_object.Call(MethodName.GetGeoreference);
	}

	#endregion
}
