// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class TokenTroubleshooting
{
	// Engine object used for calling engine methods
	protected Node _object;

	public Node NativeObject => _object;

	public TokenTroubleshooting() : this(NativeName)
	{
	}
	protected TokenTroubleshooting(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected TokenTroubleshooting(Variant variant) : this((Node) variant)
	{
	}
	protected TokenTroubleshooting([NotNull] Node @object)
	{
		_object = @object;
	}

	public static implicit operator Node(TokenTroubleshooting self) => self?._object;
	public static implicit operator Variant(TokenTroubleshooting self) => self?._object;
	public static explicit operator TokenTroubleshooting(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node.PropertyName
	{

	}

	public class MethodName : Node.MethodName
	{
		public static readonly StringName IsValidToken = "is_valid_token";
		public static readonly StringName SetData = "set_data";
		public static readonly StringName GetAssetIdByName = "get_asset_id_by_name";
	}

	public class SignalName : Node.SignalName
	{

	}

	private static readonly StringName NativeName = "TokenTroubleshooting";

	#region Methods

	public void IsValidToken(string @token)
	{
		_object.Call(MethodName.IsValidToken, @token);
	}

	public void SetData(Variant @data)
	{
		_object.Call(MethodName.SetData, @data);
	}

	public int GetAssetIdByName(string @_unnamed_arg0)
	{
		return (int)_object.Call(MethodName.GetAssetIdByName, @_unnamed_arg0);
	}

	#endregion
}
