// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumBoundingVolume
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumBoundingVolume() : this(NativeName)
	{
	}
	protected CesiumBoundingVolume(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumBoundingVolume(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumBoundingVolume([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumBoundingVolume self) => self?._object;
	public static implicit operator Variant(CesiumBoundingVolume self) => self?._object;
	public static explicit operator CesiumBoundingVolume(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName VolumeType = "volume_type";
		public static readonly StringName VolumeTypeName = "volume_type_name";
		public static readonly StringName Center = "center";
		public static readonly StringName CenterComponents = "center_components";
		public static readonly StringName OrientedBoxTransform = "oriented_box_transform";
		public static readonly StringName OrientedBoxHalfAxes = "oriented_box_half_axes";
		public static readonly StringName OrientedBoxSize = "oriented_box_size";
		public static readonly StringName SourceAabb = "source_aabb";
		public static readonly StringName Details = "details";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName GetVolumeType = "get_volume_type";
		public static readonly StringName GetVolumeTypeName = "get_volume_type_name";
		public static readonly StringName GetCenter = "get_center";
		public static readonly StringName GetCenterComponents = "get_center_components";
		public static readonly StringName GetOrientedBoxTransform = "get_oriented_box_transform";
		public static readonly StringName GetOrientedBoxHalfAxes = "get_oriented_box_half_axes";
		public static readonly StringName GetOrientedBoxSize = "get_oriented_box_size";
		public static readonly StringName GetSourceAabb = "get_source_aabb";
		public static readonly StringName GetTransformedAabb = "get_transformed_aabb";
		public static readonly StringName GetDetails = "get_details";
		public static readonly StringName CreateOwnedCopy = "create_owned_copy";
		public static readonly StringName ContainsSourcePosition = "contains_source_position";
		public static readonly StringName ContainsSourcePositionComponents = "contains_source_position_components";
		public static readonly StringName DistanceToSourcePosition = "distance_to_source_position";
		public static readonly StringName DistanceToSourcePositionComponents = "distance_to_source_position_components";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumBoundingVolume";

	#region Enums

	public enum Type : long
	{
		Invalid = 0L,
		Sphere = 1L,
		OrientedBox = 2L,
		Region = 3L,
		RegionWithLooseFittingHeights = 4L,
		S2Cell = 5L,
		CylinderRegion = 6L,
	}

	#endregion

	#region Properties

	public int VolumeType
	{
		get => (int)_object.Get(PropertyName.VolumeType);
	}

	public string VolumeTypeName
	{
		get => (string)_object.Get(PropertyName.VolumeTypeName);
	}

	public Godot.Vector3 Center
	{
		get => (Godot.Vector3)_object.Get(PropertyName.Center);
	}

	public double[] CenterComponents
	{
		get => (double[])_object.Get(PropertyName.CenterComponents);
	}

	public Godot.Transform3D OrientedBoxTransform
	{
		get => (Godot.Transform3D)_object.Get(PropertyName.OrientedBoxTransform);
	}

	public double[] OrientedBoxHalfAxes
	{
		get => (double[])_object.Get(PropertyName.OrientedBoxHalfAxes);
	}

	public Godot.Vector3 OrientedBoxSize
	{
		get => (Godot.Vector3)_object.Get(PropertyName.OrientedBoxSize);
	}

	public Godot.Aabb SourceAabb
	{
		get => (Godot.Aabb)_object.Get(PropertyName.SourceAabb);
	}

	public Godot.Collections.Dictionary Details
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.Details);
	}

	#endregion

	#region Methods

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public int GetVolumeType()
	{
		return (int)_object.Call(MethodName.GetVolumeType);
	}

	public string GetVolumeTypeName()
	{
		return (string)_object.Call(MethodName.GetVolumeTypeName);
	}

	public Godot.Vector3 GetCenter()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetCenter);
	}

	public double[] GetCenterComponents()
	{
		return (double[])_object.Call(MethodName.GetCenterComponents);
	}

	public Godot.Transform3D GetOrientedBoxTransform()
	{
		return (Godot.Transform3D)_object.Call(MethodName.GetOrientedBoxTransform);
	}

	public double[] GetOrientedBoxHalfAxes()
	{
		return (double[])_object.Call(MethodName.GetOrientedBoxHalfAxes);
	}

	public Godot.Vector3 GetOrientedBoxSize()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetOrientedBoxSize);
	}

	public Godot.Aabb GetSourceAabb()
	{
		return (Godot.Aabb)_object.Call(MethodName.GetSourceAabb);
	}

	public Godot.Aabb GetTransformedAabb(Godot.Transform3D @source_to_target)
	{
		return (Godot.Aabb)_object.Call(MethodName.GetTransformedAabb, @source_to_target);
	}

	public Godot.Collections.Dictionary GetDetails()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetDetails);
	}

	public CesiumBoundingVolume CreateOwnedCopy()
	{
		return (CesiumBoundingVolume)_object.Call(MethodName.CreateOwnedCopy);
	}

	public bool ContainsSourcePosition(Godot.Vector3 @position)
	{
		return (bool)_object.Call(MethodName.ContainsSourcePosition, @position);
	}

	public bool ContainsSourcePositionComponents(double[] @position)
	{
		return (bool)_object.Call(MethodName.ContainsSourcePositionComponents, @position);
	}

	public float DistanceToSourcePosition(Godot.Vector3 @position)
	{
		return (float)_object.Call(MethodName.DistanceToSourcePosition, @position);
	}

	public float DistanceToSourcePositionComponents(double[] @position)
	{
		return (float)_object.Call(MethodName.DistanceToSourcePositionComponents, @position);
	}

	#endregion
}
