// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class Cesium3DTileset
{
	// Engine object used for calling engine methods
	protected Node3D _object;

	public Node3D NativeObject => _object;

	public Cesium3DTileset() : this(NativeName)
	{
	}
	protected Cesium3DTileset(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected Cesium3DTileset(Variant variant) : this((Node3D) variant)
	{
	}
	protected Cesium3DTileset([NotNull] Node3D @object)
	{
		_object = @object;
	}

	public static implicit operator Node3D(Cesium3DTileset self) => self?._object;
	public static implicit operator Variant(Cesium3DTileset self) => self?._object;
	public static explicit operator Cesium3DTileset(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node3D.PropertyName
	{
		public static readonly StringName MaximumScreenSpaceError = "maximum_screen_space_error";
		public static readonly StringName MaximumSimultaneousTileLoads = "maximum_simultaneous_tile_loads";
		public static readonly StringName StaleRequestCancellationEnabled = "stale_request_cancellation_enabled";
		public static readonly StringName PreloadAncestors = "preload_ancestors";
		public static readonly StringName PreloadSiblings = "preload_siblings";
		public static readonly StringName LoadingDescendantLimit = "loading_descendant_limit";
		public static readonly StringName ForbidHoles = "forbid_holes";
		public static readonly StringName FrustumCullingEnabled = "frustum_culling_enabled";
		public static readonly StringName OcclusionCullingEnabled = "occlusion_culling_enabled";
		public static readonly StringName OcclusionPoolSize = "occlusion_pool_size";
		public static readonly StringName DelayRefinementForOcclusion = "delay_refinement_for_occlusion";
		public static readonly StringName FogCullingEnabled = "fog_culling_enabled";
		public static readonly StringName EnforceCulledScreenSpaceError = "enforce_culled_screen_space_error";
		public static readonly StringName CulledScreenSpaceError = "culled_screen_space_error";
		public static readonly StringName RenderTilesUnderCamera = "render_tiles_under_camera";
		public static readonly StringName LodTransitionsEnabled = "lod_transitions_enabled";
		public static readonly StringName LodTransitionLength = "lod_transition_length";
		public static readonly StringName KickDescendantsWhileFadingIn = "kick_descendants_while_fading_in";
		public static readonly StringName TranslucencySortPriority = "translucency_sort_priority";
		public static readonly StringName TranslucencyDepthPrepassEnabled = "translucency_depth_prepass_enabled";
		public static readonly StringName MaximumCachedBytes = "maximum_cached_bytes";
		public static readonly StringName AutomaticHardwareBudgetsEnabled = "automatic_hardware_budgets_enabled";
		public static readonly StringName HardwareBudgetProfile = "hardware_budget_profile";
		public static readonly StringName AutomaticCacheBudgetShare = "automatic_cache_budget_share";
		public static readonly StringName WorkerThreadCount = "worker_thread_count";
		public static readonly StringName MainThreadLoadingTimeLimitMs = "main_thread_loading_time_limit_ms";
		public static readonly StringName MaximumPrimitiveGeometryUploadBytes = "maximum_primitive_geometry_upload_bytes";
		public static readonly StringName MaximumPrimitiveTextureUploadBytes = "maximum_primitive_texture_upload_bytes";
		public static readonly StringName TileCacheUnloadTimeLimitMs = "tile_cache_unload_time_limit_ms";
		public static readonly StringName HttpCacheEnabled = "http_cache_enabled";
		public static readonly StringName HttpCachePath = "http_cache_path";
		public static readonly StringName HttpCacheMaximumItems = "http_cache_maximum_items";
		public static readonly StringName HttpCacheMaximumDataBytes = "http_cache_maximum_data_bytes";
		public static readonly StringName HttpCachePruneIntervalRequests = "http_cache_prune_interval_requests";
		public static readonly StringName MaximumNetworkRetries = "maximum_network_retries";
		public static readonly StringName NetworkRetryInitialDelaySeconds = "network_retry_initial_delay_seconds";
		public static readonly StringName NetworkRetryMaximumDelaySeconds = "network_retry_maximum_delay_seconds";
		public static readonly StringName MovementPredictionEnabled = "movement_prediction_enabled";
		public static readonly StringName MovementPredictionSeconds = "movement_prediction_seconds";
		public static readonly StringName MovementPredictionMinimumSpeed = "movement_prediction_minimum_speed";
		public static readonly StringName MovementPredictionMaximumDistance = "movement_prediction_maximum_distance";
		public static readonly StringName MovementPredictionWeight = "movement_prediction_weight";
		public static readonly StringName TurnPredictionEnabled = "turn_prediction_enabled";
		public static readonly StringName TurnPredictionMinimumAngularSpeedDegrees = "turn_prediction_minimum_angular_speed_degrees";
		public static readonly StringName TurnPredictionMaximumAngleDegrees = "turn_prediction_maximum_angle_degrees";
		public static readonly StringName ZoomOutPredictionEnabled = "zoom_out_prediction_enabled";
		public static readonly StringName ZoomOutPredictionMinimumRate = "zoom_out_prediction_minimum_rate";
		public static readonly StringName ZoomOutPredictionMaximumScale = "zoom_out_prediction_maximum_scale";
		public static readonly StringName GenerateMissingNormalsSmooth = "generate_missing_normals_smooth";
		public static readonly StringName CreatePhysicsMeshes = "create_physics_meshes";
		public static readonly StringName CameraManagerPath = "camera_manager_path";
		public static readonly StringName Credit = "credit";
		public static readonly StringName CreditSystem = "credit_system";
		public static readonly StringName ResolvedCreditSystem = "resolved_credit_system";
		public static readonly StringName ShowCreditsOnScreen = "show_credits_on_screen";
		public static readonly StringName DebugTileStateCaptureEnabled = "debug_tile_state_capture_enabled";
		public static readonly StringName DebugTileStateLimit = "debug_tile_state_limit";
		public static readonly StringName DebugTileStates = "debug_tile_states";
		public static readonly StringName DebugTileStateFrameNumber = "debug_tile_state_frame_number";
		public static readonly StringName DebugTileStatesTruncated = "debug_tile_states_truncated";
		public static readonly StringName LifecycleEventReceiver = "lifecycle_event_receiver";
		public static readonly StringName MetadataStyle = "metadata_style";
		public static readonly StringName PointCloudShading = "point_cloud_shading";
		public static readonly StringName DataSource = "data_source";
		public static readonly StringName Url = "url";
		public static readonly StringName RequestHeaders = "request_headers";
		public static readonly StringName IonAssetId = "ion_asset_id";
		public static readonly StringName ShowHierarchy = "show_hierarchy";
		public static readonly StringName TilesetBounds = "tileset_bounds";
	}

	public class MethodName : Node3D.MethodName
	{
		public static readonly StringName SetMaximumScreenSpaceError = "set_maximum_screen_space_error";
		public static readonly StringName GetMaximumScreenSpaceError = "get_maximum_screen_space_error";
		public static readonly StringName SetMaximumSimultaneousTileLoads = "set_maximum_simultaneous_tile_loads";
		public static readonly StringName GetMaximumSimultaneousTileLoads = "get_maximum_simultaneous_tile_loads";
		public static readonly StringName SetStaleRequestCancellationEnabled = "set_stale_request_cancellation_enabled";
		public static readonly StringName GetStaleRequestCancellationEnabled = "get_stale_request_cancellation_enabled";
		public static readonly StringName SetPreloadAncestors = "set_preload_ancestors";
		public static readonly StringName GetPreloadAncestors = "get_preload_ancestors";
		public static readonly StringName SetPreloadSiblings = "set_preload_siblings";
		public static readonly StringName GetPreloadSiblings = "get_preload_siblings";
		public static readonly StringName SetLoadingDescendantLimit = "set_loading_descendant_limit";
		public static readonly StringName GetLoadingDescendantLimit = "get_loading_descendant_limit";
		public static readonly StringName SetForbidHoles = "set_forbid_holes";
		public static readonly StringName GetForbidHoles = "get_forbid_holes";
		public static readonly StringName SetFrustumCullingEnabled = "set_frustum_culling_enabled";
		public static readonly StringName GetFrustumCullingEnabled = "get_frustum_culling_enabled";
		public static readonly StringName SetOcclusionCullingEnabled = "set_occlusion_culling_enabled";
		public static readonly StringName GetOcclusionCullingEnabled = "get_occlusion_culling_enabled";
		public static readonly StringName SetOcclusionPoolSize = "set_occlusion_pool_size";
		public static readonly StringName GetOcclusionPoolSize = "get_occlusion_pool_size";
		public static readonly StringName SetDelayRefinementForOcclusion = "set_delay_refinement_for_occlusion";
		public static readonly StringName GetDelayRefinementForOcclusion = "get_delay_refinement_for_occlusion";
		public static readonly StringName SetFogCullingEnabled = "set_fog_culling_enabled";
		public static readonly StringName GetFogCullingEnabled = "get_fog_culling_enabled";
		public static readonly StringName SetEnforceCulledScreenSpaceError = "set_enforce_culled_screen_space_error";
		public static readonly StringName GetEnforceCulledScreenSpaceError = "get_enforce_culled_screen_space_error";
		public static readonly StringName SetCulledScreenSpaceError = "set_culled_screen_space_error";
		public static readonly StringName GetCulledScreenSpaceError = "get_culled_screen_space_error";
		public static readonly StringName SetRenderTilesUnderCamera = "set_render_tiles_under_camera";
		public static readonly StringName GetRenderTilesUnderCamera = "get_render_tiles_under_camera";
		public static readonly StringName SetLodTransitionsEnabled = "set_lod_transitions_enabled";
		public static readonly StringName GetLodTransitionsEnabled = "get_lod_transitions_enabled";
		public static readonly StringName SetLodTransitionLength = "set_lod_transition_length";
		public static readonly StringName GetLodTransitionLength = "get_lod_transition_length";
		public static readonly StringName SetKickDescendantsWhileFadingIn = "set_kick_descendants_while_fading_in";
		public static readonly StringName GetKickDescendantsWhileFadingIn = "get_kick_descendants_while_fading_in";
		public static readonly StringName SetTranslucencySortPriority = "set_translucency_sort_priority";
		public static readonly StringName GetTranslucencySortPriority = "get_translucency_sort_priority";
		public static readonly StringName SetTranslucencyDepthPrepassEnabled = "set_translucency_depth_prepass_enabled";
		public static readonly StringName GetTranslucencyDepthPrepassEnabled = "get_translucency_depth_prepass_enabled";
		public static readonly StringName SetMaximumCachedBytes = "set_maximum_cached_bytes";
		public static readonly StringName GetMaximumCachedBytes = "get_maximum_cached_bytes";
		public static readonly StringName SetAutomaticHardwareBudgetsEnabled = "set_automatic_hardware_budgets_enabled";
		public static readonly StringName GetAutomaticHardwareBudgetsEnabled = "get_automatic_hardware_budgets_enabled";
		public static readonly StringName SetHardwareBudgetProfile = "set_hardware_budget_profile";
		public static readonly StringName GetHardwareBudgetProfile = "get_hardware_budget_profile";
		public static readonly StringName SetAutomaticCacheBudgetShare = "set_automatic_cache_budget_share";
		public static readonly StringName GetAutomaticCacheBudgetShare = "get_automatic_cache_budget_share";
		public static readonly StringName RecalculateAutomaticHardwareBudgets = "recalculate_automatic_hardware_budgets";
		public static readonly StringName GetHardwareCapabilities = "get_hardware_capabilities";
		public static readonly StringName GetRecommendedTotalCacheBytes = "get_recommended_total_cache_bytes";
		public static readonly StringName SetWorkerThreadCount = "set_worker_thread_count";
		public static readonly StringName GetWorkerThreadCount = "get_worker_thread_count";
		public static readonly StringName ResetWorkerThreadCountToAutomatic = "reset_worker_thread_count_to_automatic";
		public static readonly StringName SetMainThreadLoadingTimeLimitMs = "set_main_thread_loading_time_limit_ms";
		public static readonly StringName GetMainThreadLoadingTimeLimitMs = "get_main_thread_loading_time_limit_ms";
		public static readonly StringName SetMaximumPrimitiveGeometryUploadBytes = "set_maximum_primitive_geometry_upload_bytes";
		public static readonly StringName GetMaximumPrimitiveGeometryUploadBytes = "get_maximum_primitive_geometry_upload_bytes";
		public static readonly StringName SetMaximumPrimitiveTextureUploadBytes = "set_maximum_primitive_texture_upload_bytes";
		public static readonly StringName GetMaximumPrimitiveTextureUploadBytes = "get_maximum_primitive_texture_upload_bytes";
		public static readonly StringName SetTileCacheUnloadTimeLimitMs = "set_tile_cache_unload_time_limit_ms";
		public static readonly StringName GetTileCacheUnloadTimeLimitMs = "get_tile_cache_unload_time_limit_ms";
		public static readonly StringName SetHttpCacheEnabled = "set_http_cache_enabled";
		public static readonly StringName GetHttpCacheEnabled = "get_http_cache_enabled";
		public static readonly StringName SetHttpCachePath = "set_http_cache_path";
		public static readonly StringName GetHttpCachePath = "get_http_cache_path";
		public static readonly StringName GetResolvedHttpCachePath = "get_resolved_http_cache_path";
		public static readonly StringName SetHttpCacheMaximumItems = "set_http_cache_maximum_items";
		public static readonly StringName GetHttpCacheMaximumItems = "get_http_cache_maximum_items";
		public static readonly StringName SetHttpCacheMaximumDataBytes = "set_http_cache_maximum_data_bytes";
		public static readonly StringName GetHttpCacheMaximumDataBytes = "get_http_cache_maximum_data_bytes";
		public static readonly StringName SetHttpCachePruneIntervalRequests = "set_http_cache_prune_interval_requests";
		public static readonly StringName GetHttpCachePruneIntervalRequests = "get_http_cache_prune_interval_requests";
		public static readonly StringName ClearHttpCache = "clear_http_cache";
		public static readonly StringName PruneHttpCache = "prune_http_cache";
		public static readonly StringName SetMaximumNetworkRetries = "set_maximum_network_retries";
		public static readonly StringName GetMaximumNetworkRetries = "get_maximum_network_retries";
		public static readonly StringName SetNetworkRetryInitialDelaySeconds = "set_network_retry_initial_delay_seconds";
		public static readonly StringName GetNetworkRetryInitialDelaySeconds = "get_network_retry_initial_delay_seconds";
		public static readonly StringName SetNetworkRetryMaximumDelaySeconds = "set_network_retry_maximum_delay_seconds";
		public static readonly StringName GetNetworkRetryMaximumDelaySeconds = "get_network_retry_maximum_delay_seconds";
		public static readonly StringName SetMovementPredictionEnabled = "set_movement_prediction_enabled";
		public static readonly StringName GetMovementPredictionEnabled = "get_movement_prediction_enabled";
		public static readonly StringName SetMovementPredictionSeconds = "set_movement_prediction_seconds";
		public static readonly StringName GetMovementPredictionSeconds = "get_movement_prediction_seconds";
		public static readonly StringName SetMovementPredictionMinimumSpeed = "set_movement_prediction_minimum_speed";
		public static readonly StringName GetMovementPredictionMinimumSpeed = "get_movement_prediction_minimum_speed";
		public static readonly StringName SetMovementPredictionMaximumDistance = "set_movement_prediction_maximum_distance";
		public static readonly StringName GetMovementPredictionMaximumDistance = "get_movement_prediction_maximum_distance";
		public static readonly StringName SetMovementPredictionWeight = "set_movement_prediction_weight";
		public static readonly StringName GetMovementPredictionWeight = "get_movement_prediction_weight";
		public static readonly StringName SetTurnPredictionEnabled = "set_turn_prediction_enabled";
		public static readonly StringName GetTurnPredictionEnabled = "get_turn_prediction_enabled";
		public static readonly StringName SetTurnPredictionMinimumAngularSpeedDegrees = "set_turn_prediction_minimum_angular_speed_degrees";
		public static readonly StringName GetTurnPredictionMinimumAngularSpeedDegrees = "get_turn_prediction_minimum_angular_speed_degrees";
		public static readonly StringName SetTurnPredictionMaximumAngleDegrees = "set_turn_prediction_maximum_angle_degrees";
		public static readonly StringName GetTurnPredictionMaximumAngleDegrees = "get_turn_prediction_maximum_angle_degrees";
		public static readonly StringName SetZoomOutPredictionEnabled = "set_zoom_out_prediction_enabled";
		public static readonly StringName GetZoomOutPredictionEnabled = "get_zoom_out_prediction_enabled";
		public static readonly StringName SetZoomOutPredictionMinimumRate = "set_zoom_out_prediction_minimum_rate";
		public static readonly StringName GetZoomOutPredictionMinimumRate = "get_zoom_out_prediction_minimum_rate";
		public static readonly StringName SetZoomOutPredictionMaximumScale = "set_zoom_out_prediction_maximum_scale";
		public static readonly StringName GetZoomOutPredictionMaximumScale = "get_zoom_out_prediction_maximum_scale";
		public static readonly StringName SetGenerateMissingNormalsSmooth = "set_generate_missing_normals_smooth";
		public static readonly StringName GetGenerateMissingNormalsSmooth = "get_generate_missing_normals_smooth";
		public static readonly StringName SetCreatePhysicsMeshes = "set_create_physics_meshes";
		public static readonly StringName GetCreatePhysicsMeshes = "get_create_physics_meshes";
		public static readonly StringName SetCameraManagerPath = "set_camera_manager_path";
		public static readonly StringName GetCameraManagerPath = "get_camera_manager_path";
		public static readonly StringName SetCredit = "set_credit";
		public static readonly StringName GetCredit = "get_credit";
		public static readonly StringName SetCreditSystem = "set_credit_system";
		public static readonly StringName GetCreditSystem = "get_credit_system";
		public static readonly StringName ResolveCreditSystem = "resolve_credit_system";
		public static readonly StringName GetResolvedCreditSystem = "get_resolved_credit_system";
		public static readonly StringName InvalidateResolvedCreditSystem = "invalidate_resolved_credit_system";
		public static readonly StringName SetShowCreditsOnScreen = "set_show_credits_on_screen";
		public static readonly StringName GetShowCreditsOnScreen = "get_show_credits_on_screen";
		public static readonly StringName SetLifecycleEventReceiver = "set_lifecycle_event_receiver";
		public static readonly StringName GetLifecycleEventReceiver = "get_lifecycle_event_receiver";
		public static readonly StringName SetMetadataStyle = "set_metadata_style";
		public static readonly StringName GetMetadataStyle = "get_metadata_style";
		public static readonly StringName RefreshMetadataStyle = "refresh_metadata_style";
		public static readonly StringName SetPointCloudShading = "set_point_cloud_shading";
		public static readonly StringName GetPointCloudShading = "get_point_cloud_shading";
		public static readonly StringName RefreshPointCloudShading = "refresh_point_cloud_shading";
		public static readonly StringName HasActiveTileset = "has_active_tileset";
		public static readonly StringName GetTilesetBounds = "get_tileset_bounds";
		public static readonly StringName GetTilesetSourceAabb = "get_tileset_source_aabb";
		public static readonly StringName SampleHeightMostDetailed = "sample_height_most_detailed";
		public static readonly StringName SampleHeightMostDetailedExact = "sample_height_most_detailed_exact";
		public static readonly StringName GetStreamingStatistics = "get_streaming_statistics";
		public static readonly StringName SetDebugTileStateCaptureEnabled = "set_debug_tile_state_capture_enabled";
		public static readonly StringName GetDebugTileStateCaptureEnabled = "get_debug_tile_state_capture_enabled";
		public static readonly StringName SetDebugTileStateLimit = "set_debug_tile_state_limit";
		public static readonly StringName GetDebugTileStateLimit = "get_debug_tile_state_limit";
		public static readonly StringName GetDebugTileStates = "get_debug_tile_states";
		public static readonly StringName GetDebugTileStateFrameNumber = "get_debug_tile_state_frame_number";
		public static readonly StringName GetDebugTileStatesTruncated = "get_debug_tile_states_truncated";
		public static readonly StringName AttachRasterOverlay = "attach_raster_overlay";
		public static readonly StringName DetachRasterOverlay = "detach_raster_overlay";
		public static readonly StringName GetDataSource = "get_data_source";
		public static readonly StringName SetDataSource = "set_data_source";
		public static readonly StringName SetUrl = "set_url";
		public static readonly StringName GetUrl = "get_url";
		public static readonly StringName SetRequestHeaders = "set_request_headers";
		public static readonly StringName GetRequestHeaders = "get_request_headers";
		public static readonly StringName SetIonAssetId = "set_ion_asset_id";
		public static readonly StringName GetIonAssetId = "get_ion_asset_id";
		public static readonly StringName SetShowHierarchy = "set_show_hierarchy";
		public static readonly StringName GetShowHierarchy = "get_show_hierarchy";
		public static readonly StringName IsInitialLoadingFinished = "is_initial_loading_finished";
		public static readonly StringName UpdateTileset = "update_tileset";
		public static readonly StringName SetDebugBoundingVolumesFunc = "set_debug_bounding_volumes_func";
		public static readonly StringName FreeTile = "free_tile";
		public static readonly StringName SetForEachTileFunc = "set_for_each_tile_func";
	}

	public class SignalName : Node3D.SignalName
	{
		public static readonly StringName LoadFailure = "load_failure";
	}

	private static readonly StringName NativeName = "Cesium3DTileset";

	#region Enums

	public enum CesiumHardwareBudgetProfile : long
	{
		Conservative = 0L,
		Balanced = 1L,
		Aggressive = 2L,
	}

	public enum CesiumDataSource : long
	{
		CesiumIon = 0L,
		Url = 1L,
	}

	public enum BoundingType : long
	{
		Box = 2L,
		CellVolume = 5L,
		CylinderRegion = 6L,
		Region = 3L,
		RegionWithLooseFittingHeights = 4L,
		Sphere = 1L,
	}

	#endregion

	#region Properties

	public float MaximumScreenSpaceError
	{
		get => (float)_object.Get(PropertyName.MaximumScreenSpaceError);
		set => _object.Set(PropertyName.MaximumScreenSpaceError, value);
	}

	public int MaximumSimultaneousTileLoads
	{
		get => (int)_object.Get(PropertyName.MaximumSimultaneousTileLoads);
		set => _object.Set(PropertyName.MaximumSimultaneousTileLoads, value);
	}

	public bool StaleRequestCancellationEnabled
	{
		get => (bool)_object.Get(PropertyName.StaleRequestCancellationEnabled);
		set => _object.Set(PropertyName.StaleRequestCancellationEnabled, value);
	}

	public bool PreloadAncestors
	{
		get => (bool)_object.Get(PropertyName.PreloadAncestors);
		set => _object.Set(PropertyName.PreloadAncestors, value);
	}

	public bool PreloadSiblings
	{
		get => (bool)_object.Get(PropertyName.PreloadSiblings);
		set => _object.Set(PropertyName.PreloadSiblings, value);
	}

	public int LoadingDescendantLimit
	{
		get => (int)_object.Get(PropertyName.LoadingDescendantLimit);
		set => _object.Set(PropertyName.LoadingDescendantLimit, value);
	}

	public bool ForbidHoles
	{
		get => (bool)_object.Get(PropertyName.ForbidHoles);
		set => _object.Set(PropertyName.ForbidHoles, value);
	}

	public bool FrustumCullingEnabled
	{
		get => (bool)_object.Get(PropertyName.FrustumCullingEnabled);
		set => _object.Set(PropertyName.FrustumCullingEnabled, value);
	}

	public bool OcclusionCullingEnabled
	{
		get => (bool)_object.Get(PropertyName.OcclusionCullingEnabled);
		set => _object.Set(PropertyName.OcclusionCullingEnabled, value);
	}

	public int OcclusionPoolSize
	{
		get => (int)_object.Get(PropertyName.OcclusionPoolSize);
		set => _object.Set(PropertyName.OcclusionPoolSize, value);
	}

	public bool DelayRefinementForOcclusion
	{
		get => (bool)_object.Get(PropertyName.DelayRefinementForOcclusion);
		set => _object.Set(PropertyName.DelayRefinementForOcclusion, value);
	}

	public bool FogCullingEnabled
	{
		get => (bool)_object.Get(PropertyName.FogCullingEnabled);
		set => _object.Set(PropertyName.FogCullingEnabled, value);
	}

	public bool EnforceCulledScreenSpaceError
	{
		get => (bool)_object.Get(PropertyName.EnforceCulledScreenSpaceError);
		set => _object.Set(PropertyName.EnforceCulledScreenSpaceError, value);
	}

	public float CulledScreenSpaceError
	{
		get => (float)_object.Get(PropertyName.CulledScreenSpaceError);
		set => _object.Set(PropertyName.CulledScreenSpaceError, value);
	}

	public bool RenderTilesUnderCamera
	{
		get => (bool)_object.Get(PropertyName.RenderTilesUnderCamera);
		set => _object.Set(PropertyName.RenderTilesUnderCamera, value);
	}

	public bool LodTransitionsEnabled
	{
		get => (bool)_object.Get(PropertyName.LodTransitionsEnabled);
		set => _object.Set(PropertyName.LodTransitionsEnabled, value);
	}

	public float LodTransitionLength
	{
		get => (float)_object.Get(PropertyName.LodTransitionLength);
		set => _object.Set(PropertyName.LodTransitionLength, value);
	}

	public bool KickDescendantsWhileFadingIn
	{
		get => (bool)_object.Get(PropertyName.KickDescendantsWhileFadingIn);
		set => _object.Set(PropertyName.KickDescendantsWhileFadingIn, value);
	}

	public int TranslucencySortPriority
	{
		get => (int)_object.Get(PropertyName.TranslucencySortPriority);
		set => _object.Set(PropertyName.TranslucencySortPriority, value);
	}

	public bool TranslucencyDepthPrepassEnabled
	{
		get => (bool)_object.Get(PropertyName.TranslucencyDepthPrepassEnabled);
		set => _object.Set(PropertyName.TranslucencyDepthPrepassEnabled, value);
	}

	public int MaximumCachedBytes
	{
		get => (int)_object.Get(PropertyName.MaximumCachedBytes);
		set => _object.Set(PropertyName.MaximumCachedBytes, value);
	}

	public bool AutomaticHardwareBudgetsEnabled
	{
		get => (bool)_object.Get(PropertyName.AutomaticHardwareBudgetsEnabled);
		set => _object.Set(PropertyName.AutomaticHardwareBudgetsEnabled, value);
	}

	public int HardwareBudgetProfile
	{
		get => (int)_object.Get(PropertyName.HardwareBudgetProfile);
		set => _object.Set(PropertyName.HardwareBudgetProfile, value);
	}

	public float AutomaticCacheBudgetShare
	{
		get => (float)_object.Get(PropertyName.AutomaticCacheBudgetShare);
		set => _object.Set(PropertyName.AutomaticCacheBudgetShare, value);
	}

	public int WorkerThreadCount
	{
		get => (int)_object.Get(PropertyName.WorkerThreadCount);
		set => _object.Set(PropertyName.WorkerThreadCount, value);
	}

	public float MainThreadLoadingTimeLimitMs
	{
		get => (float)_object.Get(PropertyName.MainThreadLoadingTimeLimitMs);
		set => _object.Set(PropertyName.MainThreadLoadingTimeLimitMs, value);
	}

	public int MaximumPrimitiveGeometryUploadBytes
	{
		get => (int)_object.Get(PropertyName.MaximumPrimitiveGeometryUploadBytes);
		set => _object.Set(PropertyName.MaximumPrimitiveGeometryUploadBytes, value);
	}

	public int MaximumPrimitiveTextureUploadBytes
	{
		get => (int)_object.Get(PropertyName.MaximumPrimitiveTextureUploadBytes);
		set => _object.Set(PropertyName.MaximumPrimitiveTextureUploadBytes, value);
	}

	public float TileCacheUnloadTimeLimitMs
	{
		get => (float)_object.Get(PropertyName.TileCacheUnloadTimeLimitMs);
		set => _object.Set(PropertyName.TileCacheUnloadTimeLimitMs, value);
	}

	public bool HttpCacheEnabled
	{
		get => (bool)_object.Get(PropertyName.HttpCacheEnabled);
		set => _object.Set(PropertyName.HttpCacheEnabled, value);
	}

	public string HttpCachePath
	{
		get => (string)_object.Get(PropertyName.HttpCachePath);
		set => _object.Set(PropertyName.HttpCachePath, value);
	}

	public int HttpCacheMaximumItems
	{
		get => (int)_object.Get(PropertyName.HttpCacheMaximumItems);
		set => _object.Set(PropertyName.HttpCacheMaximumItems, value);
	}

	public int HttpCacheMaximumDataBytes
	{
		get => (int)_object.Get(PropertyName.HttpCacheMaximumDataBytes);
		set => _object.Set(PropertyName.HttpCacheMaximumDataBytes, value);
	}

	public int HttpCachePruneIntervalRequests
	{
		get => (int)_object.Get(PropertyName.HttpCachePruneIntervalRequests);
		set => _object.Set(PropertyName.HttpCachePruneIntervalRequests, value);
	}

	public int MaximumNetworkRetries
	{
		get => (int)_object.Get(PropertyName.MaximumNetworkRetries);
		set => _object.Set(PropertyName.MaximumNetworkRetries, value);
	}

	public float NetworkRetryInitialDelaySeconds
	{
		get => (float)_object.Get(PropertyName.NetworkRetryInitialDelaySeconds);
		set => _object.Set(PropertyName.NetworkRetryInitialDelaySeconds, value);
	}

	public float NetworkRetryMaximumDelaySeconds
	{
		get => (float)_object.Get(PropertyName.NetworkRetryMaximumDelaySeconds);
		set => _object.Set(PropertyName.NetworkRetryMaximumDelaySeconds, value);
	}

	public bool MovementPredictionEnabled
	{
		get => (bool)_object.Get(PropertyName.MovementPredictionEnabled);
		set => _object.Set(PropertyName.MovementPredictionEnabled, value);
	}

	public float MovementPredictionSeconds
	{
		get => (float)_object.Get(PropertyName.MovementPredictionSeconds);
		set => _object.Set(PropertyName.MovementPredictionSeconds, value);
	}

	public float MovementPredictionMinimumSpeed
	{
		get => (float)_object.Get(PropertyName.MovementPredictionMinimumSpeed);
		set => _object.Set(PropertyName.MovementPredictionMinimumSpeed, value);
	}

	public float MovementPredictionMaximumDistance
	{
		get => (float)_object.Get(PropertyName.MovementPredictionMaximumDistance);
		set => _object.Set(PropertyName.MovementPredictionMaximumDistance, value);
	}

	public float MovementPredictionWeight
	{
		get => (float)_object.Get(PropertyName.MovementPredictionWeight);
		set => _object.Set(PropertyName.MovementPredictionWeight, value);
	}

	public bool TurnPredictionEnabled
	{
		get => (bool)_object.Get(PropertyName.TurnPredictionEnabled);
		set => _object.Set(PropertyName.TurnPredictionEnabled, value);
	}

	public float TurnPredictionMinimumAngularSpeedDegrees
	{
		get => (float)_object.Get(PropertyName.TurnPredictionMinimumAngularSpeedDegrees);
		set => _object.Set(PropertyName.TurnPredictionMinimumAngularSpeedDegrees, value);
	}

	public float TurnPredictionMaximumAngleDegrees
	{
		get => (float)_object.Get(PropertyName.TurnPredictionMaximumAngleDegrees);
		set => _object.Set(PropertyName.TurnPredictionMaximumAngleDegrees, value);
	}

	public bool ZoomOutPredictionEnabled
	{
		get => (bool)_object.Get(PropertyName.ZoomOutPredictionEnabled);
		set => _object.Set(PropertyName.ZoomOutPredictionEnabled, value);
	}

	public float ZoomOutPredictionMinimumRate
	{
		get => (float)_object.Get(PropertyName.ZoomOutPredictionMinimumRate);
		set => _object.Set(PropertyName.ZoomOutPredictionMinimumRate, value);
	}

	public float ZoomOutPredictionMaximumScale
	{
		get => (float)_object.Get(PropertyName.ZoomOutPredictionMaximumScale);
		set => _object.Set(PropertyName.ZoomOutPredictionMaximumScale, value);
	}

	public bool GenerateMissingNormalsSmooth
	{
		get => (bool)_object.Get(PropertyName.GenerateMissingNormalsSmooth);
		set => _object.Set(PropertyName.GenerateMissingNormalsSmooth, value);
	}

	public bool CreatePhysicsMeshes
	{
		get => (bool)_object.Get(PropertyName.CreatePhysicsMeshes);
		set => _object.Set(PropertyName.CreatePhysicsMeshes, value);
	}

	public Godot.NodePath CameraManagerPath
	{
		get => (Godot.NodePath)_object.Get(PropertyName.CameraManagerPath);
		set => _object.Set(PropertyName.CameraManagerPath, value);
	}

	public string Credit
	{
		get => (string)_object.Get(PropertyName.Credit);
		set => _object.Set(PropertyName.Credit, value);
	}

	public GodotObject CreditSystem
	{
		get => (GodotObject)_object.Get(PropertyName.CreditSystem);
		set => _object.Set(PropertyName.CreditSystem, value);
	}

	public GodotObject ResolvedCreditSystem
	{
		get => (GodotObject)_object.Get(PropertyName.ResolvedCreditSystem);
	}

	public bool ShowCreditsOnScreen
	{
		get => (bool)_object.Get(PropertyName.ShowCreditsOnScreen);
		set => _object.Set(PropertyName.ShowCreditsOnScreen, value);
	}

	public bool DebugTileStateCaptureEnabled
	{
		get => (bool)_object.Get(PropertyName.DebugTileStateCaptureEnabled);
		set => _object.Set(PropertyName.DebugTileStateCaptureEnabled, value);
	}

	public int DebugTileStateLimit
	{
		get => (int)_object.Get(PropertyName.DebugTileStateLimit);
		set => _object.Set(PropertyName.DebugTileStateLimit, value);
	}

	public Godot.Collections.Array DebugTileStates
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.DebugTileStates);
	}

	public int DebugTileStateFrameNumber
	{
		get => (int)_object.Get(PropertyName.DebugTileStateFrameNumber);
	}

	public bool DebugTileStatesTruncated
	{
		get => (bool)_object.Get(PropertyName.DebugTileStatesTruncated);
	}

	public GodotObject LifecycleEventReceiver
	{
		get => (GodotObject)_object.Get(PropertyName.LifecycleEventReceiver);
		set => _object.Set(PropertyName.LifecycleEventReceiver, value);
	}

	public CesiumMetadataStyle MetadataStyle
	{
		get => (CesiumMetadataStyle)_object.Get(PropertyName.MetadataStyle);
		set => _object.Set(PropertyName.MetadataStyle, value);
	}

	public CesiumPointCloudShading PointCloudShading
	{
		get => (CesiumPointCloudShading)_object.Get(PropertyName.PointCloudShading);
		set => _object.Set(PropertyName.PointCloudShading, value);
	}

	public int DataSource
	{
		get => (int)_object.Get(PropertyName.DataSource);
		set => _object.Set(PropertyName.DataSource, value);
	}

	public string Url
	{
		get => (string)_object.Get(PropertyName.Url);
		set => _object.Set(PropertyName.Url, value);
	}

	public Godot.Collections.Dictionary RequestHeaders
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.RequestHeaders);
		set => _object.Set(PropertyName.RequestHeaders, value);
	}

	public int IonAssetId
	{
		get => (int)_object.Get(PropertyName.IonAssetId);
		set => _object.Set(PropertyName.IonAssetId, value);
	}

	public bool ShowHierarchy
	{
		get => (bool)_object.Get(PropertyName.ShowHierarchy);
		set => _object.Set(PropertyName.ShowHierarchy, value);
	}

	public CesiumBoundingVolume TilesetBounds
	{
		get => (CesiumBoundingVolume)_object.Get(PropertyName.TilesetBounds);
	}

	#endregion

	#region Methods

	public void SetMaximumScreenSpaceError(float @error)
	{
		_object.Call(MethodName.SetMaximumScreenSpaceError, @error);
	}

	public float GetMaximumScreenSpaceError()
	{
		return (float)_object.Call(MethodName.GetMaximumScreenSpaceError);
	}

	public void SetMaximumSimultaneousTileLoads(int @count)
	{
		_object.Call(MethodName.SetMaximumSimultaneousTileLoads, @count);
	}

	public int GetMaximumSimultaneousTileLoads()
	{
		return (int)_object.Call(MethodName.GetMaximumSimultaneousTileLoads);
	}

	public void SetStaleRequestCancellationEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetStaleRequestCancellationEnabled, @enabled);
	}

	public bool GetStaleRequestCancellationEnabled()
	{
		return (bool)_object.Call(MethodName.GetStaleRequestCancellationEnabled);
	}

	public void SetPreloadAncestors(bool @preload)
	{
		_object.Call(MethodName.SetPreloadAncestors, @preload);
	}

	public bool GetPreloadAncestors()
	{
		return (bool)_object.Call(MethodName.GetPreloadAncestors);
	}

	public void SetPreloadSiblings(bool @preload)
	{
		_object.Call(MethodName.SetPreloadSiblings, @preload);
	}

	public bool GetPreloadSiblings()
	{
		return (bool)_object.Call(MethodName.GetPreloadSiblings);
	}

	public void SetLoadingDescendantLimit(int @limit)
	{
		_object.Call(MethodName.SetLoadingDescendantLimit, @limit);
	}

	public int GetLoadingDescendantLimit()
	{
		return (int)_object.Call(MethodName.GetLoadingDescendantLimit);
	}

	public void SetForbidHoles(bool @forbidHoles)
	{
		_object.Call(MethodName.SetForbidHoles, @forbidHoles);
	}

	public bool GetForbidHoles()
	{
		return (bool)_object.Call(MethodName.GetForbidHoles);
	}

	public void SetFrustumCullingEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetFrustumCullingEnabled, @enabled);
	}

	public bool GetFrustumCullingEnabled()
	{
		return (bool)_object.Call(MethodName.GetFrustumCullingEnabled);
	}

	public void SetOcclusionCullingEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetOcclusionCullingEnabled, @enabled);
	}

	public bool GetOcclusionCullingEnabled()
	{
		return (bool)_object.Call(MethodName.GetOcclusionCullingEnabled);
	}

	public void SetOcclusionPoolSize(int @size)
	{
		_object.Call(MethodName.SetOcclusionPoolSize, @size);
	}

	public int GetOcclusionPoolSize()
	{
		return (int)_object.Call(MethodName.GetOcclusionPoolSize);
	}

	public void SetDelayRefinementForOcclusion(bool @enabled)
	{
		_object.Call(MethodName.SetDelayRefinementForOcclusion, @enabled);
	}

	public bool GetDelayRefinementForOcclusion()
	{
		return (bool)_object.Call(MethodName.GetDelayRefinementForOcclusion);
	}

	public void SetFogCullingEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetFogCullingEnabled, @enabled);
	}

	public bool GetFogCullingEnabled()
	{
		return (bool)_object.Call(MethodName.GetFogCullingEnabled);
	}

	public void SetEnforceCulledScreenSpaceError(bool @enforce)
	{
		_object.Call(MethodName.SetEnforceCulledScreenSpaceError, @enforce);
	}

	public bool GetEnforceCulledScreenSpaceError()
	{
		return (bool)_object.Call(MethodName.GetEnforceCulledScreenSpaceError);
	}

	public void SetCulledScreenSpaceError(float @error)
	{
		_object.Call(MethodName.SetCulledScreenSpaceError, @error);
	}

	public float GetCulledScreenSpaceError()
	{
		return (float)_object.Call(MethodName.GetCulledScreenSpaceError);
	}

	public void SetRenderTilesUnderCamera(bool @enabled)
	{
		_object.Call(MethodName.SetRenderTilesUnderCamera, @enabled);
	}

	public bool GetRenderTilesUnderCamera()
	{
		return (bool)_object.Call(MethodName.GetRenderTilesUnderCamera);
	}

	public void SetLodTransitionsEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetLodTransitionsEnabled, @enabled);
	}

	public bool GetLodTransitionsEnabled()
	{
		return (bool)_object.Call(MethodName.GetLodTransitionsEnabled);
	}

	public void SetLodTransitionLength(float @seconds)
	{
		_object.Call(MethodName.SetLodTransitionLength, @seconds);
	}

	public float GetLodTransitionLength()
	{
		return (float)_object.Call(MethodName.GetLodTransitionLength);
	}

	public void SetKickDescendantsWhileFadingIn(bool @enabled)
	{
		_object.Call(MethodName.SetKickDescendantsWhileFadingIn, @enabled);
	}

	public bool GetKickDescendantsWhileFadingIn()
	{
		return (bool)_object.Call(MethodName.GetKickDescendantsWhileFadingIn);
	}

	public void SetTranslucencySortPriority(int @priority)
	{
		_object.Call(MethodName.SetTranslucencySortPriority, @priority);
	}

	public int GetTranslucencySortPriority()
	{
		return (int)_object.Call(MethodName.GetTranslucencySortPriority);
	}

	public void SetTranslucencyDepthPrepassEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetTranslucencyDepthPrepassEnabled, @enabled);
	}

	public bool GetTranslucencyDepthPrepassEnabled()
	{
		return (bool)_object.Call(MethodName.GetTranslucencyDepthPrepassEnabled);
	}

	public void SetMaximumCachedBytes(int @bytes)
	{
		_object.Call(MethodName.SetMaximumCachedBytes, @bytes);
	}

	public int GetMaximumCachedBytes()
	{
		return (int)_object.Call(MethodName.GetMaximumCachedBytes);
	}

	public void SetAutomaticHardwareBudgetsEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetAutomaticHardwareBudgetsEnabled, @enabled);
	}

	public bool GetAutomaticHardwareBudgetsEnabled()
	{
		return (bool)_object.Call(MethodName.GetAutomaticHardwareBudgetsEnabled);
	}

	public void SetHardwareBudgetProfile(int @profile)
	{
		_object.Call(MethodName.SetHardwareBudgetProfile, @profile);
	}

	public int GetHardwareBudgetProfile()
	{
		return (int)_object.Call(MethodName.GetHardwareBudgetProfile);
	}

	public void SetAutomaticCacheBudgetShare(float @share)
	{
		_object.Call(MethodName.SetAutomaticCacheBudgetShare, @share);
	}

	public float GetAutomaticCacheBudgetShare()
	{
		return (float)_object.Call(MethodName.GetAutomaticCacheBudgetShare);
	}

	public int RecalculateAutomaticHardwareBudgets()
	{
		return (int)_object.Call(MethodName.RecalculateAutomaticHardwareBudgets);
	}

	public Godot.Collections.Dictionary GetHardwareCapabilities()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetHardwareCapabilities);
	}

	public int GetRecommendedTotalCacheBytes(int @profile)
	{
		return (int)_object.Call(MethodName.GetRecommendedTotalCacheBytes, @profile);
	}

	public void SetWorkerThreadCount(int @count)
	{
		_object.Call(MethodName.SetWorkerThreadCount, @count);
	}

	public int GetWorkerThreadCount()
	{
		return (int)_object.Call(MethodName.GetWorkerThreadCount);
	}

	public void ResetWorkerThreadCountToAutomatic()
	{
		_object.Call(MethodName.ResetWorkerThreadCountToAutomatic);
	}

	public void SetMainThreadLoadingTimeLimitMs(float @milliseconds)
	{
		_object.Call(MethodName.SetMainThreadLoadingTimeLimitMs, @milliseconds);
	}

	public float GetMainThreadLoadingTimeLimitMs()
	{
		return (float)_object.Call(MethodName.GetMainThreadLoadingTimeLimitMs);
	}

	public void SetMaximumPrimitiveGeometryUploadBytes(int @bytes)
	{
		_object.Call(MethodName.SetMaximumPrimitiveGeometryUploadBytes, @bytes);
	}

	public int GetMaximumPrimitiveGeometryUploadBytes()
	{
		return (int)_object.Call(MethodName.GetMaximumPrimitiveGeometryUploadBytes);
	}

	public void SetMaximumPrimitiveTextureUploadBytes(int @bytes)
	{
		_object.Call(MethodName.SetMaximumPrimitiveTextureUploadBytes, @bytes);
	}

	public int GetMaximumPrimitiveTextureUploadBytes()
	{
		return (int)_object.Call(MethodName.GetMaximumPrimitiveTextureUploadBytes);
	}

	public void SetTileCacheUnloadTimeLimitMs(float @milliseconds)
	{
		_object.Call(MethodName.SetTileCacheUnloadTimeLimitMs, @milliseconds);
	}

	public float GetTileCacheUnloadTimeLimitMs()
	{
		return (float)_object.Call(MethodName.GetTileCacheUnloadTimeLimitMs);
	}

	public void SetHttpCacheEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetHttpCacheEnabled, @enabled);
	}

	public bool GetHttpCacheEnabled()
	{
		return (bool)_object.Call(MethodName.GetHttpCacheEnabled);
	}

	public void SetHttpCachePath(string @path)
	{
		_object.Call(MethodName.SetHttpCachePath, @path);
	}

	public string GetHttpCachePath()
	{
		return (string)_object.Call(MethodName.GetHttpCachePath);
	}

	public string GetResolvedHttpCachePath()
	{
		return (string)_object.Call(MethodName.GetResolvedHttpCachePath);
	}

	public void SetHttpCacheMaximumItems(int @maximum_items)
	{
		_object.Call(MethodName.SetHttpCacheMaximumItems, @maximum_items);
	}

	public int GetHttpCacheMaximumItems()
	{
		return (int)_object.Call(MethodName.GetHttpCacheMaximumItems);
	}

	public void SetHttpCacheMaximumDataBytes(int @maximum_bytes)
	{
		_object.Call(MethodName.SetHttpCacheMaximumDataBytes, @maximum_bytes);
	}

	public int GetHttpCacheMaximumDataBytes()
	{
		return (int)_object.Call(MethodName.GetHttpCacheMaximumDataBytes);
	}

	public void SetHttpCachePruneIntervalRequests(int @requests)
	{
		_object.Call(MethodName.SetHttpCachePruneIntervalRequests, @requests);
	}

	public int GetHttpCachePruneIntervalRequests()
	{
		return (int)_object.Call(MethodName.GetHttpCachePruneIntervalRequests);
	}

	public bool ClearHttpCache()
	{
		return (bool)_object.Call(MethodName.ClearHttpCache);
	}

	public bool PruneHttpCache()
	{
		return (bool)_object.Call(MethodName.PruneHttpCache);
	}

	public void SetMaximumNetworkRetries(int @retries)
	{
		_object.Call(MethodName.SetMaximumNetworkRetries, @retries);
	}

	public int GetMaximumNetworkRetries()
	{
		return (int)_object.Call(MethodName.GetMaximumNetworkRetries);
	}

	public void SetNetworkRetryInitialDelaySeconds(float @seconds)
	{
		_object.Call(MethodName.SetNetworkRetryInitialDelaySeconds, @seconds);
	}

	public float GetNetworkRetryInitialDelaySeconds()
	{
		return (float)_object.Call(MethodName.GetNetworkRetryInitialDelaySeconds);
	}

	public void SetNetworkRetryMaximumDelaySeconds(float @seconds)
	{
		_object.Call(MethodName.SetNetworkRetryMaximumDelaySeconds, @seconds);
	}

	public float GetNetworkRetryMaximumDelaySeconds()
	{
		return (float)_object.Call(MethodName.GetNetworkRetryMaximumDelaySeconds);
	}

	public void SetMovementPredictionEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetMovementPredictionEnabled, @enabled);
	}

	public bool GetMovementPredictionEnabled()
	{
		return (bool)_object.Call(MethodName.GetMovementPredictionEnabled);
	}

	public void SetMovementPredictionSeconds(float @seconds)
	{
		_object.Call(MethodName.SetMovementPredictionSeconds, @seconds);
	}

	public float GetMovementPredictionSeconds()
	{
		return (float)_object.Call(MethodName.GetMovementPredictionSeconds);
	}

	public void SetMovementPredictionMinimumSpeed(float @meters_per_second)
	{
		_object.Call(MethodName.SetMovementPredictionMinimumSpeed, @meters_per_second);
	}

	public float GetMovementPredictionMinimumSpeed()
	{
		return (float)_object.Call(MethodName.GetMovementPredictionMinimumSpeed);
	}

	public void SetMovementPredictionMaximumDistance(float @meters)
	{
		_object.Call(MethodName.SetMovementPredictionMaximumDistance, @meters);
	}

	public float GetMovementPredictionMaximumDistance()
	{
		return (float)_object.Call(MethodName.GetMovementPredictionMaximumDistance);
	}

	public void SetMovementPredictionWeight(float @weight)
	{
		_object.Call(MethodName.SetMovementPredictionWeight, @weight);
	}

	public float GetMovementPredictionWeight()
	{
		return (float)_object.Call(MethodName.GetMovementPredictionWeight);
	}

	public void SetTurnPredictionEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetTurnPredictionEnabled, @enabled);
	}

	public bool GetTurnPredictionEnabled()
	{
		return (bool)_object.Call(MethodName.GetTurnPredictionEnabled);
	}

	public void SetTurnPredictionMinimumAngularSpeedDegrees(float @degrees_per_second)
	{
		_object.Call(MethodName.SetTurnPredictionMinimumAngularSpeedDegrees, @degrees_per_second);
	}

	public float GetTurnPredictionMinimumAngularSpeedDegrees()
	{
		return (float)_object.Call(MethodName.GetTurnPredictionMinimumAngularSpeedDegrees);
	}

	public void SetTurnPredictionMaximumAngleDegrees(float @degrees)
	{
		_object.Call(MethodName.SetTurnPredictionMaximumAngleDegrees, @degrees);
	}

	public float GetTurnPredictionMaximumAngleDegrees()
	{
		return (float)_object.Call(MethodName.GetTurnPredictionMaximumAngleDegrees);
	}

	public void SetZoomOutPredictionEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetZoomOutPredictionEnabled, @enabled);
	}

	public bool GetZoomOutPredictionEnabled()
	{
		return (bool)_object.Call(MethodName.GetZoomOutPredictionEnabled);
	}

	public void SetZoomOutPredictionMinimumRate(float @rate)
	{
		_object.Call(MethodName.SetZoomOutPredictionMinimumRate, @rate);
	}

	public float GetZoomOutPredictionMinimumRate()
	{
		return (float)_object.Call(MethodName.GetZoomOutPredictionMinimumRate);
	}

	public void SetZoomOutPredictionMaximumScale(float @scale)
	{
		_object.Call(MethodName.SetZoomOutPredictionMaximumScale, @scale);
	}

	public float GetZoomOutPredictionMaximumScale()
	{
		return (float)_object.Call(MethodName.GetZoomOutPredictionMaximumScale);
	}

	public void SetGenerateMissingNormalsSmooth(bool @shouldGenerate)
	{
		_object.Call(MethodName.SetGenerateMissingNormalsSmooth, @shouldGenerate);
	}

	public bool GetGenerateMissingNormalsSmooth()
	{
		return (bool)_object.Call(MethodName.GetGenerateMissingNormalsSmooth);
	}

	public void SetCreatePhysicsMeshes(bool @shouldGenerate)
	{
		_object.Call(MethodName.SetCreatePhysicsMeshes, @shouldGenerate);
	}

	public bool GetCreatePhysicsMeshes()
	{
		return (bool)_object.Call(MethodName.GetCreatePhysicsMeshes);
	}

	public void SetCameraManagerPath(Godot.NodePath @camera_manager_path)
	{
		_object.Call(MethodName.SetCameraManagerPath, @camera_manager_path);
	}

	public Godot.NodePath GetCameraManagerPath()
	{
		return (Godot.NodePath)_object.Call(MethodName.GetCameraManagerPath);
	}

	public void SetCredit(string @credit)
	{
		_object.Call(MethodName.SetCredit, @credit);
	}

	public string GetCredit()
	{
		return (string)_object.Call(MethodName.GetCredit);
	}

	public void SetCreditSystem(CesiumGDCreditSystem @credit_system)
	{
		_object.Call(MethodName.SetCreditSystem, @credit_system);
	}

	public CesiumGDCreditSystem GetCreditSystem()
	{
		return (CesiumGDCreditSystem)_object.Call(MethodName.GetCreditSystem);
	}

	public CesiumGDCreditSystem ResolveCreditSystem()
	{
		return (CesiumGDCreditSystem)_object.Call(MethodName.ResolveCreditSystem);
	}

	public CesiumGDCreditSystem GetResolvedCreditSystem()
	{
		return (CesiumGDCreditSystem)_object.Call(MethodName.GetResolvedCreditSystem);
	}

	public void InvalidateResolvedCreditSystem()
	{
		_object.Call(MethodName.InvalidateResolvedCreditSystem);
	}

	public void SetShowCreditsOnScreen(bool @show_on_screen)
	{
		_object.Call(MethodName.SetShowCreditsOnScreen, @show_on_screen);
	}

	public bool GetShowCreditsOnScreen()
	{
		return (bool)_object.Call(MethodName.GetShowCreditsOnScreen);
	}

	public void SetLifecycleEventReceiver(Cesium3DTilesetLifecycleEventReceiver @receiver)
	{
		_object.Call(MethodName.SetLifecycleEventReceiver, @receiver);
	}

	public Cesium3DTilesetLifecycleEventReceiver GetLifecycleEventReceiver()
	{
		return (Cesium3DTilesetLifecycleEventReceiver)_object.Call(MethodName.GetLifecycleEventReceiver);
	}

	public void SetMetadataStyle(CesiumMetadataStyle @style)
	{
		_object.Call(MethodName.SetMetadataStyle, @style);
	}

	public CesiumMetadataStyle GetMetadataStyle()
	{
		return (CesiumMetadataStyle)_object.Call(MethodName.GetMetadataStyle);
	}

	public void RefreshMetadataStyle()
	{
		_object.Call(MethodName.RefreshMetadataStyle);
	}

	public void SetPointCloudShading(CesiumPointCloudShading @shading)
	{
		_object.Call(MethodName.SetPointCloudShading, @shading);
	}

	public CesiumPointCloudShading GetPointCloudShading()
	{
		return (CesiumPointCloudShading)_object.Call(MethodName.GetPointCloudShading);
	}

	public void RefreshPointCloudShading()
	{
		_object.Call(MethodName.RefreshPointCloudShading);
	}

	public bool HasActiveTileset()
	{
		return (bool)_object.Call(MethodName.HasActiveTileset);
	}

	public CesiumBoundingVolume GetTilesetBounds()
	{
		return (CesiumBoundingVolume)_object.Call(MethodName.GetTilesetBounds);
	}

	public Godot.Aabb GetTilesetSourceAabb()
	{
		return (Godot.Aabb)_object.Call(MethodName.GetTilesetSourceAabb);
	}

	public CesiumSampleHeightMostDetailedRequest SampleHeightMostDetailed(Godot.Vector3[] @longitude_latitude_height)
	{
		return (CesiumSampleHeightMostDetailedRequest)_object.Call(MethodName.SampleHeightMostDetailed, @longitude_latitude_height);
	}

	public CesiumSampleHeightMostDetailedRequest SampleHeightMostDetailedExact(double[] @longitude_latitude_height_components)
	{
		return (CesiumSampleHeightMostDetailedRequest)_object.Call(MethodName.SampleHeightMostDetailedExact, @longitude_latitude_height_components);
	}

	public Godot.Collections.Dictionary GetStreamingStatistics()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetStreamingStatistics);
	}

	public void SetDebugTileStateCaptureEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetDebugTileStateCaptureEnabled, @enabled);
	}

	public bool GetDebugTileStateCaptureEnabled()
	{
		return (bool)_object.Call(MethodName.GetDebugTileStateCaptureEnabled);
	}

	public void SetDebugTileStateLimit(int @limit)
	{
		_object.Call(MethodName.SetDebugTileStateLimit, @limit);
	}

	public int GetDebugTileStateLimit()
	{
		return (int)_object.Call(MethodName.GetDebugTileStateLimit);
	}

	public Godot.Collections.Array GetDebugTileStates()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetDebugTileStates);
	}

	public int GetDebugTileStateFrameNumber()
	{
		return (int)_object.Call(MethodName.GetDebugTileStateFrameNumber);
	}

	public bool GetDebugTileStatesTruncated()
	{
		return (bool)_object.Call(MethodName.GetDebugTileStatesTruncated);
	}

	public CesiumRasterOverlayBinding AttachRasterOverlay(CesiumLoadedTilePrimitive @primitive, string @overlay_key, Texture2D @texture, int @texture_coordinate_id, int @texture_coordinate_index, Godot.Vector2 @translation, Godot.Vector2 @scale)
	{
		return (CesiumRasterOverlayBinding)_object.Call(MethodName.AttachRasterOverlay, @primitive, @overlay_key, @texture, @texture_coordinate_id, @texture_coordinate_index, @translation, @scale);
	}

	public bool DetachRasterOverlay(CesiumLoadedTilePrimitive @primitive, string @overlay_key, Texture2D @expected_texture = default)
	{
		return (bool)_object.Call(MethodName.DetachRasterOverlay, @primitive, @overlay_key, @expected_texture);
	}

	public int GetDataSource()
	{
		return (int)_object.Call(MethodName.GetDataSource);
	}

	public void SetDataSource(int @data_source)
	{
		_object.Call(MethodName.SetDataSource, @data_source);
	}

	public void SetUrl(string @url)
	{
		_object.Call(MethodName.SetUrl, @url);
	}

	public string GetUrl()
	{
		return (string)_object.Call(MethodName.GetUrl);
	}

	public void SetRequestHeaders(Godot.Collections.Dictionary @headers)
	{
		_object.Call(MethodName.SetRequestHeaders, @headers);
	}

	public Godot.Collections.Dictionary GetRequestHeaders()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetRequestHeaders);
	}

	public void SetIonAssetId(int @ion_asset_id)
	{
		_object.Call(MethodName.SetIonAssetId, @ion_asset_id);
	}

	public int GetIonAssetId()
	{
		return (int)_object.Call(MethodName.GetIonAssetId);
	}

	public void SetShowHierarchy(bool @showHierarchy)
	{
		_object.Call(MethodName.SetShowHierarchy, @showHierarchy);
	}

	public bool GetShowHierarchy()
	{
		return (bool)_object.Call(MethodName.GetShowHierarchy);
	}

	public bool IsInitialLoadingFinished()
	{
		return (bool)_object.Call(MethodName.IsInitialLoadingFinished);
	}

	public void UpdateTileset(Godot.Transform3D @camera_transform)
	{
		_object.Call(MethodName.UpdateTileset, @camera_transform);
	}

	public void SetDebugBoundingVolumesFunc(Godot.Callable @onTileDrawn)
	{
		_object.Call(MethodName.SetDebugBoundingVolumesFunc, @onTileDrawn);
	}

	public void FreeTile(Cesium3DTile @_unnamed_arg0, int @_unnamed_arg1)
	{
		_object.Call(MethodName.FreeTile, @_unnamed_arg0, @_unnamed_arg1);
	}

	public void SetForEachTileFunc(Godot.Callable @onTileFunc)
	{
		_object.Call(MethodName.SetForEachTileFunc, @onTileFunc);
	}

	#endregion

	#region Signals

	public event Action<GodotObject> LoadFailure
	{
		add
		{
			_object.Connect(SignalName.LoadFailure, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.LoadFailure, Callable.From(value));
		}
	}

	#endregion
}
