// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumDebugUtils
{
	// Engine object used for calling engine methods
	protected GodotObject _object;

	public GodotObject NativeObject => _object;

	public CesiumDebugUtils() : this(NativeName)
	{
	}
	protected CesiumDebugUtils(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumDebugUtils(Variant variant) : this((GodotObject) variant)
	{
	}
	protected CesiumDebugUtils([NotNull] GodotObject @object)
	{
		_object = @object;
	}

	public static implicit operator GodotObject(CesiumDebugUtils self) => self?._object;
	public static implicit operator Variant(CesiumDebugUtils self) => self?._object;
	public static explicit operator CesiumDebugUtils(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : GodotObject.PropertyName
	{

	}

	public class MethodName : GodotObject.MethodName
	{
		public static readonly StringName DrawLine = "draw_line";
	}

	public class SignalName : GodotObject.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumDebugUtils";

	#region Methods

	public static void DrawLine(Godot.Vector3 @from, Godot.Vector3 @to, Godot.Color @color)
	{
		ClassDB.ClassCallStatic(NativeName, MethodName.DrawLine, @from, @to, @color);
	}

	#endregion
}
