// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumMetadataPicking
{
	// Engine object used for calling engine methods
	protected GodotObject _object;

	public GodotObject NativeObject => _object;

	public CesiumMetadataPicking() : this(NativeName)
	{
	}
	protected CesiumMetadataPicking(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumMetadataPicking(Variant variant) : this((GodotObject) variant)
	{
	}
	protected CesiumMetadataPicking([NotNull] GodotObject @object)
	{
		_object = @object;
	}

	public static implicit operator GodotObject(CesiumMetadataPicking self) => self?._object;
	public static implicit operator Variant(CesiumMetadataPicking self) => self?._object;
	public static explicit operator CesiumMetadataPicking(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : GodotObject.PropertyName
	{

	}

	public class MethodName : GodotObject.MethodName
	{
		public static readonly StringName ResolveHit = "resolve_hit";
		public static readonly StringName ResolveInstance = "resolve_instance";
		public static readonly StringName GetFeatureIdFromInstance = "get_feature_id_from_instance";
		public static readonly StringName GetMetadataValuesFromInstance = "get_metadata_values_from_instance";
		public static readonly StringName GetFeatureIdFromHit = "get_feature_id_from_hit";
		public static readonly StringName GetMetadataValuesFromHit = "get_metadata_values_from_hit";
		public static readonly StringName GetPropertyTextureValuesFromHit = "get_property_texture_values_from_hit";
	}

	public class SignalName : GodotObject.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumMetadataPicking";

	#region Methods

	public static Godot.Collections.Dictionary ResolveHit(Godot.Collections.Dictionary @hit, int @feature_id_set_index = 0)
	{
		return (Godot.Collections.Dictionary)ClassDB.ClassCallStatic(NativeName, MethodName.ResolveHit, @hit, @feature_id_set_index);
	}

	public static Godot.Collections.Dictionary ResolveInstance(CesiumLoadedTilePrimitive @primitive, int @instance_index, int @feature_id_set_index = 0)
	{
		return (Godot.Collections.Dictionary)ClassDB.ClassCallStatic(NativeName, MethodName.ResolveInstance, @primitive, @instance_index, @feature_id_set_index);
	}

	public static int GetFeatureIdFromInstance(CesiumLoadedTilePrimitive @primitive, int @instance_index, int @feature_id_set_index = 0)
	{
		return (int)ClassDB.ClassCallStatic(NativeName, MethodName.GetFeatureIdFromInstance, @primitive, @instance_index, @feature_id_set_index);
	}

	public static Godot.Collections.Dictionary GetMetadataValuesFromInstance(CesiumLoadedTilePrimitive @primitive, int @instance_index, int @feature_id_set_index = 0)
	{
		return (Godot.Collections.Dictionary)ClassDB.ClassCallStatic(NativeName, MethodName.GetMetadataValuesFromInstance, @primitive, @instance_index, @feature_id_set_index);
	}

	public static int GetFeatureIdFromHit(Godot.Collections.Dictionary @hit, int @feature_id_set_index = 0)
	{
		return (int)ClassDB.ClassCallStatic(NativeName, MethodName.GetFeatureIdFromHit, @hit, @feature_id_set_index);
	}

	public static Godot.Collections.Dictionary GetMetadataValuesFromHit(Godot.Collections.Dictionary @hit, int @feature_id_set_index = 0)
	{
		return (Godot.Collections.Dictionary)ClassDB.ClassCallStatic(NativeName, MethodName.GetMetadataValuesFromHit, @hit, @feature_id_set_index);
	}

	public static Godot.Collections.Dictionary GetPropertyTextureValuesFromHit(Godot.Collections.Dictionary @hit, int @property_texture_index)
	{
		return (Godot.Collections.Dictionary)ClassDB.ClassCallStatic(NativeName, MethodName.GetPropertyTextureValuesFromHit, @hit, @property_texture_index);
	}

	#endregion
}
