// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumPrimitiveMetadata
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumPrimitiveMetadata() : this(NativeName)
	{
	}
	protected CesiumPrimitiveMetadata(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumPrimitiveMetadata(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumPrimitiveMetadata([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumPrimitiveMetadata self) => self?._object;
	public static implicit operator Variant(CesiumPrimitiveMetadata self) => self?._object;
	public static explicit operator CesiumPrimitiveMetadata(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName PropertyTextureIndices = "property_texture_indices";
		public static readonly StringName PropertyAttributeIndices = "property_attribute_indices";
		public static readonly StringName PropertyAttributes = "property_attributes";
		public static readonly StringName RetainedMemoryBytes = "retained_memory_bytes";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetPropertyTextureIndices = "get_property_texture_indices";
		public static readonly StringName GetPropertyAttributeIndices = "get_property_attribute_indices";
		public static readonly StringName GetPropertyAttributes = "get_property_attributes";
		public static readonly StringName GetPropertyAttributeCount = "get_property_attribute_count";
		public static readonly StringName GetPropertyAttribute = "get_property_attribute";
		public static readonly StringName FindTextureCoordinateFromHit = "find_texture_coordinate_from_hit";
		public static readonly StringName GetPropertyTextureValuesFromHit = "get_property_texture_values_from_hit";
		public static readonly StringName GetRetainedMemoryBytes = "get_retained_memory_bytes";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumPrimitiveMetadata";

	#region Properties

	public Godot.Collections.Array PropertyTextureIndices
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.PropertyTextureIndices);
	}

	public Godot.Collections.Array PropertyAttributeIndices
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.PropertyAttributeIndices);
	}

	public Godot.Collections.Array PropertyAttributes
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.PropertyAttributes);
	}

	public int RetainedMemoryBytes
	{
		get => (int)_object.Get(PropertyName.RetainedMemoryBytes);
	}

	#endregion

	#region Methods

	public Godot.Collections.Array GetPropertyTextureIndices()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetPropertyTextureIndices);
	}

	public Godot.Collections.Array GetPropertyAttributeIndices()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetPropertyAttributeIndices);
	}

	public Godot.Collections.Array GetPropertyAttributes()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetPropertyAttributes);
	}

	public int GetPropertyAttributeCount()
	{
		return (int)_object.Call(MethodName.GetPropertyAttributeCount);
	}

	public CesiumPropertyAttribute GetPropertyAttribute(int @index)
	{
		return (CesiumPropertyAttribute)_object.Call(MethodName.GetPropertyAttribute, @index);
	}

	public Variant FindTextureCoordinateFromHit(int @face_index, Godot.Vector3 @local_position, int @texture_coordinate_set_index)
	{
		return (Variant)_object.Call(MethodName.FindTextureCoordinateFromHit, @face_index, @local_position, @texture_coordinate_set_index);
	}

	public Godot.Collections.Dictionary GetPropertyTextureValuesFromHit(CesiumModelMetadata @model_metadata, int @property_texture_index, int @face_index, Godot.Vector3 @local_position)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetPropertyTextureValuesFromHit, @model_metadata, @property_texture_index, @face_index, @local_position);
	}

	public int GetRetainedMemoryBytes()
	{
		return (int)_object.Call(MethodName.GetRetainedMemoryBytes);
	}

	#endregion
}
