// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumLoadFailure
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumLoadFailure() : this(NativeName)
	{
	}
	protected CesiumLoadFailure(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumLoadFailure(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumLoadFailure([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumLoadFailure self) => self?._object;
	public static implicit operator Variant(CesiumLoadFailure self) => self?._object;
	public static explicit operator CesiumLoadFailure(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Source = "source";
		public static readonly StringName SourceInstanceId = "source_instance_id";
		public static readonly StringName Category = "category";
		public static readonly StringName CategoryName = "category_name";
		public static readonly StringName Stage = "stage";
		public static readonly StringName StageName = "stage_name";
		public static readonly StringName Message = "message";
		public static readonly StringName Url = "url";
		public static readonly StringName TileId = "tile_id";
		public static readonly StringName OverlayKey = "overlay_key";
		public static readonly StringName HttpStatusCode = "http_status_code";
		public static readonly StringName Terminal = "terminal";
		public static readonly StringName Retryable = "retryable";
		public static readonly StringName RetryScheduled = "retry_scheduled";
		public static readonly StringName Attempt = "attempt";
		public static readonly StringName MaximumAttempts = "maximum_attempts";
		public static readonly StringName RetryDelaySeconds = "retry_delay_seconds";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetSource = "get_source";
		public static readonly StringName GetSourceInstanceId = "get_source_instance_id";
		public static readonly StringName GetCategory = "get_category";
		public static readonly StringName GetCategoryName = "get_category_name";
		public static readonly StringName GetStage = "get_stage";
		public static readonly StringName GetStageName = "get_stage_name";
		public static readonly StringName GetMessage = "get_message";
		public static readonly StringName GetUrl = "get_url";
		public static readonly StringName GetTileId = "get_tile_id";
		public static readonly StringName GetOverlayKey = "get_overlay_key";
		public static readonly StringName GetHttpStatusCode = "get_http_status_code";
		public static readonly StringName GetTerminal = "get_terminal";
		public static readonly StringName GetRetryable = "get_retryable";
		public static readonly StringName GetRetryScheduled = "get_retry_scheduled";
		public static readonly StringName GetAttempt = "get_attempt";
		public static readonly StringName GetMaximumAttempts = "get_maximum_attempts";
		public static readonly StringName GetRetryDelaySeconds = "get_retry_delay_seconds";
		public static readonly StringName ToDictionary = "to_dictionary";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumLoadFailure";

	#region Enums

	public enum CategoryEnum : long
	{
		Unknown = 0L,
		Tileset = 1L,
		TileContent = 2L,
		RasterOverlay = 3L,
		Network = 4L,
		Decode = 5L,
		Material = 6L,
		Renderer = 7L,
		Cache = 8L,
	}

	public enum StageEnum : long
	{
		Unknown = 0L,
		IonEndpoint = 1L,
		TilesetJson = 2L,
		TileContentRequest = 3L,
		RasterTileProvider = 4L,
		RasterTileRequest = 5L,
		NetworkRequest = 6L,
		GltfDecode = 7L,
		MaterialCreation = 8L,
		RendererPreparation = 9L,
		TextureUpload = 10L,
		CacheOpen = 11L,
		CacheMaintenance = 12L,
	}

	#endregion

	#region Properties

	public GodotObject Source
	{
		get => (GodotObject)_object.Get(PropertyName.Source);
	}

	public int SourceInstanceId
	{
		get => (int)_object.Get(PropertyName.SourceInstanceId);
	}

	public int Category
	{
		get => (int)_object.Get(PropertyName.Category);
	}

	public string CategoryName
	{
		get => (string)_object.Get(PropertyName.CategoryName);
	}

	public int Stage
	{
		get => (int)_object.Get(PropertyName.Stage);
	}

	public string StageName
	{
		get => (string)_object.Get(PropertyName.StageName);
	}

	public string Message
	{
		get => (string)_object.Get(PropertyName.Message);
	}

	public string Url
	{
		get => (string)_object.Get(PropertyName.Url);
	}

	public string TileId
	{
		get => (string)_object.Get(PropertyName.TileId);
	}

	public string OverlayKey
	{
		get => (string)_object.Get(PropertyName.OverlayKey);
	}

	public int HttpStatusCode
	{
		get => (int)_object.Get(PropertyName.HttpStatusCode);
	}

	public bool Terminal
	{
		get => (bool)_object.Get(PropertyName.Terminal);
	}

	public bool Retryable
	{
		get => (bool)_object.Get(PropertyName.Retryable);
	}

	public bool RetryScheduled
	{
		get => (bool)_object.Get(PropertyName.RetryScheduled);
	}

	public int Attempt
	{
		get => (int)_object.Get(PropertyName.Attempt);
	}

	public int MaximumAttempts
	{
		get => (int)_object.Get(PropertyName.MaximumAttempts);
	}

	public float RetryDelaySeconds
	{
		get => (float)_object.Get(PropertyName.RetryDelaySeconds);
	}

	#endregion

	#region Methods

	public GodotObject GetSource()
	{
		return (GodotObject)_object.Call(MethodName.GetSource);
	}

	public int GetSourceInstanceId()
	{
		return (int)_object.Call(MethodName.GetSourceInstanceId);
	}

	public int GetCategory()
	{
		return (int)_object.Call(MethodName.GetCategory);
	}

	public string GetCategoryName()
	{
		return (string)_object.Call(MethodName.GetCategoryName);
	}

	public int GetStage()
	{
		return (int)_object.Call(MethodName.GetStage);
	}

	public string GetStageName()
	{
		return (string)_object.Call(MethodName.GetStageName);
	}

	public string GetMessage()
	{
		return (string)_object.Call(MethodName.GetMessage);
	}

	public string GetUrl()
	{
		return (string)_object.Call(MethodName.GetUrl);
	}

	public string GetTileId()
	{
		return (string)_object.Call(MethodName.GetTileId);
	}

	public string GetOverlayKey()
	{
		return (string)_object.Call(MethodName.GetOverlayKey);
	}

	public int GetHttpStatusCode()
	{
		return (int)_object.Call(MethodName.GetHttpStatusCode);
	}

	public bool GetTerminal()
	{
		return (bool)_object.Call(MethodName.GetTerminal);
	}

	public bool GetRetryable()
	{
		return (bool)_object.Call(MethodName.GetRetryable);
	}

	public bool GetRetryScheduled()
	{
		return (bool)_object.Call(MethodName.GetRetryScheduled);
	}

	public int GetAttempt()
	{
		return (int)_object.Call(MethodName.GetAttempt);
	}

	public int GetMaximumAttempts()
	{
		return (int)_object.Call(MethodName.GetMaximumAttempts);
	}

	public float GetRetryDelaySeconds()
	{
		return (float)_object.Call(MethodName.GetRetryDelaySeconds);
	}

	public Godot.Collections.Dictionary ToDictionary()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.ToDictionary);
	}

	#endregion
}
