// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumPolygonRasterOverlay : CesiumRasterOverlay
{
	public CesiumPolygonRasterOverlay() : base(NativeName)
	{
	}
	protected CesiumPolygonRasterOverlay(StringName @class) : base(@class)
	{
	}
	protected CesiumPolygonRasterOverlay(Variant variant) : base(variant)
	{
	}
	protected CesiumPolygonRasterOverlay([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(CesiumPolygonRasterOverlay self) => self?._object;
	public static implicit operator Variant(CesiumPolygonRasterOverlay self) => self?._object;
	public static explicit operator CesiumPolygonRasterOverlay(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : CesiumRasterOverlay.PropertyName
	{
		public static readonly StringName Polygons = "polygons";
		public static readonly StringName InvertSelection = "invert_selection";
		public static readonly StringName ExcludeSelectedTiles = "exclude_selected_tiles";
		public static readonly StringName ValidPolygonCount = "valid_polygon_count";
	}

	public new class MethodName : CesiumRasterOverlay.MethodName
	{
		public static readonly StringName SetPolygons = "set_polygons";
		public static readonly StringName GetPolygons = "get_polygons";
		public static readonly StringName SetInvertSelection = "set_invert_selection";
		public static readonly StringName GetInvertSelection = "get_invert_selection";
		public static readonly StringName SetExcludeSelectedTiles = "set_exclude_selected_tiles";
		public static readonly StringName GetExcludeSelectedTiles = "get_exclude_selected_tiles";
		public static readonly StringName GetValidPolygonCount = "get_valid_polygon_count";
	}

	public new class SignalName : CesiumRasterOverlay.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumPolygonRasterOverlay";

	#region Properties

	public Godot.Collections.Array Polygons
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.Polygons);
		set => _object.Set(PropertyName.Polygons, value);
	}

	public bool InvertSelection
	{
		get => (bool)_object.Get(PropertyName.InvertSelection);
		set => _object.Set(PropertyName.InvertSelection, value);
	}

	public bool ExcludeSelectedTiles
	{
		get => (bool)_object.Get(PropertyName.ExcludeSelectedTiles);
		set => _object.Set(PropertyName.ExcludeSelectedTiles, value);
	}

	public int ValidPolygonCount
	{
		get => (int)_object.Get(PropertyName.ValidPolygonCount);
	}

	#endregion

	#region Methods

	public void SetPolygons(Godot.Collections.Array @polygons)
	{
		_object.Call(MethodName.SetPolygons, @polygons);
	}

	public Godot.Collections.Array GetPolygons()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetPolygons);
	}

	public void SetInvertSelection(bool @invert)
	{
		_object.Call(MethodName.SetInvertSelection, @invert);
	}

	public bool GetInvertSelection()
	{
		return (bool)_object.Call(MethodName.GetInvertSelection);
	}

	public void SetExcludeSelectedTiles(bool @exclude)
	{
		_object.Call(MethodName.SetExcludeSelectedTiles, @exclude);
	}

	public bool GetExcludeSelectedTiles()
	{
		return (bool)_object.Call(MethodName.GetExcludeSelectedTiles);
	}

	public int GetValidPolygonCount()
	{
		return (int)_object.Call(MethodName.GetValidPolygonCount);
	}

	#endregion
}
