// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGeocoderRequest
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumGeocoderRequest() : this(NativeName)
	{
	}
	protected CesiumGeocoderRequest(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGeocoderRequest(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumGeocoderRequest([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumGeocoderRequest self) => self?._object;
	public static implicit operator Variant(CesiumGeocoderRequest self) => self?._object;
	public static explicit operator CesiumGeocoderRequest(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName RequestId = "request_id";
		public static readonly StringName Status = "status";
		public static readonly StringName Provider = "provider";
		public static readonly StringName RequestType = "request_type";
		public static readonly StringName Query = "query";
		public static readonly StringName Result = "result";
		public static readonly StringName HttpStatusCode = "http_status_code";
		public static readonly StringName ErrorCode = "error_code";
		public static readonly StringName ErrorMessage = "error_message";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetRequestId = "get_request_id";
		public static readonly StringName GetStatus = "get_status";
		public static readonly StringName IsFinished = "is_finished";
		public static readonly StringName IsCancelled = "is_cancelled";
		public static readonly StringName GetProvider = "get_provider";
		public static readonly StringName GetRequestType = "get_request_type";
		public static readonly StringName GetQuery = "get_query";
		public static readonly StringName GetResult = "get_result";
		public static readonly StringName GetHttpStatusCode = "get_http_status_code";
		public static readonly StringName GetErrorCode = "get_error_code";
		public static readonly StringName GetErrorMessage = "get_error_message";
		public static readonly StringName Cancel = "cancel";
	}

	public class SignalName : RefCounted.SignalName
	{
		public static readonly StringName Completed = "completed";
		public static readonly StringName Failed = "failed";
		public static readonly StringName Cancelled = "cancelled";
	}

	private static readonly StringName NativeName = "CesiumGeocoderRequest";

	#region Enums

	public enum StatusEnum : long
	{
		Pending = 0L,
		Completed = 1L,
		Failed = 2L,
		Cancelled = 3L,
	}

	#endregion

	#region Properties

	public int RequestId
	{
		get => (int)_object.Get(PropertyName.RequestId);
	}

	public int Status
	{
		get => (int)_object.Get(PropertyName.Status);
	}

	public int Provider
	{
		get => (int)_object.Get(PropertyName.Provider);
	}

	public int RequestType
	{
		get => (int)_object.Get(PropertyName.RequestType);
	}

	public string Query
	{
		get => (string)_object.Get(PropertyName.Query);
	}

	public CesiumGeocoderResult Result
	{
		get => (CesiumGeocoderResult)_object.Get(PropertyName.Result);
	}

	public int HttpStatusCode
	{
		get => (int)_object.Get(PropertyName.HttpStatusCode);
	}

	public string ErrorCode
	{
		get => (string)_object.Get(PropertyName.ErrorCode);
	}

	public string ErrorMessage
	{
		get => (string)_object.Get(PropertyName.ErrorMessage);
	}

	#endregion

	#region Methods

	public int GetRequestId()
	{
		return (int)_object.Call(MethodName.GetRequestId);
	}

	public int GetStatus()
	{
		return (int)_object.Call(MethodName.GetStatus);
	}

	public bool IsFinished()
	{
		return (bool)_object.Call(MethodName.IsFinished);
	}

	public bool IsCancelled()
	{
		return (bool)_object.Call(MethodName.IsCancelled);
	}

	public int GetProvider()
	{
		return (int)_object.Call(MethodName.GetProvider);
	}

	public int GetRequestType()
	{
		return (int)_object.Call(MethodName.GetRequestType);
	}

	public string GetQuery()
	{
		return (string)_object.Call(MethodName.GetQuery);
	}

	public CesiumGeocoderResult GetResult()
	{
		return (CesiumGeocoderResult)_object.Call(MethodName.GetResult);
	}

	public int GetHttpStatusCode()
	{
		return (int)_object.Call(MethodName.GetHttpStatusCode);
	}

	public string GetErrorCode()
	{
		return (string)_object.Call(MethodName.GetErrorCode);
	}

	public string GetErrorMessage()
	{
		return (string)_object.Call(MethodName.GetErrorMessage);
	}

	public void Cancel()
	{
		_object.Call(MethodName.Cancel);
	}

	#endregion

	#region Signals

	public event Action<GodotObject> Completed
	{
		add
		{
			_object.Connect(SignalName.Completed, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.Completed, Callable.From(value));
		}
	}

	public event Action<string, string, int> Failed
	{
		add
		{
			_object.Connect(SignalName.Failed, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.Failed, Callable.From(value));
		}
	}

	public event Action Cancelled
	{
		add
		{
			_object.Connect(SignalName.Cancelled, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.Cancelled, Callable.From(value));
		}
	}

	#endregion
}
