// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumSampleHeightResult
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumSampleHeightResult() : this(NativeName)
	{
	}
	protected CesiumSampleHeightResult(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumSampleHeightResult(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumSampleHeightResult([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumSampleHeightResult self) => self?._object;
	public static implicit operator Variant(CesiumSampleHeightResult self) => self?._object;
	public static explicit operator CesiumSampleHeightResult(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName LongitudeLatitudeHeight = "longitude_latitude_height";
		public static readonly StringName LongitudeLatitudeHeightComponents = "longitude_latitude_height_components";
		public static readonly StringName SampleSuccess = "sample_success";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetLongitudeLatitudeHeight = "get_longitude_latitude_height";
		public static readonly StringName GetLongitudeLatitudeHeightComponents = "get_longitude_latitude_height_components";
		public static readonly StringName GetSampleSuccess = "get_sample_success";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumSampleHeightResult";

	#region Properties

	public Godot.Vector3 LongitudeLatitudeHeight
	{
		get => (Godot.Vector3)_object.Get(PropertyName.LongitudeLatitudeHeight);
	}

	public double[] LongitudeLatitudeHeightComponents
	{
		get => (double[])_object.Get(PropertyName.LongitudeLatitudeHeightComponents);
	}

	public bool SampleSuccess
	{
		get => (bool)_object.Get(PropertyName.SampleSuccess);
	}

	#endregion

	#region Methods

	public Godot.Vector3 GetLongitudeLatitudeHeight()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetLongitudeLatitudeHeight);
	}

	public double[] GetLongitudeLatitudeHeightComponents()
	{
		return (double[])_object.Call(MethodName.GetLongitudeLatitudeHeightComponents);
	}

	public bool GetSampleSuccess()
	{
		return (bool)_object.Call(MethodName.GetSampleSuccess);
	}

	#endregion
}
