// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumPrimitiveFeatures
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumPrimitiveFeatures() : this(NativeName)
	{
	}
	protected CesiumPrimitiveFeatures(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumPrimitiveFeatures(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumPrimitiveFeatures([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumPrimitiveFeatures self) => self?._object;
	public static implicit operator Variant(CesiumPrimitiveFeatures self) => self?._object;
	public static explicit operator CesiumPrimitiveFeatures(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName FeatureIdSets = "feature_id_sets";
		public static readonly StringName VertexCount = "vertex_count";
		public static readonly StringName InstanceCount = "instance_count";
		public static readonly StringName FaceCount = "face_count";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetFeatureIdSets = "get_feature_id_sets";
		public static readonly StringName GetFeatureIdSetCount = "get_feature_id_set_count";
		public static readonly StringName GetFeatureIdSet = "get_feature_id_set";
		public static readonly StringName GetVertexCount = "get_vertex_count";
		public static readonly StringName GetInstanceCount = "get_instance_count";
		public static readonly StringName GetFaceCount = "get_face_count";
		public static readonly StringName GetFirstVertexFromFace = "get_first_vertex_from_face";
		public static readonly StringName GetFeatureIdFromFace = "get_feature_id_from_face";
		public static readonly StringName GetFeatureIdFromHit = "get_feature_id_from_hit";
		public static readonly StringName GetFeatureIdFromInstance = "get_feature_id_from_instance";
		public static readonly StringName GetMetadataValuesForFace = "get_metadata_values_for_face";
		public static readonly StringName GetMetadataValuesFromHit = "get_metadata_values_from_hit";
		public static readonly StringName GetMetadataValuesForInstance = "get_metadata_values_for_instance";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumPrimitiveFeatures";

	#region Properties

	public Godot.Collections.Array FeatureIdSets
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.FeatureIdSets);
	}

	public int VertexCount
	{
		get => (int)_object.Get(PropertyName.VertexCount);
	}

	public int InstanceCount
	{
		get => (int)_object.Get(PropertyName.InstanceCount);
	}

	public int FaceCount
	{
		get => (int)_object.Get(PropertyName.FaceCount);
	}

	#endregion

	#region Methods

	public Godot.Collections.Array GetFeatureIdSets()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetFeatureIdSets);
	}

	public int GetFeatureIdSetCount()
	{
		return (int)_object.Call(MethodName.GetFeatureIdSetCount);
	}

	public CesiumFeatureIdSet GetFeatureIdSet(int @index)
	{
		return (CesiumFeatureIdSet)_object.Call(MethodName.GetFeatureIdSet, @index);
	}

	public int GetVertexCount()
	{
		return (int)_object.Call(MethodName.GetVertexCount);
	}

	public int GetInstanceCount()
	{
		return (int)_object.Call(MethodName.GetInstanceCount);
	}

	public int GetFaceCount()
	{
		return (int)_object.Call(MethodName.GetFaceCount);
	}

	public int GetFirstVertexFromFace(int @face_index)
	{
		return (int)_object.Call(MethodName.GetFirstVertexFromFace, @face_index);
	}

	public int GetFeatureIdFromFace(int @face_index, int @feature_id_set_index = 0)
	{
		return (int)_object.Call(MethodName.GetFeatureIdFromFace, @face_index, @feature_id_set_index);
	}

	public int GetFeatureIdFromHit(int @face_index, Godot.Vector3 @local_position, int @feature_id_set_index = 0)
	{
		return (int)_object.Call(MethodName.GetFeatureIdFromHit, @face_index, @local_position, @feature_id_set_index);
	}

	public int GetFeatureIdFromInstance(int @instance_index, int @feature_id_set_index = 0)
	{
		return (int)_object.Call(MethodName.GetFeatureIdFromInstance, @instance_index, @feature_id_set_index);
	}

	public Godot.Collections.Dictionary GetMetadataValuesForFace(CesiumModelMetadata @model_metadata, int @face_index, int @feature_id_set_index = 0)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetMetadataValuesForFace, @model_metadata, @face_index, @feature_id_set_index);
	}

	public Godot.Collections.Dictionary GetMetadataValuesFromHit(CesiumModelMetadata @model_metadata, int @face_index, Godot.Vector3 @local_position, int @feature_id_set_index = 0)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetMetadataValuesFromHit, @model_metadata, @face_index, @local_position, @feature_id_set_index);
	}

	public Godot.Collections.Dictionary GetMetadataValuesForInstance(CesiumModelMetadata @model_metadata, int @instance_index, int @feature_id_set_index = 0)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetMetadataValuesForInstance, @model_metadata, @instance_index, @feature_id_set_index);
	}

	#endregion
}
