// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumBingMapsRasterOverlay : CesiumRasterOverlay
{
	public CesiumBingMapsRasterOverlay() : base(NativeName)
	{
	}
	protected CesiumBingMapsRasterOverlay(StringName @class) : base(@class)
	{
	}
	protected CesiumBingMapsRasterOverlay(Variant variant) : base(variant)
	{
	}
	protected CesiumBingMapsRasterOverlay([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(CesiumBingMapsRasterOverlay self) => self?._object;
	public static implicit operator Variant(CesiumBingMapsRasterOverlay self) => self?._object;
	public static explicit operator CesiumBingMapsRasterOverlay(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : CesiumRasterOverlay.PropertyName
	{
		public static readonly StringName ApiKey = "api_key";
		public static readonly StringName MapStyle = "map_style";
		public static readonly StringName Culture = "culture";
		public static readonly StringName ServiceUrl = "service_url";
	}

	public new class MethodName : CesiumRasterOverlay.MethodName
	{
		public static readonly StringName SetApiKey = "set_api_key";
		public static readonly StringName GetApiKey = "get_api_key";
		public static readonly StringName SetMapStyle = "set_map_style";
		public static readonly StringName GetMapStyle = "get_map_style";
		public static readonly StringName SetCulture = "set_culture";
		public static readonly StringName GetCulture = "get_culture";
		public static readonly StringName SetServiceUrl = "set_service_url";
		public static readonly StringName GetServiceUrl = "get_service_url";
	}

	public new class SignalName : CesiumRasterOverlay.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumBingMapsRasterOverlay";

	#region Enums

	public enum MapStyleEnum : long
	{
		Aerial = 0L,
		AerialWithLabelsOnDemand = 1L,
		RoadOnDemand = 2L,
		CanvasDark = 3L,
		CanvasLight = 4L,
		CanvasGray = 5L,
		OrdnanceSurvey = 6L,
		CollinsBart = 7L,
	}

	#endregion

	#region Properties

	public string ApiKey
	{
		get => (string)_object.Get(PropertyName.ApiKey);
		set => _object.Set(PropertyName.ApiKey, value);
	}

	public int MapStyle
	{
		get => (int)_object.Get(PropertyName.MapStyle);
		set => _object.Set(PropertyName.MapStyle, value);
	}

	public string Culture
	{
		get => (string)_object.Get(PropertyName.Culture);
		set => _object.Set(PropertyName.Culture, value);
	}

	public string ServiceUrl
	{
		get => (string)_object.Get(PropertyName.ServiceUrl);
		set => _object.Set(PropertyName.ServiceUrl, value);
	}

	#endregion

	#region Methods

	public void SetApiKey(string @value)
	{
		_object.Call(MethodName.SetApiKey, @value);
	}

	public string GetApiKey()
	{
		return (string)_object.Call(MethodName.GetApiKey);
	}

	public void SetMapStyle(int @value)
	{
		_object.Call(MethodName.SetMapStyle, @value);
	}

	public int GetMapStyle()
	{
		return (int)_object.Call(MethodName.GetMapStyle);
	}

	public void SetCulture(string @value)
	{
		_object.Call(MethodName.SetCulture, @value);
	}

	public string GetCulture()
	{
		return (string)_object.Call(MethodName.GetCulture);
	}

	public void SetServiceUrl(string @value)
	{
		_object.Call(MethodName.SetServiceUrl, @value);
	}

	public string GetServiceUrl()
	{
		return (string)_object.Call(MethodName.GetServiceUrl);
	}

	#endregion
}
