// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumEllipsoid
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public Resource NativeObject => _object;

	public CesiumEllipsoid() : this(NativeName)
	{
	}
	protected CesiumEllipsoid(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumEllipsoid(Variant variant) : this((Resource) variant)
	{
	}
	protected CesiumEllipsoid([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(CesiumEllipsoid self) => self?._object;
	public static implicit operator Variant(CesiumEllipsoid self) => self?._object;
	public static explicit operator CesiumEllipsoid(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName Radii = "radii";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName SetRadii = "set_radii";
		public static readonly StringName GetRadii = "get_radii";
		public static readonly StringName SetRadiiPrecise = "set_radii_precise";
		public static readonly StringName GetRadiiPrecise = "get_radii_precise";
		public static readonly StringName GetMaximumRadius = "get_maximum_radius";
		public static readonly StringName GetMinimumRadius = "get_minimum_radius";
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName GetRevision = "get_revision";
		public static readonly StringName LongitudeLatitudeHeightToEcefPrecise = "longitude_latitude_height_to_ecef_precise";
		public static readonly StringName EcefToLongitudeLatitudeHeightPrecise = "ecef_to_longitude_latitude_height_precise";
		public static readonly StringName ScaleToGeodeticSurfacePrecise = "scale_to_geodetic_surface_precise";
		public static readonly StringName GeodeticSurfaceNormalPrecise = "geodetic_surface_normal_precise";
		public static readonly StringName RayIntersectionPrecise = "ray_intersection_precise";
		public static readonly StringName LongitudeLatitudeHeightToEcef = "longitude_latitude_height_to_ecef";
		public static readonly StringName EcefToLongitudeLatitudeHeight = "ecef_to_longitude_latitude_height";
		public static readonly StringName ScaleToGeodeticSurface = "scale_to_geodetic_surface";
		public static readonly StringName GeodeticSurfaceNormal = "geodetic_surface_normal";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumEllipsoid";

	#region Properties

	public Godot.Vector3 Radii
	{
		get => (Godot.Vector3)_object.Get(PropertyName.Radii);
		set => _object.Set(PropertyName.Radii, value);
	}

	#endregion

	#region Methods

	public void SetRadii(Godot.Vector3 @radii)
	{
		_object.Call(MethodName.SetRadii, @radii);
	}

	public Godot.Vector3 GetRadii()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetRadii);
	}

	public void SetRadiiPrecise(double[] @radii)
	{
		_object.Call(MethodName.SetRadiiPrecise, @radii);
	}

	public double[] GetRadiiPrecise()
	{
		return (double[])_object.Call(MethodName.GetRadiiPrecise);
	}

	public float GetMaximumRadius()
	{
		return (float)_object.Call(MethodName.GetMaximumRadius);
	}

	public float GetMinimumRadius()
	{
		return (float)_object.Call(MethodName.GetMinimumRadius);
	}

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public int GetRevision()
	{
		return (int)_object.Call(MethodName.GetRevision);
	}

	public double[] LongitudeLatitudeHeightToEcefPrecise(double[] @longitude_latitude_height)
	{
		return (double[])_object.Call(MethodName.LongitudeLatitudeHeightToEcefPrecise, @longitude_latitude_height);
	}

	public double[] EcefToLongitudeLatitudeHeightPrecise(double[] @ecef)
	{
		return (double[])_object.Call(MethodName.EcefToLongitudeLatitudeHeightPrecise, @ecef);
	}

	public double[] ScaleToGeodeticSurfacePrecise(double[] @ecef)
	{
		return (double[])_object.Call(MethodName.ScaleToGeodeticSurfacePrecise, @ecef);
	}

	public double[] GeodeticSurfaceNormalPrecise(double[] @ecef)
	{
		return (double[])_object.Call(MethodName.GeodeticSurfaceNormalPrecise, @ecef);
	}

	public double[] RayIntersectionPrecise(double[] @origin_ecef, double[] @direction_ecef)
	{
		return (double[])_object.Call(MethodName.RayIntersectionPrecise, @origin_ecef, @direction_ecef);
	}

	public Godot.Vector3 LongitudeLatitudeHeightToEcef(Godot.Vector3 @longitude_latitude_height)
	{
		return (Godot.Vector3)_object.Call(MethodName.LongitudeLatitudeHeightToEcef, @longitude_latitude_height);
	}

	public Godot.Vector3 EcefToLongitudeLatitudeHeight(Godot.Vector3 @ecef)
	{
		return (Godot.Vector3)_object.Call(MethodName.EcefToLongitudeLatitudeHeight, @ecef);
	}

	public Godot.Vector3 ScaleToGeodeticSurface(Godot.Vector3 @ecef)
	{
		return (Godot.Vector3)_object.Call(MethodName.ScaleToGeodeticSurface, @ecef);
	}

	public Godot.Vector3 GeodeticSurfaceNormal(Godot.Vector3 @ecef)
	{
		return (Godot.Vector3)_object.Call(MethodName.GeodeticSurfaceNormal, @ecef);
	}

	#endregion
}
