// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumPropertyAttribute
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumPropertyAttribute() : this(NativeName)
	{
	}
	protected CesiumPropertyAttribute(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumPropertyAttribute(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumPropertyAttribute([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumPropertyAttribute self) => self?._object;
	public static implicit operator Variant(CesiumPropertyAttribute self) => self?._object;
	public static explicit operator CesiumPropertyAttribute(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Status = "status";
		public static readonly StringName StatusName = "status_name";
		public static readonly StringName AttributeName = "attribute_name";
		public static readonly StringName ClassName = "class_name";
		public static readonly StringName ElementCount = "element_count";
		public static readonly StringName Properties = "properties";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetStatus = "get_status";
		public static readonly StringName GetStatusName = "get_status_name";
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName GetAttributeName = "get_attribute_name";
		public static readonly StringName GetClassName = "get_class_name";
		public static readonly StringName GetElementCount = "get_element_count";
		public static readonly StringName GetProperties = "get_properties";
		public static readonly StringName GetPropertyNames = "get_property_names";
		public static readonly StringName FindProperty = "find_property";
		public static readonly StringName GetMetadataValuesAtIndex = "get_metadata_values_at_index";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumPropertyAttribute";

	#region Enums

	public enum StatusEnum : long
	{
		Valid = 0L,
		ErrorInvalidPropertyAttribute = 1L,
		ErrorInvalidPropertyAttributeClass = 2L,
	}

	#endregion

	#region Properties

	public int Status
	{
		get => (int)_object.Get(PropertyName.Status);
	}

	public string StatusName
	{
		get => (string)_object.Get(PropertyName.StatusName);
	}

	public string AttributeName
	{
		get => (string)_object.Get(PropertyName.AttributeName);
	}

	public string ClassName
	{
		get => (string)_object.Get(PropertyName.ClassName);
	}

	public int ElementCount
	{
		get => (int)_object.Get(PropertyName.ElementCount);
	}

	public Godot.Collections.Array Properties
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.Properties);
	}

	#endregion

	#region Methods

	public int GetStatus()
	{
		return (int)_object.Call(MethodName.GetStatus);
	}

	public string GetStatusName()
	{
		return (string)_object.Call(MethodName.GetStatusName);
	}

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public string GetAttributeName()
	{
		return (string)_object.Call(MethodName.GetAttributeName);
	}

	public string GetClassName()
	{
		return (string)_object.Call(MethodName.GetClassName);
	}

	public int GetElementCount()
	{
		return (int)_object.Call(MethodName.GetElementCount);
	}

	public Godot.Collections.Array GetProperties()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetProperties);
	}

	public Godot.Collections.Array GetPropertyNames()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetPropertyNames);
	}

	public CesiumPropertyAttributeProperty FindProperty(string @property_id)
	{
		return (CesiumPropertyAttributeProperty)_object.Call(MethodName.FindProperty, @property_id);
	}

	public Godot.Collections.Dictionary GetMetadataValuesAtIndex(int @vertex_index)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetMetadataValuesAtIndex, @vertex_index);
	}

	#endregion
}
