// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGlobeAnchor
{
	// Engine object used for calling engine methods
	protected Node _object;

	public Node NativeObject => _object;

	public CesiumGlobeAnchor() : this(NativeName)
	{
	}
	protected CesiumGlobeAnchor(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGlobeAnchor(Variant variant) : this((Node) variant)
	{
	}
	protected CesiumGlobeAnchor([NotNull] Node @object)
	{
		_object = @object;
	}

	public static implicit operator Node(CesiumGlobeAnchor self) => self?._object;
	public static implicit operator Variant(CesiumGlobeAnchor self) => self?._object;
	public static explicit operator CesiumGlobeAnchor(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node.PropertyName
	{
		public static readonly StringName TargetNodePath = "target_node_path";
		public static readonly StringName GeoreferencePath = "georeference_path";
		public static readonly StringName AdjustOrientationForGlobeWhenMoving = "adjust_orientation_for_globe_when_moving";
		public static readonly StringName AutomaticTransformSync = "automatic_transform_sync";
	}

	public class MethodName : Node.MethodName
	{
		public static readonly StringName SetTargetNodePath = "set_target_node_path";
		public static readonly StringName GetTargetNodePath = "get_target_node_path";
		public static readonly StringName SetGeoreferencePath = "set_georeference_path";
		public static readonly StringName GetGeoreferencePath = "get_georeference_path";
		public static readonly StringName SetAdjustOrientationForGlobeWhenMoving = "set_adjust_orientation_for_globe_when_moving";
		public static readonly StringName GetAdjustOrientationForGlobeWhenMoving = "get_adjust_orientation_for_globe_when_moving";
		public static readonly StringName SetAutomaticTransformSync = "set_automatic_transform_sync";
		public static readonly StringName GetAutomaticTransformSync = "get_automatic_transform_sync";
		public static readonly StringName GetTargetNode = "get_target_node";
		public static readonly StringName GetGeoreference = "get_georeference";
		public static readonly StringName IsAnchorInitialized = "is_anchor_initialized";
		public static readonly StringName TargetTransformChangedSinceLastSync = "target_transform_changed_since_last_sync";
		public static readonly StringName SyncFromTarget = "sync_from_target";
		public static readonly StringName SyncToTarget = "sync_to_target";
		public static readonly StringName GetEcefPositionPrecise = "get_ecef_position_precise";
		public static readonly StringName SetEcefPositionPrecise = "set_ecef_position_precise";
		public static readonly StringName GetLongitudeLatitudeHeightPrecise = "get_longitude_latitude_height_precise";
		public static readonly StringName SetLongitudeLatitudeHeightPrecise = "set_longitude_latitude_height_precise";
		public static readonly StringName GetAnchorToEcefMatrixPrecise = "get_anchor_to_ecef_matrix_precise";
		public static readonly StringName SetAnchorToEcefMatrixPrecise = "set_anchor_to_ecef_matrix_precise";
		public static readonly StringName GetAnchorRevision = "get_anchor_revision";
	}

	public class SignalName : Node.SignalName
	{
		public static readonly StringName AnchorChanged = "anchor_changed";
	}

	private static readonly StringName NativeName = "CesiumGlobeAnchor";

	#region Properties

	public Godot.NodePath TargetNodePath
	{
		get => (Godot.NodePath)_object.Get(PropertyName.TargetNodePath);
		set => _object.Set(PropertyName.TargetNodePath, value);
	}

	public Godot.NodePath GeoreferencePath
	{
		get => (Godot.NodePath)_object.Get(PropertyName.GeoreferencePath);
		set => _object.Set(PropertyName.GeoreferencePath, value);
	}

	public bool AdjustOrientationForGlobeWhenMoving
	{
		get => (bool)_object.Get(PropertyName.AdjustOrientationForGlobeWhenMoving);
		set => _object.Set(PropertyName.AdjustOrientationForGlobeWhenMoving, value);
	}

	public bool AutomaticTransformSync
	{
		get => (bool)_object.Get(PropertyName.AutomaticTransformSync);
		set => _object.Set(PropertyName.AutomaticTransformSync, value);
	}

	#endregion

	#region Methods

	public void SetTargetNodePath(Godot.NodePath @path)
	{
		_object.Call(MethodName.SetTargetNodePath, @path);
	}

	public Godot.NodePath GetTargetNodePath()
	{
		return (Godot.NodePath)_object.Call(MethodName.GetTargetNodePath);
	}

	public void SetGeoreferencePath(Godot.NodePath @path)
	{
		_object.Call(MethodName.SetGeoreferencePath, @path);
	}

	public Godot.NodePath GetGeoreferencePath()
	{
		return (Godot.NodePath)_object.Call(MethodName.GetGeoreferencePath);
	}

	public void SetAdjustOrientationForGlobeWhenMoving(bool @value)
	{
		_object.Call(MethodName.SetAdjustOrientationForGlobeWhenMoving, @value);
	}

	public bool GetAdjustOrientationForGlobeWhenMoving()
	{
		return (bool)_object.Call(MethodName.GetAdjustOrientationForGlobeWhenMoving);
	}

	public void SetAutomaticTransformSync(bool @value)
	{
		_object.Call(MethodName.SetAutomaticTransformSync, @value);
	}

	public bool GetAutomaticTransformSync()
	{
		return (bool)_object.Call(MethodName.GetAutomaticTransformSync);
	}

	public Node3D GetTargetNode()
	{
		return (Node3D)_object.Call(MethodName.GetTargetNode);
	}

	public CesiumGeoreference GetGeoreference()
	{
		return (CesiumGeoreference)_object.Call(MethodName.GetGeoreference);
	}

	public bool IsAnchorInitialized()
	{
		return (bool)_object.Call(MethodName.IsAnchorInitialized);
	}

	public bool TargetTransformChangedSinceLastSync()
	{
		return (bool)_object.Call(MethodName.TargetTransformChangedSinceLastSync);
	}

	public bool SyncFromTarget()
	{
		return (bool)_object.Call(MethodName.SyncFromTarget);
	}

	public bool SyncToTarget()
	{
		return (bool)_object.Call(MethodName.SyncToTarget);
	}

	public double[] GetEcefPositionPrecise()
	{
		return (double[])_object.Call(MethodName.GetEcefPositionPrecise);
	}

	public bool SetEcefPositionPrecise(double[] @ecef)
	{
		return (bool)_object.Call(MethodName.SetEcefPositionPrecise, @ecef);
	}

	public double[] GetLongitudeLatitudeHeightPrecise()
	{
		return (double[])_object.Call(MethodName.GetLongitudeLatitudeHeightPrecise);
	}

	public bool SetLongitudeLatitudeHeightPrecise(double[] @longitude_latitude_height)
	{
		return (bool)_object.Call(MethodName.SetLongitudeLatitudeHeightPrecise, @longitude_latitude_height);
	}

	public double[] GetAnchorToEcefMatrixPrecise()
	{
		return (double[])_object.Call(MethodName.GetAnchorToEcefMatrixPrecise);
	}

	public bool SetAnchorToEcefMatrixPrecise(double[] @matrix)
	{
		return (bool)_object.Call(MethodName.SetAnchorToEcefMatrixPrecise, @matrix);
	}

	public int GetAnchorRevision()
	{
		return (int)_object.Call(MethodName.GetAnchorRevision);
	}

	#endregion

	#region Signals

	public event Action<int> AnchorChanged
	{
		add
		{
			_object.Connect(SignalName.AnchorChanged, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.AnchorChanged, Callable.From(value));
		}
	}

	#endregion
}
