// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumIonEditorSession
{
	// Engine object used for calling engine methods
	protected Node _object;

	public Node NativeObject => _object;

	public CesiumIonEditorSession() : this(NativeName)
	{
	}
	protected CesiumIonEditorSession(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumIonEditorSession(Variant variant) : this((Node) variant)
	{
	}
	protected CesiumIonEditorSession([NotNull] Node @object)
	{
		_object = @object;
	}

	public static implicit operator Node(CesiumIonEditorSession self) => self?._object;
	public static implicit operator Variant(CesiumIonEditorSession self) => self?._object;
	public static explicit operator CesiumIonEditorSession(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node.PropertyName
	{
		public static readonly StringName State = "state";
		public static readonly StringName IsConnected = "is_connected";
		public static readonly StringName IsConnecting = "is_connecting";
		public static readonly StringName ErrorMessage = "error_message";
		public static readonly StringName ProfileName = "profile_name";
		public static readonly StringName ApiUrl = "api_url";
		public static readonly StringName ServerUrl = "server_url";
		public static readonly StringName OauthApplicationId = "oauth_application_id";
		public static readonly StringName OauthRedirectPath = "oauth_redirect_path";
		public static readonly StringName AuthorizationUrlHandler = "authorization_url_handler";
		public static readonly StringName SecureStorageAvailable = "secure_storage_available";
		public static readonly StringName SecureStorageBackend = "secure_storage_backend";
		public static readonly StringName SecureStorageError = "secure_storage_error";
	}

	public class MethodName : Node.MethodName
	{
		public static readonly StringName ConnectToIon = "connect_to_ion";
		public static readonly StringName ResumeSession = "resume_session";
		public static readonly StringName CancelConnection = "cancel_connection";
		public static readonly StringName SignOut = "sign_out";
		public static readonly StringName RequestAssets = "request_assets";
		public static readonly StringName RequestTokens = "request_tokens";
		public static readonly StringName CreateToken = "create_token";
		public static readonly StringName GetState = "get_state";
		public static readonly StringName GetIsConnected = "get_is_connected";
		public static readonly StringName GetIsConnecting = "get_is_connecting";
		public static readonly StringName GetErrorMessage = "get_error_message";
		public static readonly StringName GetProfileName = "get_profile_name";
		public static readonly StringName GetApiUrl = "get_api_url";
		public static readonly StringName SetApiUrl = "set_api_url";
		public static readonly StringName GetServerUrl = "get_server_url";
		public static readonly StringName SetServerUrl = "set_server_url";
		public static readonly StringName GetOauthApplicationId = "get_oauth_application_id";
		public static readonly StringName SetOauthApplicationId = "set_oauth_application_id";
		public static readonly StringName GetOauthRedirectPath = "get_oauth_redirect_path";
		public static readonly StringName SetOauthRedirectPath = "set_oauth_redirect_path";
		public static readonly StringName GetAuthorizationUrlHandler = "get_authorization_url_handler";
		public static readonly StringName SetAuthorizationUrlHandler = "set_authorization_url_handler";
		public static readonly StringName GetSecureStorageAvailable = "get_secure_storage_available";
		public static readonly StringName GetSecureStorageBackend = "get_secure_storage_backend";
		public static readonly StringName GetSecureStorageError = "get_secure_storage_error";
	}

	public class SignalName : Node.SignalName
	{
		public static readonly StringName StateChanged = "state_changed";
		public static readonly StringName Connected = "connected";
		public static readonly StringName Disconnected = "disconnected";
		public static readonly StringName AuthorizationFailed = "authorization_failed";
		public static readonly StringName AssetsReceived = "assets_received";
		public static readonly StringName TokensReceived = "tokens_received";
		public static readonly StringName TokenCreated = "token_created";
		public static readonly StringName RequestFailed = "request_failed";
		public static readonly StringName OperationCompleted = "operation_completed";
	}

	private static readonly StringName NativeName = "CesiumIonEditorSession";

	#region Enums

	public enum StateEnum : long
	{
		Disconnected = 0L,
		Resuming = 1L,
		Connecting = 2L,
		Connected = 3L,
		Error = 4L,
	}

	#endregion

	#region Properties

	public int State
	{
		get => (int)_object.Get(PropertyName.State);
	}

	public bool IsConnected
	{
		get => (bool)_object.Get(PropertyName.IsConnected);
	}

	public bool IsConnecting
	{
		get => (bool)_object.Get(PropertyName.IsConnecting);
	}

	public string ErrorMessage
	{
		get => (string)_object.Get(PropertyName.ErrorMessage);
	}

	public string ProfileName
	{
		get => (string)_object.Get(PropertyName.ProfileName);
	}

	public string ApiUrl
	{
		get => (string)_object.Get(PropertyName.ApiUrl);
		set => _object.Set(PropertyName.ApiUrl, value);
	}

	public string ServerUrl
	{
		get => (string)_object.Get(PropertyName.ServerUrl);
		set => _object.Set(PropertyName.ServerUrl, value);
	}

	public int OauthApplicationId
	{
		get => (int)_object.Get(PropertyName.OauthApplicationId);
		set => _object.Set(PropertyName.OauthApplicationId, value);
	}

	public string OauthRedirectPath
	{
		get => (string)_object.Get(PropertyName.OauthRedirectPath);
		set => _object.Set(PropertyName.OauthRedirectPath, value);
	}

	public Godot.Callable AuthorizationUrlHandler
	{
		get => (Godot.Callable)_object.Get(PropertyName.AuthorizationUrlHandler);
		set => _object.Set(PropertyName.AuthorizationUrlHandler, value);
	}

	public bool SecureStorageAvailable
	{
		get => (bool)_object.Get(PropertyName.SecureStorageAvailable);
	}

	public string SecureStorageBackend
	{
		get => (string)_object.Get(PropertyName.SecureStorageBackend);
	}

	public string SecureStorageError
	{
		get => (string)_object.Get(PropertyName.SecureStorageError);
	}

	#endregion

	#region Methods

	public void ConnectToIon()
	{
		_object.Call(MethodName.ConnectToIon);
	}

	public void ResumeSession()
	{
		_object.Call(MethodName.ResumeSession);
	}

	public void CancelConnection()
	{
		_object.Call(MethodName.CancelConnection);
	}

	public void SignOut()
	{
		_object.Call(MethodName.SignOut);
	}

	public void RequestAssets()
	{
		_object.Call(MethodName.RequestAssets);
	}

	public void RequestTokens()
	{
		_object.Call(MethodName.RequestTokens);
	}

	public void CreateToken(string @name, string[] @scopes)
	{
		_object.Call(MethodName.CreateToken, @name, @scopes);
	}

	public int GetState()
	{
		return (int)_object.Call(MethodName.GetState);
	}

	public bool GetIsConnected()
	{
		return (bool)_object.Call(MethodName.GetIsConnected);
	}

	public bool GetIsConnecting()
	{
		return (bool)_object.Call(MethodName.GetIsConnecting);
	}

	public string GetErrorMessage()
	{
		return (string)_object.Call(MethodName.GetErrorMessage);
	}

	public string GetProfileName()
	{
		return (string)_object.Call(MethodName.GetProfileName);
	}

	public string GetApiUrl()
	{
		return (string)_object.Call(MethodName.GetApiUrl);
	}

	public void SetApiUrl(string @value)
	{
		_object.Call(MethodName.SetApiUrl, @value);
	}

	public string GetServerUrl()
	{
		return (string)_object.Call(MethodName.GetServerUrl);
	}

	public void SetServerUrl(string @value)
	{
		_object.Call(MethodName.SetServerUrl, @value);
	}

	public int GetOauthApplicationId()
	{
		return (int)_object.Call(MethodName.GetOauthApplicationId);
	}

	public void SetOauthApplicationId(int @value)
	{
		_object.Call(MethodName.SetOauthApplicationId, @value);
	}

	public string GetOauthRedirectPath()
	{
		return (string)_object.Call(MethodName.GetOauthRedirectPath);
	}

	public void SetOauthRedirectPath(string @value)
	{
		_object.Call(MethodName.SetOauthRedirectPath, @value);
	}

	public Godot.Callable GetAuthorizationUrlHandler()
	{
		return (Godot.Callable)_object.Call(MethodName.GetAuthorizationUrlHandler);
	}

	public void SetAuthorizationUrlHandler(Godot.Callable @value)
	{
		_object.Call(MethodName.SetAuthorizationUrlHandler, @value);
	}

	public bool GetSecureStorageAvailable()
	{
		return (bool)_object.Call(MethodName.GetSecureStorageAvailable);
	}

	public string GetSecureStorageBackend()
	{
		return (string)_object.Call(MethodName.GetSecureStorageBackend);
	}

	public string GetSecureStorageError()
	{
		return (string)_object.Call(MethodName.GetSecureStorageError);
	}

	#endregion

	#region Signals

	public event Action<int> StateChanged
	{
		add
		{
			_object.Connect(SignalName.StateChanged, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.StateChanged, Callable.From(value));
		}
	}

	public event Action<string> Connected
	{
		add
		{
			_object.Connect(SignalName.Connected, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.Connected, Callable.From(value));
		}
	}

	public event Action Disconnected
	{
		add
		{
			_object.Connect(SignalName.Disconnected, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.Disconnected, Callable.From(value));
		}
	}

	public event Action<string> AuthorizationFailed
	{
		add
		{
			_object.Connect(SignalName.AuthorizationFailed, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.AuthorizationFailed, Callable.From(value));
		}
	}

	public event Action<Godot.Collections.Array> AssetsReceived
	{
		add
		{
			_object.Connect(SignalName.AssetsReceived, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.AssetsReceived, Callable.From(value));
		}
	}

	public event Action<Godot.Collections.Array> TokensReceived
	{
		add
		{
			_object.Connect(SignalName.TokensReceived, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.TokensReceived, Callable.From(value));
		}
	}

	public event Action<Godot.Collections.Dictionary> TokenCreated
	{
		add
		{
			_object.Connect(SignalName.TokenCreated, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.TokenCreated, Callable.From(value));
		}
	}

	public event Action<string, string> RequestFailed
	{
		add
		{
			_object.Connect(SignalName.RequestFailed, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.RequestFailed, Callable.From(value));
		}
	}

	public event Action<string, bool, Variant, string> OperationCompleted
	{
		add
		{
			_object.Connect(SignalName.OperationCompleted, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.OperationCompleted, Callable.From(value));
		}
	}

	#endregion
}
