// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumPropertyTextureProperty
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumPropertyTextureProperty() : this(NativeName)
	{
	}
	protected CesiumPropertyTextureProperty(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumPropertyTextureProperty(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumPropertyTextureProperty([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumPropertyTextureProperty self) => self?._object;
	public static implicit operator Variant(CesiumPropertyTextureProperty self) => self?._object;
	public static explicit operator CesiumPropertyTextureProperty(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Status = "status";
		public static readonly StringName StatusName = "status_name";
		public static readonly StringName PropertyId = "property_id";
		public static readonly StringName ValueType = "value_type";
		public static readonly StringName ComponentType = "component_type";
		public static readonly StringName EnumType = "enum_type";
		public static readonly StringName IsArray = "is_array";
		public static readonly StringName Normalized = "normalized";
		public static readonly StringName FixedArrayCount = "fixed_array_count";
		public static readonly StringName TextureCoordinateSetIndex = "texture_coordinate_set_index";
		public static readonly StringName Channels = "channels";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetStatus = "get_status";
		public static readonly StringName GetStatusName = "get_status_name";
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName GetPropertyId = "get_property_id";
		public static readonly StringName GetValueType = "get_value_type";
		public static readonly StringName GetComponentType = "get_component_type";
		public static readonly StringName GetEnumType = "get_enum_type";
		public static readonly StringName GetIsArray = "get_is_array";
		public static readonly StringName GetNormalized = "get_normalized";
		public static readonly StringName GetFixedArrayCount = "get_fixed_array_count";
		public static readonly StringName GetTextureCoordinateSetIndex = "get_texture_coordinate_set_index";
		public static readonly StringName GetChannels = "get_channels";
		public static readonly StringName GetSamplerDetails = "get_sampler_details";
		public static readonly StringName GetTextureTransformDetails = "get_texture_transform_details";
		public static readonly StringName GetValueTransformDetails = "get_value_transform_details";
		public static readonly StringName GetValue = "get_value";
		public static readonly StringName GetRawValue = "get_raw_value";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumPropertyTextureProperty";

	#region Enums

	public enum StatusEnum : long
	{
		Valid = 0L,
		EmptyPropertyWithDefault = 1L,
		ErrorInvalidProperty = 2L,
		ErrorInvalidPropertyData = 3L,
		ErrorUnsupportedProperty = 4L,
	}

	#endregion

	#region Properties

	public int Status
	{
		get => (int)_object.Get(PropertyName.Status);
	}

	public string StatusName
	{
		get => (string)_object.Get(PropertyName.StatusName);
	}

	public string PropertyId
	{
		get => (string)_object.Get(PropertyName.PropertyId);
	}

	public string ValueType
	{
		get => (string)_object.Get(PropertyName.ValueType);
	}

	public string ComponentType
	{
		get => (string)_object.Get(PropertyName.ComponentType);
	}

	public string EnumType
	{
		get => (string)_object.Get(PropertyName.EnumType);
	}

	public bool IsArray
	{
		get => (bool)_object.Get(PropertyName.IsArray);
	}

	public bool Normalized
	{
		get => (bool)_object.Get(PropertyName.Normalized);
	}

	public int FixedArrayCount
	{
		get => (int)_object.Get(PropertyName.FixedArrayCount);
	}

	public int TextureCoordinateSetIndex
	{
		get => (int)_object.Get(PropertyName.TextureCoordinateSetIndex);
	}

	public Godot.Collections.Array Channels
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.Channels);
	}

	#endregion

	#region Methods

	public int GetStatus()
	{
		return (int)_object.Call(MethodName.GetStatus);
	}

	public string GetStatusName()
	{
		return (string)_object.Call(MethodName.GetStatusName);
	}

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public string GetPropertyId()
	{
		return (string)_object.Call(MethodName.GetPropertyId);
	}

	public string GetValueType()
	{
		return (string)_object.Call(MethodName.GetValueType);
	}

	public string GetComponentType()
	{
		return (string)_object.Call(MethodName.GetComponentType);
	}

	public string GetEnumType()
	{
		return (string)_object.Call(MethodName.GetEnumType);
	}

	public bool GetIsArray()
	{
		return (bool)_object.Call(MethodName.GetIsArray);
	}

	public bool GetNormalized()
	{
		return (bool)_object.Call(MethodName.GetNormalized);
	}

	public int GetFixedArrayCount()
	{
		return (int)_object.Call(MethodName.GetFixedArrayCount);
	}

	public int GetTextureCoordinateSetIndex()
	{
		return (int)_object.Call(MethodName.GetTextureCoordinateSetIndex);
	}

	public Godot.Collections.Array GetChannels()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetChannels);
	}

	public Godot.Collections.Dictionary GetSamplerDetails()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetSamplerDetails);
	}

	public Godot.Collections.Dictionary GetTextureTransformDetails()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetTextureTransformDetails);
	}

	public Godot.Collections.Dictionary GetValueTransformDetails()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetValueTransformDetails);
	}

	public Variant GetValue(Godot.Vector2 @texture_coordinates)
	{
		return (Variant)_object.Call(MethodName.GetValue, @texture_coordinates);
	}

	public Variant GetRawValue(Godot.Vector2 @texture_coordinates)
	{
		return (Variant)_object.Call(MethodName.GetRawValue, @texture_coordinates);
	}

	#endregion
}
