// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumMetadataEnum
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumMetadataEnum() : this(NativeName)
	{
	}
	protected CesiumMetadataEnum(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumMetadataEnum(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumMetadataEnum([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumMetadataEnum self) => self?._object;
	public static implicit operator Variant(CesiumMetadataEnum self) => self?._object;
	public static explicit operator CesiumMetadataEnum(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName EnumId = "enum_id";
		public static readonly StringName EnumName = "enum_name";
		public static readonly StringName Description = "description";
		public static readonly StringName ValueType = "value_type";
		public static readonly StringName Values = "values";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetEnumId = "get_enum_id";
		public static readonly StringName GetEnumName = "get_enum_name";
		public static readonly StringName GetDescription = "get_description";
		public static readonly StringName GetValueType = "get_value_type";
		public static readonly StringName GetValueCount = "get_value_count";
		public static readonly StringName GetValues = "get_values";
		public static readonly StringName HasValue = "has_value";
		public static readonly StringName GetNameForValue = "get_name_for_value";
		public static readonly StringName GetValueDetails = "get_value_details";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumMetadataEnum";

	#region Properties

	public string EnumId
	{
		get => (string)_object.Get(PropertyName.EnumId);
	}

	public string EnumName
	{
		get => (string)_object.Get(PropertyName.EnumName);
	}

	public string Description
	{
		get => (string)_object.Get(PropertyName.Description);
	}

	public string ValueType
	{
		get => (string)_object.Get(PropertyName.ValueType);
	}

	public Godot.Collections.Array Values
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.Values);
	}

	#endregion

	#region Methods

	public string GetEnumId()
	{
		return (string)_object.Call(MethodName.GetEnumId);
	}

	public string GetEnumName()
	{
		return (string)_object.Call(MethodName.GetEnumName);
	}

	public string GetDescription()
	{
		return (string)_object.Call(MethodName.GetDescription);
	}

	public string GetValueType()
	{
		return (string)_object.Call(MethodName.GetValueType);
	}

	public int GetValueCount()
	{
		return (int)_object.Call(MethodName.GetValueCount);
	}

	public Godot.Collections.Array GetValues()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetValues);
	}

	public bool HasValue(int @value)
	{
		return (bool)_object.Call(MethodName.HasValue, @value);
	}

	public string GetNameForValue(int @value)
	{
		return (string)_object.Call(MethodName.GetNameForValue, @value);
	}

	public Godot.Collections.Dictionary GetValueDetails(int @value)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetValueDetails, @value);
	}

	#endregion
}
