// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGDConfig
{
	// Engine object used for calling engine methods
	protected Node3D _object;

	public Node3D NativeObject => _object;

	public CesiumGDConfig() : this(NativeName)
	{
	}
	protected CesiumGDConfig(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGDConfig(Variant variant) : this((Node3D) variant)
	{
	}
	protected CesiumGDConfig([NotNull] Node3D @object)
	{
		_object = @object;
	}

	public static implicit operator Node3D(CesiumGDConfig self) => self?._object;
	public static implicit operator Variant(CesiumGDConfig self) => self?._object;
	public static explicit operator CesiumGDConfig(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node3D.PropertyName
	{
		public static readonly StringName AccessToken = "accessToken";
	}

	public class MethodName : Node3D.MethodName
	{
		public static readonly StringName GetAccessToken = "get_access_token";
		public static readonly StringName SetAccessToken = "set_access_token";
		public static readonly StringName GetSingleton = "get_singleton";
	}

	public class SignalName : Node3D.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumGDConfig";

	#region Properties

	public string AccessToken
	{
		get => (string)_object.Get(PropertyName.AccessToken);
		set => _object.Set(PropertyName.AccessToken, value);
	}

	#endregion

	#region Methods

	public string GetAccessToken()
	{
		return (string)_object.Call(MethodName.GetAccessToken);
	}

	public void SetAccessToken(string @accessToken)
	{
		_object.Call(MethodName.SetAccessToken, @accessToken);
	}

	public static CesiumGDConfig GetSingleton(Node @baseNode)
	{
		return (CesiumGDConfig)ClassDB.ClassCallStatic(NativeName, MethodName.GetSingleton, @baseNode);
	}

	#endregion
}
