// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumTileExclusionContext
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumTileExclusionContext() : this(NativeName)
	{
	}
	protected CesiumTileExclusionContext(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumTileExclusionContext(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumTileExclusionContext([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumTileExclusionContext self) => self?._object;
	public static implicit operator Variant(CesiumTileExclusionContext self) => self?._object;
	public static explicit operator CesiumTileExclusionContext(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName TileId = "tile_id";
		public static readonly StringName Depth = "depth";
		public static readonly StringName ChildCount = "child_count";
		public static readonly StringName GeometricError = "geometric_error";
		public static readonly StringName RefineMode = "refine_mode";
		public static readonly StringName RefineModeName = "refine_mode_name";
		public static readonly StringName TileBounds = "tile_bounds";
		public static readonly StringName TileTransformComponents = "tile_transform_components";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetTileId = "get_tile_id";
		public static readonly StringName GetDepth = "get_depth";
		public static readonly StringName GetChildCount = "get_child_count";
		public static readonly StringName GetGeometricError = "get_geometric_error";
		public static readonly StringName GetRefineMode = "get_refine_mode";
		public static readonly StringName GetRefineModeName = "get_refine_mode_name";
		public static readonly StringName GetTileBounds = "get_tile_bounds";
		public static readonly StringName GetTileTransformComponents = "get_tile_transform_components";
		public static readonly StringName ToDictionary = "to_dictionary";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumTileExclusionContext";

	#region Properties

	public string TileId
	{
		get => (string)_object.Get(PropertyName.TileId);
	}

	public int Depth
	{
		get => (int)_object.Get(PropertyName.Depth);
	}

	public int ChildCount
	{
		get => (int)_object.Get(PropertyName.ChildCount);
	}

	public float GeometricError
	{
		get => (float)_object.Get(PropertyName.GeometricError);
	}

	public int RefineMode
	{
		get => (int)_object.Get(PropertyName.RefineMode);
	}

	public string RefineModeName
	{
		get => (string)_object.Get(PropertyName.RefineModeName);
	}

	public GodotObject TileBounds
	{
		get => (GodotObject)_object.Get(PropertyName.TileBounds);
	}

	public double[] TileTransformComponents
	{
		get => (double[])_object.Get(PropertyName.TileTransformComponents);
	}

	#endregion

	#region Methods

	public string GetTileId()
	{
		return (string)_object.Call(MethodName.GetTileId);
	}

	public int GetDepth()
	{
		return (int)_object.Call(MethodName.GetDepth);
	}

	public int GetChildCount()
	{
		return (int)_object.Call(MethodName.GetChildCount);
	}

	public float GetGeometricError()
	{
		return (float)_object.Call(MethodName.GetGeometricError);
	}

	public int GetRefineMode()
	{
		return (int)_object.Call(MethodName.GetRefineMode);
	}

	public string GetRefineModeName()
	{
		return (string)_object.Call(MethodName.GetRefineModeName);
	}

	public CesiumBoundingVolume GetTileBounds()
	{
		return (CesiumBoundingVolume)_object.Call(MethodName.GetTileBounds);
	}

	public double[] GetTileTransformComponents()
	{
		return (double[])_object.Call(MethodName.GetTileTransformComponents);
	}

	public Godot.Collections.Dictionary ToDictionary()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.ToDictionary);
	}

	#endregion
}
