// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGoogleMapTilesRasterOverlay : CesiumRasterOverlay
{
	public CesiumGoogleMapTilesRasterOverlay() : base(NativeName)
	{
	}
	protected CesiumGoogleMapTilesRasterOverlay(StringName @class) : base(@class)
	{
	}
	protected CesiumGoogleMapTilesRasterOverlay(Variant variant) : base(variant)
	{
	}
	protected CesiumGoogleMapTilesRasterOverlay([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(CesiumGoogleMapTilesRasterOverlay self) => self?._object;
	public static implicit operator Variant(CesiumGoogleMapTilesRasterOverlay self) => self?._object;
	public static explicit operator CesiumGoogleMapTilesRasterOverlay(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : CesiumRasterOverlay.PropertyName
	{
		public static readonly StringName ApiKey = "api_key";
		public static readonly StringName MapType = "map_type";
		public static readonly StringName Language = "language";
		public static readonly StringName Region = "region";
		public static readonly StringName ImageFormat = "image_format";
		public static new readonly StringName Scale = "scale";
		public static readonly StringName HighDpi = "high_dpi";
		public static readonly StringName LayerTypes = "layer_types";
		public static readonly StringName Styles = "styles";
		public static readonly StringName Overlay = "overlay";
		public static readonly StringName ApiBaseUrl = "api_base_url";
		public static readonly StringName LastStyleErrors = "last_style_errors";
	}

	public new class MethodName : CesiumRasterOverlay.MethodName
	{
		public static readonly StringName SetApiKey = "set_api_key";
		public static readonly StringName GetApiKey = "get_api_key";
		public static readonly StringName SetMapType = "set_map_type";
		public static readonly StringName GetMapType = "get_map_type";
		public static readonly StringName SetLanguage = "set_language";
		public static readonly StringName GetLanguage = "get_language";
		public static readonly StringName SetRegion = "set_region";
		public static readonly StringName GetRegion = "get_region";
		public static readonly StringName SetImageFormat = "set_image_format";
		public static readonly StringName GetImageFormat = "get_image_format";
		public static readonly StringName SetHighDpi = "set_high_dpi";
		public static readonly StringName GetHighDpi = "get_high_dpi";
		public static readonly StringName SetLayerTypes = "set_layer_types";
		public static readonly StringName GetLayerTypes = "get_layer_types";
		public static readonly StringName SetStyles = "set_styles";
		public static readonly StringName GetStyles = "get_styles";
		public static readonly StringName SetOverlay = "set_overlay";
		public static readonly StringName GetOverlay = "get_overlay";
		public static readonly StringName SetApiBaseUrl = "set_api_base_url";
		public static readonly StringName GetApiBaseUrl = "get_api_base_url";
		public static readonly StringName GetLastStyleErrors = "get_last_style_errors";
	}

	public new class SignalName : CesiumRasterOverlay.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumGoogleMapTilesRasterOverlay";

	#region Enums

	public enum MapTypeEnum : long
	{
		Satellite = 0L,
		Roadmap = 1L,
		Terrain = 2L,
	}

	public enum ImageFormatEnum : long
	{
		Automatic = 0L,
		Png = 1L,
		Jpeg = 2L,
	}

	public enum ScaleEnum : long
	{
		Value1x = 0L,
		Value2x = 1L,
		Value4x = 2L,
	}

	public enum LayerType : long
	{
		Roadmap = 1L,
		StreetView = 2L,
		Traffic = 4L,
	}

	#endregion

	#region Properties

	public string ApiKey
	{
		get => (string)_object.Get(PropertyName.ApiKey);
		set => _object.Set(PropertyName.ApiKey, value);
	}

	public int MapType
	{
		get => (int)_object.Get(PropertyName.MapType);
		set => _object.Set(PropertyName.MapType, value);
	}

	public string Language
	{
		get => (string)_object.Get(PropertyName.Language);
		set => _object.Set(PropertyName.Language, value);
	}

	public string Region
	{
		get => (string)_object.Get(PropertyName.Region);
		set => _object.Set(PropertyName.Region, value);
	}

	public int ImageFormat
	{
		get => (int)_object.Get(PropertyName.ImageFormat);
		set => _object.Set(PropertyName.ImageFormat, value);
	}

	public int Scale
	{
		get => (int)_object.Get(PropertyName.Scale);
		set => _object.Set(PropertyName.Scale, value);
	}

	public bool HighDpi
	{
		get => (bool)_object.Get(PropertyName.HighDpi);
		set => _object.Set(PropertyName.HighDpi, value);
	}

	public int LayerTypes
	{
		get => (int)_object.Get(PropertyName.LayerTypes);
		set => _object.Set(PropertyName.LayerTypes, value);
	}

	public string[] Styles
	{
		get => (string[])_object.Get(PropertyName.Styles);
		set => _object.Set(PropertyName.Styles, value);
	}

	public bool Overlay
	{
		get => (bool)_object.Get(PropertyName.Overlay);
		set => _object.Set(PropertyName.Overlay, value);
	}

	public string ApiBaseUrl
	{
		get => (string)_object.Get(PropertyName.ApiBaseUrl);
		set => _object.Set(PropertyName.ApiBaseUrl, value);
	}

	public string[] LastStyleErrors
	{
		get => (string[])_object.Get(PropertyName.LastStyleErrors);
	}

	#endregion

	#region Methods

	public void SetApiKey(string @value)
	{
		_object.Call(MethodName.SetApiKey, @value);
	}

	public string GetApiKey()
	{
		return (string)_object.Call(MethodName.GetApiKey);
	}

	public void SetMapType(int @value)
	{
		_object.Call(MethodName.SetMapType, @value);
	}

	public int GetMapType()
	{
		return (int)_object.Call(MethodName.GetMapType);
	}

	public void SetLanguage(string @value)
	{
		_object.Call(MethodName.SetLanguage, @value);
	}

	public string GetLanguage()
	{
		return (string)_object.Call(MethodName.GetLanguage);
	}

	public void SetRegion(string @value)
	{
		_object.Call(MethodName.SetRegion, @value);
	}

	public string GetRegion()
	{
		return (string)_object.Call(MethodName.GetRegion);
	}

	public void SetImageFormat(int @value)
	{
		_object.Call(MethodName.SetImageFormat, @value);
	}

	public int GetImageFormat()
	{
		return (int)_object.Call(MethodName.GetImageFormat);
	}

	public void SetScale(int @value)
	{
		_object.Call(MethodName.SetScale, @value);
	}

	public int GetScale()
	{
		return (int)_object.Call(MethodName.GetScale);
	}

	public void SetHighDpi(bool @value)
	{
		_object.Call(MethodName.SetHighDpi, @value);
	}

	public bool GetHighDpi()
	{
		return (bool)_object.Call(MethodName.GetHighDpi);
	}

	public void SetLayerTypes(int @value)
	{
		_object.Call(MethodName.SetLayerTypes, @value);
	}

	public int GetLayerTypes()
	{
		return (int)_object.Call(MethodName.GetLayerTypes);
	}

	public void SetStyles(string[] @value)
	{
		_object.Call(MethodName.SetStyles, @value);
	}

	public string[] GetStyles()
	{
		return (string[])_object.Call(MethodName.GetStyles);
	}

	public void SetOverlay(bool @value)
	{
		_object.Call(MethodName.SetOverlay, @value);
	}

	public bool GetOverlay()
	{
		return (bool)_object.Call(MethodName.GetOverlay);
	}

	public void SetApiBaseUrl(string @value)
	{
		_object.Call(MethodName.SetApiBaseUrl, @value);
	}

	public string GetApiBaseUrl()
	{
		return (string)_object.Call(MethodName.GetApiBaseUrl);
	}

	public string[] GetLastStyleErrors()
	{
		return (string[])_object.Call(MethodName.GetLastStyleErrors);
	}

	#endregion
}
