// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumWebMapTileServiceRasterOverlay : CesiumRasterOverlay
{
	public CesiumWebMapTileServiceRasterOverlay() : base(NativeName)
	{
	}
	protected CesiumWebMapTileServiceRasterOverlay(StringName @class) : base(@class)
	{
	}
	protected CesiumWebMapTileServiceRasterOverlay(Variant variant) : base(variant)
	{
	}
	protected CesiumWebMapTileServiceRasterOverlay([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(CesiumWebMapTileServiceRasterOverlay self) => self?._object;
	public static implicit operator Variant(CesiumWebMapTileServiceRasterOverlay self) => self?._object;
	public static explicit operator CesiumWebMapTileServiceRasterOverlay(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : CesiumRasterOverlay.PropertyName
	{
		public static readonly StringName BaseUrl = "base_url";
		public static readonly StringName Layer = "layer";
		public static readonly StringName Style = "style";
		public static readonly StringName Format = "format";
		public static readonly StringName TileMatrixSetId = "tile_matrix_set_id";
		public static readonly StringName TileMatrixSetLabelPrefix = "tile_matrix_set_label_prefix";
		public static readonly StringName SpecifyTileMatrixSetLabels = "specify_tile_matrix_set_labels";
		public static readonly StringName TileMatrixSetLabels = "tile_matrix_set_labels";
		public static readonly StringName Projection = "projection";
		public static readonly StringName SpecifyTilingScheme = "specify_tiling_scheme";
		public static readonly StringName RootTilesX = "root_tiles_x";
		public static readonly StringName RootTilesY = "root_tiles_y";
		public static readonly StringName RectangleWest = "rectangle_west";
		public static readonly StringName RectangleSouth = "rectangle_south";
		public static readonly StringName RectangleEast = "rectangle_east";
		public static readonly StringName RectangleNorth = "rectangle_north";
		public static readonly StringName SpecifyZoomLevels = "specify_zoom_levels";
		public static readonly StringName MinimumLevel = "minimum_level";
		public static readonly StringName MaximumLevel = "maximum_level";
		public static readonly StringName TileWidth = "tile_width";
		public static readonly StringName TileHeight = "tile_height";
		public static readonly StringName Subdomains = "subdomains";
		public static readonly StringName Dimensions = "dimensions";
		public static readonly StringName RequestHeaders = "request_headers";
	}

	public new class MethodName : CesiumRasterOverlay.MethodName
	{
		public static readonly StringName SetBaseUrl = "set_base_url";
		public static readonly StringName GetBaseUrl = "get_base_url";
		public static readonly StringName SetLayer = "set_layer";
		public static readonly StringName GetLayer = "get_layer";
		public static readonly StringName SetStyle = "set_style";
		public static readonly StringName GetStyle = "get_style";
		public static readonly StringName SetFormat = "set_format";
		public static readonly StringName GetFormat = "get_format";
		public static readonly StringName SetTileMatrixSetId = "set_tile_matrix_set_id";
		public static readonly StringName GetTileMatrixSetId = "get_tile_matrix_set_id";
		public static readonly StringName SetTileMatrixSetLabelPrefix = "set_tile_matrix_set_label_prefix";
		public static readonly StringName GetTileMatrixSetLabelPrefix = "get_tile_matrix_set_label_prefix";
		public static readonly StringName SetSpecifyTileMatrixSetLabels = "set_specify_tile_matrix_set_labels";
		public static readonly StringName GetSpecifyTileMatrixSetLabels = "get_specify_tile_matrix_set_labels";
		public static readonly StringName SetTileMatrixSetLabels = "set_tile_matrix_set_labels";
		public static readonly StringName GetTileMatrixSetLabels = "get_tile_matrix_set_labels";
		public static readonly StringName SetProjection = "set_projection";
		public static readonly StringName GetProjection = "get_projection";
		public static readonly StringName SetSpecifyTilingScheme = "set_specify_tiling_scheme";
		public static readonly StringName GetSpecifyTilingScheme = "get_specify_tiling_scheme";
		public static readonly StringName SetRootTilesX = "set_root_tiles_x";
		public static readonly StringName GetRootTilesX = "get_root_tiles_x";
		public static readonly StringName SetRootTilesY = "set_root_tiles_y";
		public static readonly StringName GetRootTilesY = "get_root_tiles_y";
		public static readonly StringName SetRectangleWest = "set_rectangle_west";
		public static readonly StringName GetRectangleWest = "get_rectangle_west";
		public static readonly StringName SetRectangleSouth = "set_rectangle_south";
		public static readonly StringName GetRectangleSouth = "get_rectangle_south";
		public static readonly StringName SetRectangleEast = "set_rectangle_east";
		public static readonly StringName GetRectangleEast = "get_rectangle_east";
		public static readonly StringName SetRectangleNorth = "set_rectangle_north";
		public static readonly StringName GetRectangleNorth = "get_rectangle_north";
		public static readonly StringName SetSpecifyZoomLevels = "set_specify_zoom_levels";
		public static readonly StringName GetSpecifyZoomLevels = "get_specify_zoom_levels";
		public static readonly StringName SetMinimumLevel = "set_minimum_level";
		public static readonly StringName GetMinimumLevel = "get_minimum_level";
		public static readonly StringName SetMaximumLevel = "set_maximum_level";
		public static readonly StringName GetMaximumLevel = "get_maximum_level";
		public static readonly StringName SetTileWidth = "set_tile_width";
		public static readonly StringName GetTileWidth = "get_tile_width";
		public static readonly StringName SetTileHeight = "set_tile_height";
		public static readonly StringName GetTileHeight = "get_tile_height";
		public static readonly StringName SetSubdomains = "set_subdomains";
		public static readonly StringName GetSubdomains = "get_subdomains";
		public static readonly StringName SetDimensions = "set_dimensions";
		public static readonly StringName GetDimensions = "get_dimensions";
		public static readonly StringName SetRequestHeaders = "set_request_headers";
		public static readonly StringName GetRequestHeaders = "get_request_headers";
	}

	public new class SignalName : CesiumRasterOverlay.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumWebMapTileServiceRasterOverlay";

	#region Enums

	public enum ProjectionEnum : long
	{
		WebMercator = 0L,
		Geographic = 1L,
	}

	#endregion

	#region Properties

	public string BaseUrl
	{
		get => (string)_object.Get(PropertyName.BaseUrl);
		set => _object.Set(PropertyName.BaseUrl, value);
	}

	public string Layer
	{
		get => (string)_object.Get(PropertyName.Layer);
		set => _object.Set(PropertyName.Layer, value);
	}

	public string Style
	{
		get => (string)_object.Get(PropertyName.Style);
		set => _object.Set(PropertyName.Style, value);
	}

	public string Format
	{
		get => (string)_object.Get(PropertyName.Format);
		set => _object.Set(PropertyName.Format, value);
	}

	public string TileMatrixSetId
	{
		get => (string)_object.Get(PropertyName.TileMatrixSetId);
		set => _object.Set(PropertyName.TileMatrixSetId, value);
	}

	public string TileMatrixSetLabelPrefix
	{
		get => (string)_object.Get(PropertyName.TileMatrixSetLabelPrefix);
		set => _object.Set(PropertyName.TileMatrixSetLabelPrefix, value);
	}

	public bool SpecifyTileMatrixSetLabels
	{
		get => (bool)_object.Get(PropertyName.SpecifyTileMatrixSetLabels);
		set => _object.Set(PropertyName.SpecifyTileMatrixSetLabels, value);
	}

	public string[] TileMatrixSetLabels
	{
		get => (string[])_object.Get(PropertyName.TileMatrixSetLabels);
		set => _object.Set(PropertyName.TileMatrixSetLabels, value);
	}

	public int Projection
	{
		get => (int)_object.Get(PropertyName.Projection);
		set => _object.Set(PropertyName.Projection, value);
	}

	public bool SpecifyTilingScheme
	{
		get => (bool)_object.Get(PropertyName.SpecifyTilingScheme);
		set => _object.Set(PropertyName.SpecifyTilingScheme, value);
	}

	public int RootTilesX
	{
		get => (int)_object.Get(PropertyName.RootTilesX);
		set => _object.Set(PropertyName.RootTilesX, value);
	}

	public int RootTilesY
	{
		get => (int)_object.Get(PropertyName.RootTilesY);
		set => _object.Set(PropertyName.RootTilesY, value);
	}

	public float RectangleWest
	{
		get => (float)_object.Get(PropertyName.RectangleWest);
		set => _object.Set(PropertyName.RectangleWest, value);
	}

	public float RectangleSouth
	{
		get => (float)_object.Get(PropertyName.RectangleSouth);
		set => _object.Set(PropertyName.RectangleSouth, value);
	}

	public float RectangleEast
	{
		get => (float)_object.Get(PropertyName.RectangleEast);
		set => _object.Set(PropertyName.RectangleEast, value);
	}

	public float RectangleNorth
	{
		get => (float)_object.Get(PropertyName.RectangleNorth);
		set => _object.Set(PropertyName.RectangleNorth, value);
	}

	public bool SpecifyZoomLevels
	{
		get => (bool)_object.Get(PropertyName.SpecifyZoomLevels);
		set => _object.Set(PropertyName.SpecifyZoomLevels, value);
	}

	public int MinimumLevel
	{
		get => (int)_object.Get(PropertyName.MinimumLevel);
		set => _object.Set(PropertyName.MinimumLevel, value);
	}

	public int MaximumLevel
	{
		get => (int)_object.Get(PropertyName.MaximumLevel);
		set => _object.Set(PropertyName.MaximumLevel, value);
	}

	public int TileWidth
	{
		get => (int)_object.Get(PropertyName.TileWidth);
		set => _object.Set(PropertyName.TileWidth, value);
	}

	public int TileHeight
	{
		get => (int)_object.Get(PropertyName.TileHeight);
		set => _object.Set(PropertyName.TileHeight, value);
	}

	public string[] Subdomains
	{
		get => (string[])_object.Get(PropertyName.Subdomains);
		set => _object.Set(PropertyName.Subdomains, value);
	}

	public Godot.Collections.Dictionary Dimensions
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.Dimensions);
		set => _object.Set(PropertyName.Dimensions, value);
	}

	public Godot.Collections.Dictionary RequestHeaders
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.RequestHeaders);
		set => _object.Set(PropertyName.RequestHeaders, value);
	}

	#endregion

	#region Methods

	public void SetBaseUrl(string @value)
	{
		_object.Call(MethodName.SetBaseUrl, @value);
	}

	public string GetBaseUrl()
	{
		return (string)_object.Call(MethodName.GetBaseUrl);
	}

	public void SetLayer(string @value)
	{
		_object.Call(MethodName.SetLayer, @value);
	}

	public string GetLayer()
	{
		return (string)_object.Call(MethodName.GetLayer);
	}

	public void SetStyle(string @value)
	{
		_object.Call(MethodName.SetStyle, @value);
	}

	public string GetStyle()
	{
		return (string)_object.Call(MethodName.GetStyle);
	}

	public void SetFormat(string @value)
	{
		_object.Call(MethodName.SetFormat, @value);
	}

	public string GetFormat()
	{
		return (string)_object.Call(MethodName.GetFormat);
	}

	public void SetTileMatrixSetId(string @value)
	{
		_object.Call(MethodName.SetTileMatrixSetId, @value);
	}

	public string GetTileMatrixSetId()
	{
		return (string)_object.Call(MethodName.GetTileMatrixSetId);
	}

	public void SetTileMatrixSetLabelPrefix(string @value)
	{
		_object.Call(MethodName.SetTileMatrixSetLabelPrefix, @value);
	}

	public string GetTileMatrixSetLabelPrefix()
	{
		return (string)_object.Call(MethodName.GetTileMatrixSetLabelPrefix);
	}

	public void SetSpecifyTileMatrixSetLabels(bool @value)
	{
		_object.Call(MethodName.SetSpecifyTileMatrixSetLabels, @value);
	}

	public bool GetSpecifyTileMatrixSetLabels()
	{
		return (bool)_object.Call(MethodName.GetSpecifyTileMatrixSetLabels);
	}

	public void SetTileMatrixSetLabels(string[] @value)
	{
		_object.Call(MethodName.SetTileMatrixSetLabels, @value);
	}

	public string[] GetTileMatrixSetLabels()
	{
		return (string[])_object.Call(MethodName.GetTileMatrixSetLabels);
	}

	public void SetProjection(int @value)
	{
		_object.Call(MethodName.SetProjection, @value);
	}

	public int GetProjection()
	{
		return (int)_object.Call(MethodName.GetProjection);
	}

	public void SetSpecifyTilingScheme(bool @value)
	{
		_object.Call(MethodName.SetSpecifyTilingScheme, @value);
	}

	public bool GetSpecifyTilingScheme()
	{
		return (bool)_object.Call(MethodName.GetSpecifyTilingScheme);
	}

	public void SetRootTilesX(int @value)
	{
		_object.Call(MethodName.SetRootTilesX, @value);
	}

	public int GetRootTilesX()
	{
		return (int)_object.Call(MethodName.GetRootTilesX);
	}

	public void SetRootTilesY(int @value)
	{
		_object.Call(MethodName.SetRootTilesY, @value);
	}

	public int GetRootTilesY()
	{
		return (int)_object.Call(MethodName.GetRootTilesY);
	}

	public void SetRectangleWest(float @value)
	{
		_object.Call(MethodName.SetRectangleWest, @value);
	}

	public float GetRectangleWest()
	{
		return (float)_object.Call(MethodName.GetRectangleWest);
	}

	public void SetRectangleSouth(float @value)
	{
		_object.Call(MethodName.SetRectangleSouth, @value);
	}

	public float GetRectangleSouth()
	{
		return (float)_object.Call(MethodName.GetRectangleSouth);
	}

	public void SetRectangleEast(float @value)
	{
		_object.Call(MethodName.SetRectangleEast, @value);
	}

	public float GetRectangleEast()
	{
		return (float)_object.Call(MethodName.GetRectangleEast);
	}

	public void SetRectangleNorth(float @value)
	{
		_object.Call(MethodName.SetRectangleNorth, @value);
	}

	public float GetRectangleNorth()
	{
		return (float)_object.Call(MethodName.GetRectangleNorth);
	}

	public void SetSpecifyZoomLevels(bool @value)
	{
		_object.Call(MethodName.SetSpecifyZoomLevels, @value);
	}

	public bool GetSpecifyZoomLevels()
	{
		return (bool)_object.Call(MethodName.GetSpecifyZoomLevels);
	}

	public void SetMinimumLevel(int @value)
	{
		_object.Call(MethodName.SetMinimumLevel, @value);
	}

	public int GetMinimumLevel()
	{
		return (int)_object.Call(MethodName.GetMinimumLevel);
	}

	public void SetMaximumLevel(int @value)
	{
		_object.Call(MethodName.SetMaximumLevel, @value);
	}

	public int GetMaximumLevel()
	{
		return (int)_object.Call(MethodName.GetMaximumLevel);
	}

	public void SetTileWidth(int @value)
	{
		_object.Call(MethodName.SetTileWidth, @value);
	}

	public int GetTileWidth()
	{
		return (int)_object.Call(MethodName.GetTileWidth);
	}

	public void SetTileHeight(int @value)
	{
		_object.Call(MethodName.SetTileHeight, @value);
	}

	public int GetTileHeight()
	{
		return (int)_object.Call(MethodName.GetTileHeight);
	}

	public void SetSubdomains(string[] @value)
	{
		_object.Call(MethodName.SetSubdomains, @value);
	}

	public string[] GetSubdomains()
	{
		return (string[])_object.Call(MethodName.GetSubdomains);
	}

	public void SetDimensions(Godot.Collections.Dictionary @value)
	{
		_object.Call(MethodName.SetDimensions, @value);
	}

	public Godot.Collections.Dictionary GetDimensions()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetDimensions);
	}

	public void SetRequestHeaders(Godot.Collections.Dictionary @value)
	{
		_object.Call(MethodName.SetRequestHeaders, @value);
	}

	public Godot.Collections.Dictionary GetRequestHeaders()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetRequestHeaders);
	}

	#endregion
}
