// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGeoJsonDocument
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public Resource NativeObject => _object;

	public CesiumGeoJsonDocument() : this(NativeName)
	{
	}
	protected CesiumGeoJsonDocument(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGeoJsonDocument(Variant variant) : this((Resource) variant)
	{
	}
	protected CesiumGeoJsonDocument([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(CesiumGeoJsonDocument self) => self?._object;
	public static implicit operator Variant(CesiumGeoJsonDocument self) => self?._object;
	public static explicit operator CesiumGeoJsonDocument(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName Valid = "valid";
		public static readonly StringName Errors = "errors";
		public static readonly StringName Warnings = "warnings";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName LoadFromString = "load_from_string";
		public static readonly StringName Clear = "clear";
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName GetRootObject = "get_root_object";
		public static readonly StringName GetObjects = "get_objects";
		public static readonly StringName GetStatistics = "get_statistics";
		public static readonly StringName GetAttributions = "get_attributions";
		public static readonly StringName GetErrors = "get_errors";
		public static readonly StringName GetWarnings = "get_warnings";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumGeoJsonDocument";

	#region Properties

	public bool Valid
	{
		get => (bool)_object.Get(PropertyName.Valid);
	}

	public string[] Errors
	{
		get => (string[])_object.Get(PropertyName.Errors);
	}

	public string[] Warnings
	{
		get => (string[])_object.Get(PropertyName.Warnings);
	}

	#endregion

	#region Methods

	public bool LoadFromString(string @geo_json, Godot.Collections.Array @attributions = null)
	{
		@attributions ??= new();
		return (bool)_object.Call(MethodName.LoadFromString, @geo_json, @attributions);
	}

	public void Clear()
	{
		_object.Call(MethodName.Clear);
	}

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public CesiumGeoJsonObject GetRootObject()
	{
		return (CesiumGeoJsonObject)_object.Call(MethodName.GetRootObject);
	}

	public Godot.Collections.Array GetObjects()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetObjects);
	}

	public Godot.Collections.Dictionary GetStatistics()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetStatistics);
	}

	public Godot.Collections.Array GetAttributions()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetAttributions);
	}

	public string[] GetErrors()
	{
		return (string[])_object.Call(MethodName.GetErrors);
	}

	public string[] GetWarnings()
	{
		return (string[])_object.Call(MethodName.GetWarnings);
	}

	#endregion
}
