// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumDebugColorizeTilesRasterOverlay : CesiumRasterOverlay
{
	public CesiumDebugColorizeTilesRasterOverlay() : base(NativeName)
	{
	}
	protected CesiumDebugColorizeTilesRasterOverlay(StringName @class) : base(@class)
	{
	}
	protected CesiumDebugColorizeTilesRasterOverlay(Variant variant) : base(variant)
	{
	}
	protected CesiumDebugColorizeTilesRasterOverlay([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(CesiumDebugColorizeTilesRasterOverlay self) => self?._object;
	public static implicit operator Variant(CesiumDebugColorizeTilesRasterOverlay self) => self?._object;
	public static explicit operator CesiumDebugColorizeTilesRasterOverlay(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : CesiumRasterOverlay.PropertyName
	{

	}

	public new class MethodName : CesiumRasterOverlay.MethodName
	{

	}

	public new class SignalName : CesiumRasterOverlay.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumDebugColorizeTilesRasterOverlay";
}
