// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGeoreference
{
	// Engine object used for calling engine methods
	protected Node3D _object;

	public Node3D NativeObject => _object;

	public CesiumGeoreference() : this(NativeName)
	{
	}
	protected CesiumGeoreference(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGeoreference(Variant variant) : this((Node3D) variant)
	{
	}
	protected CesiumGeoreference([NotNull] Node3D @object)
	{
		_object = @object;
	}

	public static implicit operator Node3D(CesiumGeoreference self) => self?._object;
	public static implicit operator Variant(CesiumGeoreference self) => self?._object;
	public static explicit operator CesiumGeoreference(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node3D.PropertyName
	{
		public static readonly StringName Ellipsoid = "ellipsoid";
		public static readonly StringName OriginType = "origin_type";
		public static readonly StringName Latitude = "latitude";
		public static readonly StringName Longitude = "longitude";
		public static readonly StringName Altitude = "altitude";
		public static readonly StringName EcefX = "ecefX";
		public static readonly StringName EcefY = "ecefY";
		public static readonly StringName EcefZ = "ecefZ";
		public static readonly StringName ScaleFactor = "scale_factor";
		public static readonly StringName ShouldUpdateOrigin = "should_update_origin";
	}

	public class MethodName : Node3D.MethodName
	{
		public static readonly StringName SetEllipsoid = "set_ellipsoid";
		public static readonly StringName GetEllipsoid = "get_ellipsoid";
		public static readonly StringName GetOriginType = "get_origin_type";
		public static readonly StringName SetOriginType = "set_origin_type";
		public static readonly StringName GetEcefX = "get_ecef_x";
		public static readonly StringName SetEcefX = "set_ecef_x";
		public static readonly StringName GetEcefY = "get_ecef_y";
		public static readonly StringName SetEcefY = "set_ecef_y";
		public static readonly StringName GetEcefZ = "get_ecef_z";
		public static readonly StringName SetEcefZ = "set_ecef_z";
		public static readonly StringName GetOriginEcefPrecise = "get_origin_ecef_precise";
		public static readonly StringName SetOriginEcefPrecise = "set_origin_ecef_precise";
		public static readonly StringName GetLatitude = "get_latitude";
		public static readonly StringName SetLatitude = "set_latitude";
		public static readonly StringName GetLongitude = "get_longitude";
		public static readonly StringName SetLongitude = "set_longitude";
		public static readonly StringName GetAltitude = "get_altitude";
		public static readonly StringName SetAltitude = "set_altitude";
		public static readonly StringName GetOriginLongitudeLatitudeHeightPrecise = "get_origin_longitude_latitude_height_precise";
		public static readonly StringName SetOriginLongitudeLatitudeHeightPrecise = "set_origin_longitude_latitude_height_precise";
		public static readonly StringName GetScaleFactor = "get_scale_factor";
		public static readonly StringName SetScaleFactor = "set_scale_factor";
		public static readonly StringName GetRevision = "get_revision";
		public static readonly StringName TransformEcefPositionToLocalPrecise = "transform_ecef_position_to_local_precise";
		public static readonly StringName TransformLocalPositionToEcefPrecise = "transform_local_position_to_ecef_precise";
		public static readonly StringName TransformEcefDirectionToLocalPrecise = "transform_ecef_direction_to_local_precise";
		public static readonly StringName TransformLocalDirectionToEcefPrecise = "transform_local_direction_to_ecef_precise";
		public static readonly StringName TransformLongitudeLatitudeHeightToLocalPrecise = "transform_longitude_latitude_height_to_local_precise";
		public static readonly StringName TransformLocalToLongitudeLatitudeHeightPrecise = "transform_local_to_longitude_latitude_height_precise";
		public static readonly StringName TransformEcefPositionToLocal = "transform_ecef_position_to_local";
		public static readonly StringName TransformLocalPositionToEcef = "transform_local_position_to_ecef";
		public static readonly StringName TransformEcefDirectionToLocal = "transform_ecef_direction_to_local";
		public static readonly StringName TransformLocalDirectionToEcef = "transform_local_direction_to_ecef";
		public static readonly StringName TransformGlobalPositionToEcef = "transform_global_position_to_ecef";
		public static readonly StringName TransformEcefPositionToGlobal = "transform_ecef_position_to_global";
		public static readonly StringName GetTxEngineToEcef = "get_tx_engine_to_ecef";
		public static readonly StringName GetTxEcefToEngine = "get_tx_ecef_to_engine";
		public static readonly StringName GetInitialTxEngineToEcef = "get_initial_tx_engine_to_ecef";
		public static readonly StringName GetInitialTxEcefToEngine = "get_initial_tx_ecef_to_engine";
		public static readonly StringName GetGlobalCenterPosition = "get_global_center_position";
		public static readonly StringName GetGlobalSurfacePosition = "get_global_surface_position";
		public static readonly StringName GetMousePosEcef = "get_mouse_pos_ecef";
		public static readonly StringName GetMousePosEcefPrecise = "get_mouse_pos_ecef_precise";
		public static readonly StringName RayToSurface = "ray_to_surface";
		public static readonly StringName GetEllipsoidDimensions = "get_ellipsoid_dimensions";
		public static readonly StringName EusAtEcef = "eus_at_ecef";
		public static readonly StringName GetNormalAtSurfacePos = "get_normal_at_surface_pos";
		public static readonly StringName EcefToLatLonAltDeg = "ecef_to_lat_lon_alt_deg";
		public static readonly StringName EcefToLatLonAltRad = "ecef_to_lat_lon_alt_rad";
		public static readonly StringName LatLonAltRadToEcef = "lat_lon_alt_rad_to_ecef";
		public static readonly StringName SetShouldUpdateOrigin = "set_should_update_origin";
		public static readonly StringName GetShouldUpdateOrigin = "get_should_update_origin";
		public static readonly StringName RefreshDependents = "refresh_dependents";
	}

	public class SignalName : Node3D.SignalName
	{
		public static readonly StringName GeoreferenceChanged = "georeference_changed";
		public static readonly StringName EllipsoidChanged = "ellipsoid_changed";
	}

	private static readonly StringName NativeName = "CesiumGeoreference";

	#region Enums

	public enum OriginTypeEnum : long
	{
		CartographicOrigin = 0L,
		TrueOrigin = 1L,
	}

	#endregion

	#region Properties

	public CesiumEllipsoid Ellipsoid
	{
		get => (CesiumEllipsoid)_object.Get(PropertyName.Ellipsoid);
		set => _object.Set(PropertyName.Ellipsoid, value);
	}

	public int OriginType
	{
		get => (int)_object.Get(PropertyName.OriginType);
		set => _object.Set(PropertyName.OriginType, value);
	}

	public float Latitude
	{
		get => (float)_object.Get(PropertyName.Latitude);
		set => _object.Set(PropertyName.Latitude, value);
	}

	public float Longitude
	{
		get => (float)_object.Get(PropertyName.Longitude);
		set => _object.Set(PropertyName.Longitude, value);
	}

	public float Altitude
	{
		get => (float)_object.Get(PropertyName.Altitude);
		set => _object.Set(PropertyName.Altitude, value);
	}

	public float EcefX
	{
		get => (float)_object.Get(PropertyName.EcefX);
		set => _object.Set(PropertyName.EcefX, value);
	}

	public float EcefY
	{
		get => (float)_object.Get(PropertyName.EcefY);
		set => _object.Set(PropertyName.EcefY, value);
	}

	public float EcefZ
	{
		get => (float)_object.Get(PropertyName.EcefZ);
		set => _object.Set(PropertyName.EcefZ, value);
	}

	public float ScaleFactor
	{
		get => (float)_object.Get(PropertyName.ScaleFactor);
		set => _object.Set(PropertyName.ScaleFactor, value);
	}

	public bool ShouldUpdateOrigin
	{
		get => (bool)_object.Get(PropertyName.ShouldUpdateOrigin);
		set => _object.Set(PropertyName.ShouldUpdateOrigin, value);
	}

	#endregion

	#region Methods

	public void SetEllipsoid(CesiumEllipsoid @ellipsoid)
	{
		_object.Call(MethodName.SetEllipsoid, @ellipsoid);
	}

	public CesiumEllipsoid GetEllipsoid()
	{
		return (CesiumEllipsoid)_object.Call(MethodName.GetEllipsoid);
	}

	public int GetOriginType()
	{
		return (int)_object.Call(MethodName.GetOriginType);
	}

	public void SetOriginType(int @origin_type)
	{
		_object.Call(MethodName.SetOriginType, @origin_type);
	}

	public float GetEcefX()
	{
		return (float)_object.Call(MethodName.GetEcefX);
	}

	public void SetEcefX(float @value)
	{
		_object.Call(MethodName.SetEcefX, @value);
	}

	public float GetEcefY()
	{
		return (float)_object.Call(MethodName.GetEcefY);
	}

	public void SetEcefY(float @value)
	{
		_object.Call(MethodName.SetEcefY, @value);
	}

	public float GetEcefZ()
	{
		return (float)_object.Call(MethodName.GetEcefZ);
	}

	public void SetEcefZ(float @value)
	{
		_object.Call(MethodName.SetEcefZ, @value);
	}

	public double[] GetOriginEcefPrecise()
	{
		return (double[])_object.Call(MethodName.GetOriginEcefPrecise);
	}

	public bool SetOriginEcefPrecise(double[] @ecef)
	{
		return (bool)_object.Call(MethodName.SetOriginEcefPrecise, @ecef);
	}

	public float GetLatitude()
	{
		return (float)_object.Call(MethodName.GetLatitude);
	}

	public void SetLatitude(float @value)
	{
		_object.Call(MethodName.SetLatitude, @value);
	}

	public float GetLongitude()
	{
		return (float)_object.Call(MethodName.GetLongitude);
	}

	public void SetLongitude(float @value)
	{
		_object.Call(MethodName.SetLongitude, @value);
	}

	public float GetAltitude()
	{
		return (float)_object.Call(MethodName.GetAltitude);
	}

	public void SetAltitude(float @value)
	{
		_object.Call(MethodName.SetAltitude, @value);
	}

	public double[] GetOriginLongitudeLatitudeHeightPrecise()
	{
		return (double[])_object.Call(MethodName.GetOriginLongitudeLatitudeHeightPrecise);
	}

	public void SetOriginLongitudeLatitudeHeightPrecise(double[] @longitude_latitude_height)
	{
		_object.Call(MethodName.SetOriginLongitudeLatitudeHeightPrecise, @longitude_latitude_height);
	}

	public float GetScaleFactor()
	{
		return (float)_object.Call(MethodName.GetScaleFactor);
	}

	public void SetScaleFactor(float @value)
	{
		_object.Call(MethodName.SetScaleFactor, @value);
	}

	public int GetRevision()
	{
		return (int)_object.Call(MethodName.GetRevision);
	}

	public double[] TransformEcefPositionToLocalPrecise(double[] @ecef)
	{
		return (double[])_object.Call(MethodName.TransformEcefPositionToLocalPrecise, @ecef);
	}

	public double[] TransformLocalPositionToEcefPrecise(double[] @local)
	{
		return (double[])_object.Call(MethodName.TransformLocalPositionToEcefPrecise, @local);
	}

	public double[] TransformEcefDirectionToLocalPrecise(double[] @ecef)
	{
		return (double[])_object.Call(MethodName.TransformEcefDirectionToLocalPrecise, @ecef);
	}

	public double[] TransformLocalDirectionToEcefPrecise(double[] @local)
	{
		return (double[])_object.Call(MethodName.TransformLocalDirectionToEcefPrecise, @local);
	}

	public double[] TransformLongitudeLatitudeHeightToLocalPrecise(double[] @longitude_latitude_height)
	{
		return (double[])_object.Call(MethodName.TransformLongitudeLatitudeHeightToLocalPrecise, @longitude_latitude_height);
	}

	public double[] TransformLocalToLongitudeLatitudeHeightPrecise(double[] @local)
	{
		return (double[])_object.Call(MethodName.TransformLocalToLongitudeLatitudeHeightPrecise, @local);
	}

	public Godot.Vector3 TransformEcefPositionToLocal(Godot.Vector3 @ecef)
	{
		return (Godot.Vector3)_object.Call(MethodName.TransformEcefPositionToLocal, @ecef);
	}

	public Godot.Vector3 TransformLocalPositionToEcef(Godot.Vector3 @local)
	{
		return (Godot.Vector3)_object.Call(MethodName.TransformLocalPositionToEcef, @local);
	}

	public Godot.Vector3 TransformEcefDirectionToLocal(Godot.Vector3 @ecef)
	{
		return (Godot.Vector3)_object.Call(MethodName.TransformEcefDirectionToLocal, @ecef);
	}

	public Godot.Vector3 TransformLocalDirectionToEcef(Godot.Vector3 @local)
	{
		return (Godot.Vector3)_object.Call(MethodName.TransformLocalDirectionToEcef, @local);
	}

	public Godot.Vector3 TransformGlobalPositionToEcef(Godot.Vector3 @global)
	{
		return (Godot.Vector3)_object.Call(MethodName.TransformGlobalPositionToEcef, @global);
	}

	public Godot.Vector3 TransformEcefPositionToGlobal(Godot.Vector3 @ecef)
	{
		return (Godot.Vector3)_object.Call(MethodName.TransformEcefPositionToGlobal, @ecef);
	}

	public Godot.Transform3D GetTxEngineToEcef()
	{
		return (Godot.Transform3D)_object.Call(MethodName.GetTxEngineToEcef);
	}

	public Godot.Transform3D GetTxEcefToEngine()
	{
		return (Godot.Transform3D)_object.Call(MethodName.GetTxEcefToEngine);
	}

	public Godot.Transform3D GetInitialTxEngineToEcef()
	{
		return (Godot.Transform3D)_object.Call(MethodName.GetInitialTxEngineToEcef);
	}

	public Godot.Transform3D GetInitialTxEcefToEngine()
	{
		return (Godot.Transform3D)_object.Call(MethodName.GetInitialTxEcefToEngine);
	}

	public Godot.Vector3 GetGlobalCenterPosition()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetGlobalCenterPosition);
	}

	public Godot.Vector3 GetGlobalSurfacePosition(Godot.Vector3 @camera_position, Godot.Vector3 @camera_direction)
	{
		return (Godot.Vector3)_object.Call(MethodName.GetGlobalSurfacePosition, @camera_position, @camera_direction);
	}

	public Godot.Vector3 GetMousePosEcef()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetMousePosEcef);
	}

	public double[] GetMousePosEcefPrecise()
	{
		return (double[])_object.Call(MethodName.GetMousePosEcefPrecise);
	}

	public Godot.Vector3 RayToSurface(Godot.Vector3 @origin, Godot.Vector3 @direction)
	{
		return (Godot.Vector3)_object.Call(MethodName.RayToSurface, @origin, @direction);
	}

	public Godot.Vector3 GetEllipsoidDimensions()
	{
		return (Godot.Vector3)_object.Call(MethodName.GetEllipsoidDimensions);
	}

	public Godot.Basis EusAtEcef(Godot.Vector3 @ecef)
	{
		return (Godot.Basis)_object.Call(MethodName.EusAtEcef, @ecef);
	}

	public Godot.Vector3 GetNormalAtSurfacePos(Godot.Vector3 @ecef)
	{
		return (Godot.Vector3)_object.Call(MethodName.GetNormalAtSurfacePos, @ecef);
	}

	public Godot.Vector3 EcefToLatLonAltDeg(Godot.Vector3 @ecef)
	{
		return (Godot.Vector3)_object.Call(MethodName.EcefToLatLonAltDeg, @ecef);
	}

	public Godot.Vector3 EcefToLatLonAltRad(Godot.Vector3 @ecef)
	{
		return (Godot.Vector3)_object.Call(MethodName.EcefToLatLonAltRad, @ecef);
	}

	public Godot.Vector3 LatLonAltRadToEcef(Godot.Vector3 @latitude_longitude_altitude)
	{
		return (Godot.Vector3)_object.Call(MethodName.LatLonAltRadToEcef, @latitude_longitude_altitude);
	}

	public void SetShouldUpdateOrigin(bool @value)
	{
		_object.Call(MethodName.SetShouldUpdateOrigin, @value);
	}

	public bool GetShouldUpdateOrigin()
	{
		return (bool)_object.Call(MethodName.GetShouldUpdateOrigin);
	}

	public void RefreshDependents()
	{
		_object.Call(MethodName.RefreshDependents);
	}

	#endregion

	#region Signals

	public event Action<int> GeoreferenceChanged
	{
		add
		{
			_object.Connect(SignalName.GeoreferenceChanged, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.GeoreferenceChanged, Callable.From(value));
		}
	}

	public event Action<GodotObject> EllipsoidChanged
	{
		add
		{
			_object.Connect(SignalName.EllipsoidChanged, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.EllipsoidChanged, Callable.From(value));
		}
	}

	#endregion
}
