// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumFlyTo
{
	// Engine object used for calling engine methods
	protected Node _object;

	public Node NativeObject => _object;

	public CesiumFlyTo() : this(NativeName)
	{
	}
	protected CesiumFlyTo(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumFlyTo(Variant variant) : this((Node) variant)
	{
	}
	protected CesiumFlyTo([NotNull] Node @object)
	{
		_object = @object;
	}

	public static implicit operator Node(CesiumFlyTo self) => self?._object;
	public static implicit operator Variant(CesiumFlyTo self) => self?._object;
	public static explicit operator CesiumFlyTo(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node.PropertyName
	{
		public static readonly StringName GlobeAnchorPath = "globe_anchor_path";
		public static readonly StringName Duration = "duration";
		public static readonly StringName ProgressCurve = "progress_curve";
		public static readonly StringName HeightPercentageCurve = "height_percentage_curve";
		public static readonly StringName MaximumHeightByDistanceCurve = "maximum_height_by_distance_curve";
		public static readonly StringName MaximumHeightCurveDistance = "maximum_height_curve_distance";
		public static readonly StringName DefaultMaximumHeight = "default_maximum_height";
		public static readonly StringName MovementInterruptTolerance = "movement_interrupt_tolerance";
		public static readonly StringName AutomaticUpdate = "automatic_update";
		public static readonly StringName FlightInProgress = "flight_in_progress";
		public static readonly StringName FlightProgress = "flight_progress";
		public static readonly StringName FlightElapsedTime = "flight_elapsed_time";
		public static readonly StringName FlightDistance = "flight_distance";
		public static readonly StringName CurrentHeightOffset = "current_height_offset";
		public static readonly StringName DestinationEcefPrecise = "destination_ecef_precise";
		public static readonly StringName LastInterruptionReason = "last_interruption_reason";
	}

	public class MethodName : Node.MethodName
	{
		public static readonly StringName SetGlobeAnchorPath = "set_globe_anchor_path";
		public static readonly StringName GetGlobeAnchorPath = "get_globe_anchor_path";
		public static readonly StringName GetGlobeAnchor = "get_globe_anchor";
		public static readonly StringName SetDuration = "set_duration";
		public static readonly StringName GetDuration = "get_duration";
		public static readonly StringName SetProgressCurve = "set_progress_curve";
		public static readonly StringName GetProgressCurve = "get_progress_curve";
		public static readonly StringName SetHeightPercentageCurve = "set_height_percentage_curve";
		public static readonly StringName GetHeightPercentageCurve = "get_height_percentage_curve";
		public static readonly StringName SetMaximumHeightByDistanceCurve = "set_maximum_height_by_distance_curve";
		public static readonly StringName GetMaximumHeightByDistanceCurve = "get_maximum_height_by_distance_curve";
		public static readonly StringName SetMaximumHeightCurveDistance = "set_maximum_height_curve_distance";
		public static readonly StringName GetMaximumHeightCurveDistance = "get_maximum_height_curve_distance";
		public static readonly StringName SetDefaultMaximumHeight = "set_default_maximum_height";
		public static readonly StringName GetDefaultMaximumHeight = "get_default_maximum_height";
		public static readonly StringName SetMovementInterruptTolerance = "set_movement_interrupt_tolerance";
		public static readonly StringName GetMovementInterruptTolerance = "get_movement_interrupt_tolerance";
		public static readonly StringName SetAutomaticUpdate = "set_automatic_update";
		public static readonly StringName GetAutomaticUpdate = "get_automatic_update";
		public static readonly StringName FlyToLocationEcefPrecise = "fly_to_location_ecef_precise";
		public static readonly StringName FlyToLocationLongitudeLatitudeHeightPrecise = "fly_to_location_longitude_latitude_height_precise";
		public static readonly StringName FlyToLocationLocalPrecise = "fly_to_location_local_precise";
		public static readonly StringName FlyToLocationEcef = "fly_to_location_ecef";
		public static readonly StringName FlyToLocationLongitudeLatitudeHeight = "fly_to_location_longitude_latitude_height";
		public static readonly StringName FlyToLocationGlobal = "fly_to_location_global";
		public static readonly StringName UpdateFlight = "update_flight";
		public static readonly StringName InterruptFlight = "interrupt_flight";
		public static readonly StringName IsFlightInProgress = "is_flight_in_progress";
		public static readonly StringName GetFlightProgress = "get_flight_progress";
		public static readonly StringName GetFlightElapsedTime = "get_flight_elapsed_time";
		public static readonly StringName GetFlightDistance = "get_flight_distance";
		public static readonly StringName GetCurrentHeightOffset = "get_current_height_offset";
		public static readonly StringName GetDestinationEcefPrecise = "get_destination_ecef_precise";
		public static readonly StringName GetLastInterruptionReason = "get_last_interruption_reason";
	}

	public class SignalName : Node.SignalName
	{
		public static readonly StringName FlightStarted = "flight_started";
		public static readonly StringName FlightProgressed = "flight_progressed";
		public static readonly StringName FlightCompleted = "flight_completed";
		public static readonly StringName FlightInterrupted = "flight_interrupted";
	}

	private static readonly StringName NativeName = "CesiumFlyTo";

	#region Enums

	public enum InterruptionReason : long
	{
		ExplicitlyInterrupted = 0L,
		TargetMoved = 1L,
		AnchorUnavailable = 2L,
	}

	#endregion

	#region Properties

	public Godot.NodePath GlobeAnchorPath
	{
		get => (Godot.NodePath)_object.Get(PropertyName.GlobeAnchorPath);
		set => _object.Set(PropertyName.GlobeAnchorPath, value);
	}

	public float Duration
	{
		get => (float)_object.Get(PropertyName.Duration);
		set => _object.Set(PropertyName.Duration, value);
	}

	public Curve ProgressCurve
	{
		get => (Curve)_object.Get(PropertyName.ProgressCurve);
		set => _object.Set(PropertyName.ProgressCurve, value);
	}

	public Curve HeightPercentageCurve
	{
		get => (Curve)_object.Get(PropertyName.HeightPercentageCurve);
		set => _object.Set(PropertyName.HeightPercentageCurve, value);
	}

	public Curve MaximumHeightByDistanceCurve
	{
		get => (Curve)_object.Get(PropertyName.MaximumHeightByDistanceCurve);
		set => _object.Set(PropertyName.MaximumHeightByDistanceCurve, value);
	}

	public float MaximumHeightCurveDistance
	{
		get => (float)_object.Get(PropertyName.MaximumHeightCurveDistance);
		set => _object.Set(PropertyName.MaximumHeightCurveDistance, value);
	}

	public float DefaultMaximumHeight
	{
		get => (float)_object.Get(PropertyName.DefaultMaximumHeight);
		set => _object.Set(PropertyName.DefaultMaximumHeight, value);
	}

	public float MovementInterruptTolerance
	{
		get => (float)_object.Get(PropertyName.MovementInterruptTolerance);
		set => _object.Set(PropertyName.MovementInterruptTolerance, value);
	}

	public bool AutomaticUpdate
	{
		get => (bool)_object.Get(PropertyName.AutomaticUpdate);
		set => _object.Set(PropertyName.AutomaticUpdate, value);
	}

	public bool FlightInProgress
	{
		get => (bool)_object.Get(PropertyName.FlightInProgress);
	}

	public float FlightProgress
	{
		get => (float)_object.Get(PropertyName.FlightProgress);
	}

	public float FlightElapsedTime
	{
		get => (float)_object.Get(PropertyName.FlightElapsedTime);
	}

	public float FlightDistance
	{
		get => (float)_object.Get(PropertyName.FlightDistance);
	}

	public float CurrentHeightOffset
	{
		get => (float)_object.Get(PropertyName.CurrentHeightOffset);
	}

	public double[] DestinationEcefPrecise
	{
		get => (double[])_object.Get(PropertyName.DestinationEcefPrecise);
	}

	public int LastInterruptionReason
	{
		get => (int)_object.Get(PropertyName.LastInterruptionReason);
	}

	#endregion

	#region Methods

	public void SetGlobeAnchorPath(Godot.NodePath @path)
	{
		_object.Call(MethodName.SetGlobeAnchorPath, @path);
	}

	public Godot.NodePath GetGlobeAnchorPath()
	{
		return (Godot.NodePath)_object.Call(MethodName.GetGlobeAnchorPath);
	}

	public CesiumGlobeAnchor GetGlobeAnchor()
	{
		return (CesiumGlobeAnchor)_object.Call(MethodName.GetGlobeAnchor);
	}

	public void SetDuration(float @value)
	{
		_object.Call(MethodName.SetDuration, @value);
	}

	public float GetDuration()
	{
		return (float)_object.Call(MethodName.GetDuration);
	}

	public void SetProgressCurve(Curve @curve)
	{
		_object.Call(MethodName.SetProgressCurve, @curve);
	}

	public Curve GetProgressCurve()
	{
		return (Curve)_object.Call(MethodName.GetProgressCurve);
	}

	public void SetHeightPercentageCurve(Curve @curve)
	{
		_object.Call(MethodName.SetHeightPercentageCurve, @curve);
	}

	public Curve GetHeightPercentageCurve()
	{
		return (Curve)_object.Call(MethodName.GetHeightPercentageCurve);
	}

	public void SetMaximumHeightByDistanceCurve(Curve @curve)
	{
		_object.Call(MethodName.SetMaximumHeightByDistanceCurve, @curve);
	}

	public Curve GetMaximumHeightByDistanceCurve()
	{
		return (Curve)_object.Call(MethodName.GetMaximumHeightByDistanceCurve);
	}

	public void SetMaximumHeightCurveDistance(float @value)
	{
		_object.Call(MethodName.SetMaximumHeightCurveDistance, @value);
	}

	public float GetMaximumHeightCurveDistance()
	{
		return (float)_object.Call(MethodName.GetMaximumHeightCurveDistance);
	}

	public void SetDefaultMaximumHeight(float @value)
	{
		_object.Call(MethodName.SetDefaultMaximumHeight, @value);
	}

	public float GetDefaultMaximumHeight()
	{
		return (float)_object.Call(MethodName.GetDefaultMaximumHeight);
	}

	public void SetMovementInterruptTolerance(float @value)
	{
		_object.Call(MethodName.SetMovementInterruptTolerance, @value);
	}

	public float GetMovementInterruptTolerance()
	{
		return (float)_object.Call(MethodName.GetMovementInterruptTolerance);
	}

	public void SetAutomaticUpdate(bool @value)
	{
		_object.Call(MethodName.SetAutomaticUpdate, @value);
	}

	public bool GetAutomaticUpdate()
	{
		return (bool)_object.Call(MethodName.GetAutomaticUpdate);
	}

	public bool FlyToLocationEcefPrecise(double[] @destination, float @yaw_at_destination = 0.0f, float @pitch_at_destination = 0.0f, bool @can_interrupt_by_moving = true)
	{
		return (bool)_object.Call(MethodName.FlyToLocationEcefPrecise, @destination, @yaw_at_destination, @pitch_at_destination, @can_interrupt_by_moving);
	}

	public bool FlyToLocationLongitudeLatitudeHeightPrecise(double[] @destination, float @yaw_at_destination = 0.0f, float @pitch_at_destination = 0.0f, bool @can_interrupt_by_moving = true)
	{
		return (bool)_object.Call(MethodName.FlyToLocationLongitudeLatitudeHeightPrecise, @destination, @yaw_at_destination, @pitch_at_destination, @can_interrupt_by_moving);
	}

	public bool FlyToLocationLocalPrecise(double[] @destination, float @yaw_at_destination = 0.0f, float @pitch_at_destination = 0.0f, bool @can_interrupt_by_moving = true)
	{
		return (bool)_object.Call(MethodName.FlyToLocationLocalPrecise, @destination, @yaw_at_destination, @pitch_at_destination, @can_interrupt_by_moving);
	}

	public bool FlyToLocationEcef(Godot.Vector3 @destination, float @yaw_at_destination = 0.0f, float @pitch_at_destination = 0.0f, bool @can_interrupt_by_moving = true)
	{
		return (bool)_object.Call(MethodName.FlyToLocationEcef, @destination, @yaw_at_destination, @pitch_at_destination, @can_interrupt_by_moving);
	}

	public bool FlyToLocationLongitudeLatitudeHeight(Godot.Vector3 @destination, float @yaw_at_destination = 0.0f, float @pitch_at_destination = 0.0f, bool @can_interrupt_by_moving = true)
	{
		return (bool)_object.Call(MethodName.FlyToLocationLongitudeLatitudeHeight, @destination, @yaw_at_destination, @pitch_at_destination, @can_interrupt_by_moving);
	}

	public bool FlyToLocationGlobal(Godot.Vector3 @destination, float @yaw_at_destination = 0.0f, float @pitch_at_destination = 0.0f, bool @can_interrupt_by_moving = true)
	{
		return (bool)_object.Call(MethodName.FlyToLocationGlobal, @destination, @yaw_at_destination, @pitch_at_destination, @can_interrupt_by_moving);
	}

	public bool UpdateFlight(float @delta)
	{
		return (bool)_object.Call(MethodName.UpdateFlight, @delta);
	}

	public bool InterruptFlight()
	{
		return (bool)_object.Call(MethodName.InterruptFlight);
	}

	public bool IsFlightInProgress()
	{
		return (bool)_object.Call(MethodName.IsFlightInProgress);
	}

	public float GetFlightProgress()
	{
		return (float)_object.Call(MethodName.GetFlightProgress);
	}

	public float GetFlightElapsedTime()
	{
		return (float)_object.Call(MethodName.GetFlightElapsedTime);
	}

	public float GetFlightDistance()
	{
		return (float)_object.Call(MethodName.GetFlightDistance);
	}

	public float GetCurrentHeightOffset()
	{
		return (float)_object.Call(MethodName.GetCurrentHeightOffset);
	}

	public double[] GetDestinationEcefPrecise()
	{
		return (double[])_object.Call(MethodName.GetDestinationEcefPrecise);
	}

	public int GetLastInterruptionReason()
	{
		return (int)_object.Call(MethodName.GetLastInterruptionReason);
	}

	#endregion

	#region Signals

	public event Action<double[], float> FlightStarted
	{
		add
		{
			_object.Connect(SignalName.FlightStarted, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.FlightStarted, Callable.From(value));
		}
	}

	public event Action<float, double[], float> FlightProgressed
	{
		add
		{
			_object.Connect(SignalName.FlightProgressed, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.FlightProgressed, Callable.From(value));
		}
	}

	public event Action FlightCompleted
	{
		add
		{
			_object.Connect(SignalName.FlightCompleted, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.FlightCompleted, Callable.From(value));
		}
	}

	public event Action<int> FlightInterrupted
	{
		add
		{
			_object.Connect(SignalName.FlightInterrupted, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.FlightInterrupted, Callable.From(value));
		}
	}

	#endregion
}
