// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumMetadataStyle
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public Resource NativeObject => _object;

	public CesiumMetadataStyle() : this(NativeName)
	{
	}
	protected CesiumMetadataStyle(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumMetadataStyle(Variant variant) : this((Resource) variant)
	{
	}
	protected CesiumMetadataStyle([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(CesiumMetadataStyle self) => self?._object;
	public static implicit operator Variant(CesiumMetadataStyle self) => self?._object;
	public static explicit operator CesiumMetadataStyle(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName Enabled = "enabled";
		public static readonly StringName FeatureSource = "feature_source";
		public static readonly StringName FeatureIdSetName = "feature_id_set_name";
		public static readonly StringName FeatureIdSetIndex = "feature_id_set_index";
		public static readonly StringName Rules = "rules";
		public static readonly StringName DefaultShow = "default_show";
		public static readonly StringName DefaultColor = "default_color";
		public static readonly StringName DefaultColorMix = "default_color_mix";
		public static readonly StringName MaximumFeatures = "maximum_features";
		public static readonly StringName MaximumCacheBytes = "maximum_cache_bytes";
		public static readonly StringName LookupCacheCount = "lookup_cache_count";
		public static readonly StringName LookupCacheBytes = "lookup_cache_bytes";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName SetEnabled = "set_enabled";
		public static readonly StringName GetEnabled = "get_enabled";
		public static readonly StringName SetFeatureSource = "set_feature_source";
		public static readonly StringName GetFeatureSource = "get_feature_source";
		public static readonly StringName SetFeatureIdSetName = "set_feature_id_set_name";
		public static readonly StringName GetFeatureIdSetName = "get_feature_id_set_name";
		public static readonly StringName SetFeatureIdSetIndex = "set_feature_id_set_index";
		public static readonly StringName GetFeatureIdSetIndex = "get_feature_id_set_index";
		public static readonly StringName SetRules = "set_rules";
		public static readonly StringName GetRules = "get_rules";
		public static readonly StringName SetDefaultShow = "set_default_show";
		public static readonly StringName GetDefaultShow = "get_default_show";
		public static readonly StringName SetDefaultColor = "set_default_color";
		public static readonly StringName GetDefaultColor = "get_default_color";
		public static readonly StringName SetDefaultColorMix = "set_default_color_mix";
		public static readonly StringName GetDefaultColorMix = "get_default_color_mix";
		public static readonly StringName SetMaximumFeatures = "set_maximum_features";
		public static readonly StringName GetMaximumFeatures = "get_maximum_features";
		public static readonly StringName SetMaximumCacheBytes = "set_maximum_cache_bytes";
		public static readonly StringName GetMaximumCacheBytes = "get_maximum_cache_bytes";
		public static readonly StringName GetLookupCacheCount = "get_lookup_cache_count";
		public static readonly StringName GetLookupCacheBytes = "get_lookup_cache_bytes";
		public static readonly StringName EvaluateFeature = "evaluate_feature";
		public static readonly StringName ApplyToPrimitive = "apply_to_primitive";
		public static readonly StringName ClearFromPrimitive = "clear_from_primitive";
		public static readonly StringName ClearLookupCache = "clear_lookup_cache";
	}

	public class SignalName : Resource.SignalName
	{
		public static readonly StringName EncodingChanged = "encoding_changed";
	}

	private static readonly StringName NativeName = "CesiumMetadataStyle";

	#region Enums

	public enum FeatureSourceEnum : long
	{
		MeshFeatures = 0L,
		InstanceFeatures = 1L,
	}

	#endregion

	#region Properties

	public bool Enabled
	{
		get => (bool)_object.Get(PropertyName.Enabled);
		set => _object.Set(PropertyName.Enabled, value);
	}

	public int FeatureSource
	{
		get => (int)_object.Get(PropertyName.FeatureSource);
		set => _object.Set(PropertyName.FeatureSource, value);
	}

	public string FeatureIdSetName
	{
		get => (string)_object.Get(PropertyName.FeatureIdSetName);
		set => _object.Set(PropertyName.FeatureIdSetName, value);
	}

	public int FeatureIdSetIndex
	{
		get => (int)_object.Get(PropertyName.FeatureIdSetIndex);
		set => _object.Set(PropertyName.FeatureIdSetIndex, value);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> Rules
	{
		get => (Godot.Collections.Array<Godot.Collections.Dictionary>)_object.Get(PropertyName.Rules);
		set => _object.Set(PropertyName.Rules, value);
	}

	public bool DefaultShow
	{
		get => (bool)_object.Get(PropertyName.DefaultShow);
		set => _object.Set(PropertyName.DefaultShow, value);
	}

	public Godot.Color DefaultColor
	{
		get => (Godot.Color)_object.Get(PropertyName.DefaultColor);
		set => _object.Set(PropertyName.DefaultColor, value);
	}

	public float DefaultColorMix
	{
		get => (float)_object.Get(PropertyName.DefaultColorMix);
		set => _object.Set(PropertyName.DefaultColorMix, value);
	}

	public int MaximumFeatures
	{
		get => (int)_object.Get(PropertyName.MaximumFeatures);
		set => _object.Set(PropertyName.MaximumFeatures, value);
	}

	public int MaximumCacheBytes
	{
		get => (int)_object.Get(PropertyName.MaximumCacheBytes);
		set => _object.Set(PropertyName.MaximumCacheBytes, value);
	}

	public int LookupCacheCount
	{
		get => (int)_object.Get(PropertyName.LookupCacheCount);
	}

	public int LookupCacheBytes
	{
		get => (int)_object.Get(PropertyName.LookupCacheBytes);
	}

	#endregion

	#region Methods

	public void SetEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetEnabled, @enabled);
	}

	public bool GetEnabled()
	{
		return (bool)_object.Call(MethodName.GetEnabled);
	}

	public void SetFeatureSource(int @source)
	{
		_object.Call(MethodName.SetFeatureSource, @source);
	}

	public int GetFeatureSource()
	{
		return (int)_object.Call(MethodName.GetFeatureSource);
	}

	public void SetFeatureIdSetName(string @name)
	{
		_object.Call(MethodName.SetFeatureIdSetName, @name);
	}

	public string GetFeatureIdSetName()
	{
		return (string)_object.Call(MethodName.GetFeatureIdSetName);
	}

	public void SetFeatureIdSetIndex(int @index)
	{
		_object.Call(MethodName.SetFeatureIdSetIndex, @index);
	}

	public int GetFeatureIdSetIndex()
	{
		return (int)_object.Call(MethodName.GetFeatureIdSetIndex);
	}

	public void SetRules(Godot.Collections.Array @rules)
	{
		_object.Call(MethodName.SetRules, @rules);
	}

	public Godot.Collections.Array GetRules()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetRules);
	}

	public void SetDefaultShow(bool @show)
	{
		_object.Call(MethodName.SetDefaultShow, @show);
	}

	public bool GetDefaultShow()
	{
		return (bool)_object.Call(MethodName.GetDefaultShow);
	}

	public void SetDefaultColor(Godot.Color @color)
	{
		_object.Call(MethodName.SetDefaultColor, @color);
	}

	public Godot.Color GetDefaultColor()
	{
		return (Godot.Color)_object.Call(MethodName.GetDefaultColor);
	}

	public void SetDefaultColorMix(float @mix)
	{
		_object.Call(MethodName.SetDefaultColorMix, @mix);
	}

	public float GetDefaultColorMix()
	{
		return (float)_object.Call(MethodName.GetDefaultColorMix);
	}

	public void SetMaximumFeatures(int @count)
	{
		_object.Call(MethodName.SetMaximumFeatures, @count);
	}

	public int GetMaximumFeatures()
	{
		return (int)_object.Call(MethodName.GetMaximumFeatures);
	}

	public void SetMaximumCacheBytes(int @bytes)
	{
		_object.Call(MethodName.SetMaximumCacheBytes, @bytes);
	}

	public int GetMaximumCacheBytes()
	{
		return (int)_object.Call(MethodName.GetMaximumCacheBytes);
	}

	public int GetLookupCacheCount()
	{
		return (int)_object.Call(MethodName.GetLookupCacheCount);
	}

	public int GetLookupCacheBytes()
	{
		return (int)_object.Call(MethodName.GetLookupCacheBytes);
	}

	public Godot.Collections.Dictionary EvaluateFeature(int @feature_id, Godot.Collections.Dictionary @metadata)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.EvaluateFeature, @feature_id, @metadata);
	}

	public bool ApplyToPrimitive(CesiumLoadedTilePrimitive @primitive)
	{
		return (bool)_object.Call(MethodName.ApplyToPrimitive, @primitive);
	}

	public void ClearFromPrimitive(CesiumLoadedTilePrimitive @primitive)
	{
		_object.Call(MethodName.ClearFromPrimitive, @primitive);
	}

	public void ClearLookupCache()
	{
		_object.Call(MethodName.ClearLookupCache);
	}

	#endregion

	#region Signals

	public event Action EncodingChanged
	{
		add
		{
			_object.Connect(SignalName.EncodingChanged, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.EncodingChanged, Callable.From(value));
		}
	}

	#endregion
}
