// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumVectorStyle
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public Resource NativeObject => _object;

	public CesiumVectorStyle() : this(NativeName)
	{
	}
	protected CesiumVectorStyle(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumVectorStyle(Variant variant) : this((Resource) variant)
	{
	}
	protected CesiumVectorStyle([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(CesiumVectorStyle self) => self?._object;
	public static implicit operator Variant(CesiumVectorStyle self) => self?._object;
	public static explicit operator CesiumVectorStyle(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName LineColor = "line_color";
		public static readonly StringName LineColorMode = "line_color_mode";
		public static readonly StringName LineWidth = "line_width";
		public static readonly StringName LineWidthMode = "line_width_mode";
		public static readonly StringName PolygonFillEnabled = "polygon_fill_enabled";
		public static readonly StringName PolygonFillColor = "polygon_fill_color";
		public static readonly StringName PolygonFillColorMode = "polygon_fill_color_mode";
		public static readonly StringName PolygonOutlineEnabled = "polygon_outline_enabled";
		public static readonly StringName PolygonOutlineColor = "polygon_outline_color";
		public static readonly StringName PolygonOutlineColorMode = "polygon_outline_color_mode";
		public static readonly StringName PolygonOutlineWidth = "polygon_outline_width";
		public static readonly StringName PolygonOutlineWidthMode = "polygon_outline_width_mode";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName SetLineColor = "set_line_color";
		public static readonly StringName GetLineColor = "get_line_color";
		public static readonly StringName SetLineColorMode = "set_line_color_mode";
		public static readonly StringName GetLineColorMode = "get_line_color_mode";
		public static readonly StringName SetLineWidth = "set_line_width";
		public static readonly StringName GetLineWidth = "get_line_width";
		public static readonly StringName SetLineWidthMode = "set_line_width_mode";
		public static readonly StringName GetLineWidthMode = "get_line_width_mode";
		public static readonly StringName SetPolygonFillEnabled = "set_polygon_fill_enabled";
		public static readonly StringName GetPolygonFillEnabled = "get_polygon_fill_enabled";
		public static readonly StringName SetPolygonFillColor = "set_polygon_fill_color";
		public static readonly StringName GetPolygonFillColor = "get_polygon_fill_color";
		public static readonly StringName SetPolygonFillColorMode = "set_polygon_fill_color_mode";
		public static readonly StringName GetPolygonFillColorMode = "get_polygon_fill_color_mode";
		public static readonly StringName SetPolygonOutlineEnabled = "set_polygon_outline_enabled";
		public static readonly StringName GetPolygonOutlineEnabled = "get_polygon_outline_enabled";
		public static readonly StringName SetPolygonOutlineColor = "set_polygon_outline_color";
		public static readonly StringName GetPolygonOutlineColor = "get_polygon_outline_color";
		public static readonly StringName SetPolygonOutlineColorMode = "set_polygon_outline_color_mode";
		public static readonly StringName GetPolygonOutlineColorMode = "get_polygon_outline_color_mode";
		public static readonly StringName SetPolygonOutlineWidth = "set_polygon_outline_width";
		public static readonly StringName GetPolygonOutlineWidth = "get_polygon_outline_width";
		public static readonly StringName SetPolygonOutlineWidthMode = "set_polygon_outline_width_mode";
		public static readonly StringName GetPolygonOutlineWidthMode = "get_polygon_outline_width_mode";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumVectorStyle";

	#region Enums

	public enum ColorMode : long
	{
		Normal = 0L,
		Random = 1L,
	}

	public enum LineWidthModeEnum : long
	{
		Pixels = 0L,
		Meters = 1L,
	}

	#endregion

	#region Properties

	public Godot.Color LineColor
	{
		get => (Godot.Color)_object.Get(PropertyName.LineColor);
		set => _object.Set(PropertyName.LineColor, value);
	}

	public int LineColorMode
	{
		get => (int)_object.Get(PropertyName.LineColorMode);
		set => _object.Set(PropertyName.LineColorMode, value);
	}

	public float LineWidth
	{
		get => (float)_object.Get(PropertyName.LineWidth);
		set => _object.Set(PropertyName.LineWidth, value);
	}

	public int LineWidthMode
	{
		get => (int)_object.Get(PropertyName.LineWidthMode);
		set => _object.Set(PropertyName.LineWidthMode, value);
	}

	public bool PolygonFillEnabled
	{
		get => (bool)_object.Get(PropertyName.PolygonFillEnabled);
		set => _object.Set(PropertyName.PolygonFillEnabled, value);
	}

	public Godot.Color PolygonFillColor
	{
		get => (Godot.Color)_object.Get(PropertyName.PolygonFillColor);
		set => _object.Set(PropertyName.PolygonFillColor, value);
	}

	public int PolygonFillColorMode
	{
		get => (int)_object.Get(PropertyName.PolygonFillColorMode);
		set => _object.Set(PropertyName.PolygonFillColorMode, value);
	}

	public bool PolygonOutlineEnabled
	{
		get => (bool)_object.Get(PropertyName.PolygonOutlineEnabled);
		set => _object.Set(PropertyName.PolygonOutlineEnabled, value);
	}

	public Godot.Color PolygonOutlineColor
	{
		get => (Godot.Color)_object.Get(PropertyName.PolygonOutlineColor);
		set => _object.Set(PropertyName.PolygonOutlineColor, value);
	}

	public int PolygonOutlineColorMode
	{
		get => (int)_object.Get(PropertyName.PolygonOutlineColorMode);
		set => _object.Set(PropertyName.PolygonOutlineColorMode, value);
	}

	public float PolygonOutlineWidth
	{
		get => (float)_object.Get(PropertyName.PolygonOutlineWidth);
		set => _object.Set(PropertyName.PolygonOutlineWidth, value);
	}

	public int PolygonOutlineWidthMode
	{
		get => (int)_object.Get(PropertyName.PolygonOutlineWidthMode);
		set => _object.Set(PropertyName.PolygonOutlineWidthMode, value);
	}

	#endregion

	#region Methods

	public void SetLineColor(Godot.Color @color)
	{
		_object.Call(MethodName.SetLineColor, @color);
	}

	public Godot.Color GetLineColor()
	{
		return (Godot.Color)_object.Call(MethodName.GetLineColor);
	}

	public void SetLineColorMode(int @mode)
	{
		_object.Call(MethodName.SetLineColorMode, @mode);
	}

	public int GetLineColorMode()
	{
		return (int)_object.Call(MethodName.GetLineColorMode);
	}

	public void SetLineWidth(float @width)
	{
		_object.Call(MethodName.SetLineWidth, @width);
	}

	public float GetLineWidth()
	{
		return (float)_object.Call(MethodName.GetLineWidth);
	}

	public void SetLineWidthMode(int @mode)
	{
		_object.Call(MethodName.SetLineWidthMode, @mode);
	}

	public int GetLineWidthMode()
	{
		return (int)_object.Call(MethodName.GetLineWidthMode);
	}

	public void SetPolygonFillEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetPolygonFillEnabled, @enabled);
	}

	public bool GetPolygonFillEnabled()
	{
		return (bool)_object.Call(MethodName.GetPolygonFillEnabled);
	}

	public void SetPolygonFillColor(Godot.Color @color)
	{
		_object.Call(MethodName.SetPolygonFillColor, @color);
	}

	public Godot.Color GetPolygonFillColor()
	{
		return (Godot.Color)_object.Call(MethodName.GetPolygonFillColor);
	}

	public void SetPolygonFillColorMode(int @mode)
	{
		_object.Call(MethodName.SetPolygonFillColorMode, @mode);
	}

	public int GetPolygonFillColorMode()
	{
		return (int)_object.Call(MethodName.GetPolygonFillColorMode);
	}

	public void SetPolygonOutlineEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetPolygonOutlineEnabled, @enabled);
	}

	public bool GetPolygonOutlineEnabled()
	{
		return (bool)_object.Call(MethodName.GetPolygonOutlineEnabled);
	}

	public void SetPolygonOutlineColor(Godot.Color @color)
	{
		_object.Call(MethodName.SetPolygonOutlineColor, @color);
	}

	public Godot.Color GetPolygonOutlineColor()
	{
		return (Godot.Color)_object.Call(MethodName.GetPolygonOutlineColor);
	}

	public void SetPolygonOutlineColorMode(int @mode)
	{
		_object.Call(MethodName.SetPolygonOutlineColorMode, @mode);
	}

	public int GetPolygonOutlineColorMode()
	{
		return (int)_object.Call(MethodName.GetPolygonOutlineColorMode);
	}

	public void SetPolygonOutlineWidth(float @width)
	{
		_object.Call(MethodName.SetPolygonOutlineWidth, @width);
	}

	public float GetPolygonOutlineWidth()
	{
		return (float)_object.Call(MethodName.GetPolygonOutlineWidth);
	}

	public void SetPolygonOutlineWidthMode(int @mode)
	{
		_object.Call(MethodName.SetPolygonOutlineWidthMode, @mode);
	}

	public int GetPolygonOutlineWidthMode()
	{
		return (int)_object.Call(MethodName.GetPolygonOutlineWidthMode);
	}

	#endregion
}
