// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumOriginShift
{
	// Engine object used for calling engine methods
	protected Node _object;

	public Node NativeObject => _object;

	public CesiumOriginShift() : this(NativeName)
	{
	}
	protected CesiumOriginShift(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumOriginShift(Variant variant) : this((Node) variant)
	{
	}
	protected CesiumOriginShift([NotNull] Node @object)
	{
		_object = @object;
	}

	public static implicit operator Node(CesiumOriginShift self) => self?._object;
	public static implicit operator Variant(CesiumOriginShift self) => self?._object;
	public static explicit operator CesiumOriginShift(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node.PropertyName
	{
		public static readonly StringName Mode = "mode";
		public static readonly StringName Distance = "distance";
		public static readonly StringName GlobeAnchorPath = "globe_anchor_path";
	}

	public class MethodName : Node.MethodName
	{
		public static readonly StringName SetMode = "set_mode";
		public static readonly StringName GetMode = "get_mode";
		public static readonly StringName SetDistance = "set_distance";
		public static readonly StringName GetDistance = "get_distance";
		public static readonly StringName SetGlobeAnchorPath = "set_globe_anchor_path";
		public static readonly StringName GetGlobeAnchorPath = "get_globe_anchor_path";
		public static readonly StringName GetGlobeAnchor = "get_globe_anchor";
		public static readonly StringName ShiftOriginNow = "shift_origin_now";
		public static readonly StringName GetShiftCount = "get_shift_count";
	}

	public class SignalName : Node.SignalName
	{
		public static readonly StringName OriginShifted = "origin_shifted";
	}

	private static readonly StringName NativeName = "CesiumOriginShift";

	#region Enums

	public enum ModeEnum : long
	{
		Disabled = 0L,
		ChangeCesiumGeoreference = 1L,
	}

	#endregion

	#region Properties

	public int Mode
	{
		get => (int)_object.Get(PropertyName.Mode);
		set => _object.Set(PropertyName.Mode, value);
	}

	public float Distance
	{
		get => (float)_object.Get(PropertyName.Distance);
		set => _object.Set(PropertyName.Distance, value);
	}

	public Godot.NodePath GlobeAnchorPath
	{
		get => (Godot.NodePath)_object.Get(PropertyName.GlobeAnchorPath);
		set => _object.Set(PropertyName.GlobeAnchorPath, value);
	}

	#endregion

	#region Methods

	public void SetMode(int @mode)
	{
		_object.Call(MethodName.SetMode, @mode);
	}

	public int GetMode()
	{
		return (int)_object.Call(MethodName.GetMode);
	}

	public void SetDistance(float @distance)
	{
		_object.Call(MethodName.SetDistance, @distance);
	}

	public float GetDistance()
	{
		return (float)_object.Call(MethodName.GetDistance);
	}

	public void SetGlobeAnchorPath(Godot.NodePath @path)
	{
		_object.Call(MethodName.SetGlobeAnchorPath, @path);
	}

	public Godot.NodePath GetGlobeAnchorPath()
	{
		return (Godot.NodePath)_object.Call(MethodName.GetGlobeAnchorPath);
	}

	public CesiumGlobeAnchor GetGlobeAnchor()
	{
		return (CesiumGlobeAnchor)_object.Call(MethodName.GetGlobeAnchor);
	}

	public bool ShiftOriginNow()
	{
		return (bool)_object.Call(MethodName.ShiftOriginNow);
	}

	public int GetShiftCount()
	{
		return (int)_object.Call(MethodName.GetShiftCount);
	}

	#endregion

	#region Signals

	public event Action<double[], double[], int> OriginShifted
	{
		add
		{
			_object.Connect(SignalName.OriginShifted, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.OriginShifted, Callable.From(value));
		}
	}

	#endregion
}
