// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumUrlTemplateRasterOverlay : CesiumRasterOverlay
{
	public CesiumUrlTemplateRasterOverlay() : base(NativeName)
	{
	}
	protected CesiumUrlTemplateRasterOverlay(StringName @class) : base(@class)
	{
	}
	protected CesiumUrlTemplateRasterOverlay(Variant variant) : base(variant)
	{
	}
	protected CesiumUrlTemplateRasterOverlay([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(CesiumUrlTemplateRasterOverlay self) => self?._object;
	public static implicit operator Variant(CesiumUrlTemplateRasterOverlay self) => self?._object;
	public static explicit operator CesiumUrlTemplateRasterOverlay(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : CesiumRasterOverlay.PropertyName
	{
		public static readonly StringName TemplateUrl = "template_url";
		public static readonly StringName Projection = "projection";
		public static readonly StringName SpecifyTilingScheme = "specify_tiling_scheme";
		public static readonly StringName RootTilesX = "root_tiles_x";
		public static readonly StringName RootTilesY = "root_tiles_y";
		public static readonly StringName RectangleWest = "rectangle_west";
		public static readonly StringName RectangleSouth = "rectangle_south";
		public static readonly StringName RectangleEast = "rectangle_east";
		public static readonly StringName RectangleNorth = "rectangle_north";
		public static readonly StringName MinimumLevel = "minimum_level";
		public static readonly StringName MaximumLevel = "maximum_level";
		public static readonly StringName TileWidth = "tile_width";
		public static readonly StringName TileHeight = "tile_height";
		public static readonly StringName RequestHeaders = "request_headers";
	}

	public new class MethodName : CesiumRasterOverlay.MethodName
	{
		public static readonly StringName SetTemplateUrl = "set_template_url";
		public static readonly StringName GetTemplateUrl = "get_template_url";
		public static readonly StringName SetProjection = "set_projection";
		public static readonly StringName GetProjection = "get_projection";
		public static readonly StringName SetSpecifyTilingScheme = "set_specify_tiling_scheme";
		public static readonly StringName GetSpecifyTilingScheme = "get_specify_tiling_scheme";
		public static readonly StringName SetRootTilesX = "set_root_tiles_x";
		public static readonly StringName GetRootTilesX = "get_root_tiles_x";
		public static readonly StringName SetRootTilesY = "set_root_tiles_y";
		public static readonly StringName GetRootTilesY = "get_root_tiles_y";
		public static readonly StringName SetRectangleWest = "set_rectangle_west";
		public static readonly StringName GetRectangleWest = "get_rectangle_west";
		public static readonly StringName SetRectangleSouth = "set_rectangle_south";
		public static readonly StringName GetRectangleSouth = "get_rectangle_south";
		public static readonly StringName SetRectangleEast = "set_rectangle_east";
		public static readonly StringName GetRectangleEast = "get_rectangle_east";
		public static readonly StringName SetRectangleNorth = "set_rectangle_north";
		public static readonly StringName GetRectangleNorth = "get_rectangle_north";
		public static readonly StringName SetMinimumLevel = "set_minimum_level";
		public static readonly StringName GetMinimumLevel = "get_minimum_level";
		public static readonly StringName SetMaximumLevel = "set_maximum_level";
		public static readonly StringName GetMaximumLevel = "get_maximum_level";
		public static readonly StringName SetTileWidth = "set_tile_width";
		public static readonly StringName GetTileWidth = "get_tile_width";
		public static readonly StringName SetTileHeight = "set_tile_height";
		public static readonly StringName GetTileHeight = "get_tile_height";
		public static readonly StringName SetRequestHeaders = "set_request_headers";
		public static readonly StringName GetRequestHeaders = "get_request_headers";
	}

	public new class SignalName : CesiumRasterOverlay.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumUrlTemplateRasterOverlay";

	#region Enums

	public enum ProjectionEnum : long
	{
		WebMercator = 0L,
		Geographic = 1L,
	}

	#endregion

	#region Properties

	public string TemplateUrl
	{
		get => (string)_object.Get(PropertyName.TemplateUrl);
		set => _object.Set(PropertyName.TemplateUrl, value);
	}

	public int Projection
	{
		get => (int)_object.Get(PropertyName.Projection);
		set => _object.Set(PropertyName.Projection, value);
	}

	public bool SpecifyTilingScheme
	{
		get => (bool)_object.Get(PropertyName.SpecifyTilingScheme);
		set => _object.Set(PropertyName.SpecifyTilingScheme, value);
	}

	public int RootTilesX
	{
		get => (int)_object.Get(PropertyName.RootTilesX);
		set => _object.Set(PropertyName.RootTilesX, value);
	}

	public int RootTilesY
	{
		get => (int)_object.Get(PropertyName.RootTilesY);
		set => _object.Set(PropertyName.RootTilesY, value);
	}

	public float RectangleWest
	{
		get => (float)_object.Get(PropertyName.RectangleWest);
		set => _object.Set(PropertyName.RectangleWest, value);
	}

	public float RectangleSouth
	{
		get => (float)_object.Get(PropertyName.RectangleSouth);
		set => _object.Set(PropertyName.RectangleSouth, value);
	}

	public float RectangleEast
	{
		get => (float)_object.Get(PropertyName.RectangleEast);
		set => _object.Set(PropertyName.RectangleEast, value);
	}

	public float RectangleNorth
	{
		get => (float)_object.Get(PropertyName.RectangleNorth);
		set => _object.Set(PropertyName.RectangleNorth, value);
	}

	public int MinimumLevel
	{
		get => (int)_object.Get(PropertyName.MinimumLevel);
		set => _object.Set(PropertyName.MinimumLevel, value);
	}

	public int MaximumLevel
	{
		get => (int)_object.Get(PropertyName.MaximumLevel);
		set => _object.Set(PropertyName.MaximumLevel, value);
	}

	public int TileWidth
	{
		get => (int)_object.Get(PropertyName.TileWidth);
		set => _object.Set(PropertyName.TileWidth, value);
	}

	public int TileHeight
	{
		get => (int)_object.Get(PropertyName.TileHeight);
		set => _object.Set(PropertyName.TileHeight, value);
	}

	public Godot.Collections.Dictionary RequestHeaders
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.RequestHeaders);
		set => _object.Set(PropertyName.RequestHeaders, value);
	}

	#endregion

	#region Methods

	public void SetTemplateUrl(string @url)
	{
		_object.Call(MethodName.SetTemplateUrl, @url);
	}

	public string GetTemplateUrl()
	{
		return (string)_object.Call(MethodName.GetTemplateUrl);
	}

	public void SetProjection(int @projection)
	{
		_object.Call(MethodName.SetProjection, @projection);
	}

	public int GetProjection()
	{
		return (int)_object.Call(MethodName.GetProjection);
	}

	public void SetSpecifyTilingScheme(bool @value)
	{
		_object.Call(MethodName.SetSpecifyTilingScheme, @value);
	}

	public bool GetSpecifyTilingScheme()
	{
		return (bool)_object.Call(MethodName.GetSpecifyTilingScheme);
	}

	public void SetRootTilesX(int @value)
	{
		_object.Call(MethodName.SetRootTilesX, @value);
	}

	public int GetRootTilesX()
	{
		return (int)_object.Call(MethodName.GetRootTilesX);
	}

	public void SetRootTilesY(int @value)
	{
		_object.Call(MethodName.SetRootTilesY, @value);
	}

	public int GetRootTilesY()
	{
		return (int)_object.Call(MethodName.GetRootTilesY);
	}

	public void SetRectangleWest(float @value)
	{
		_object.Call(MethodName.SetRectangleWest, @value);
	}

	public float GetRectangleWest()
	{
		return (float)_object.Call(MethodName.GetRectangleWest);
	}

	public void SetRectangleSouth(float @value)
	{
		_object.Call(MethodName.SetRectangleSouth, @value);
	}

	public float GetRectangleSouth()
	{
		return (float)_object.Call(MethodName.GetRectangleSouth);
	}

	public void SetRectangleEast(float @value)
	{
		_object.Call(MethodName.SetRectangleEast, @value);
	}

	public float GetRectangleEast()
	{
		return (float)_object.Call(MethodName.GetRectangleEast);
	}

	public void SetRectangleNorth(float @value)
	{
		_object.Call(MethodName.SetRectangleNorth, @value);
	}

	public float GetRectangleNorth()
	{
		return (float)_object.Call(MethodName.GetRectangleNorth);
	}

	public void SetMinimumLevel(int @value)
	{
		_object.Call(MethodName.SetMinimumLevel, @value);
	}

	public int GetMinimumLevel()
	{
		return (int)_object.Call(MethodName.GetMinimumLevel);
	}

	public void SetMaximumLevel(int @value)
	{
		_object.Call(MethodName.SetMaximumLevel, @value);
	}

	public int GetMaximumLevel()
	{
		return (int)_object.Call(MethodName.GetMaximumLevel);
	}

	public void SetTileWidth(int @value)
	{
		_object.Call(MethodName.SetTileWidth, @value);
	}

	public int GetTileWidth()
	{
		return (int)_object.Call(MethodName.GetTileWidth);
	}

	public void SetTileHeight(int @value)
	{
		_object.Call(MethodName.SetTileHeight, @value);
	}

	public int GetTileHeight()
	{
		return (int)_object.Call(MethodName.GetTileHeight);
	}

	public void SetRequestHeaders(Godot.Collections.Dictionary @headers)
	{
		_object.Call(MethodName.SetRequestHeaders, @headers);
	}

	public Godot.Collections.Dictionary GetRequestHeaders()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetRequestHeaders);
	}

	#endregion
}
