// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumSampleHeightMostDetailedRequest
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumSampleHeightMostDetailedRequest() : this(NativeName)
	{
	}
	protected CesiumSampleHeightMostDetailedRequest(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumSampleHeightMostDetailedRequest(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumSampleHeightMostDetailedRequest([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumSampleHeightMostDetailedRequest self) => self?._object;
	public static implicit operator Variant(CesiumSampleHeightMostDetailedRequest self) => self?._object;
	public static explicit operator CesiumSampleHeightMostDetailedRequest(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Status = "status";
		public static readonly StringName Results = "results";
		public static readonly StringName Warnings = "warnings";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetStatus = "get_status";
		public static readonly StringName IsFinished = "is_finished";
		public static readonly StringName IsCancelled = "is_cancelled";
		public static readonly StringName GetResults = "get_results";
		public static readonly StringName GetWarnings = "get_warnings";
	}

	public class SignalName : RefCounted.SignalName
	{
		public static readonly StringName Completed = "completed";
		public static readonly StringName Cancelled = "cancelled";
	}

	private static readonly StringName NativeName = "CesiumSampleHeightMostDetailedRequest";

	#region Enums

	public enum StatusEnum : long
	{
		Pending = 0L,
		Completed = 1L,
		Cancelled = 2L,
	}

	#endregion

	#region Properties

	public int Status
	{
		get => (int)_object.Get(PropertyName.Status);
	}

	public Godot.Collections.Array Results
	{
		get => (Godot.Collections.Array)_object.Get(PropertyName.Results);
	}

	public string[] Warnings
	{
		get => (string[])_object.Get(PropertyName.Warnings);
	}

	#endregion

	#region Methods

	public int GetStatus()
	{
		return (int)_object.Call(MethodName.GetStatus);
	}

	public bool IsFinished()
	{
		return (bool)_object.Call(MethodName.IsFinished);
	}

	public bool IsCancelled()
	{
		return (bool)_object.Call(MethodName.IsCancelled);
	}

	public Godot.Collections.Array GetResults()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetResults);
	}

	public string[] GetWarnings()
	{
		return (string[])_object.Call(MethodName.GetWarnings);
	}

	#endregion

	#region Signals

	public event Action<Godot.Collections.Array, string[]> Completed
	{
		add
		{
			_object.Connect(SignalName.Completed, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.Completed, Callable.From(value));
		}
	}

	public event Action<string[]> Cancelled
	{
		add
		{
			_object.Connect(SignalName.Cancelled, Callable.From(value));
		}
		remove
		{
			_object.Disconnect(SignalName.Cancelled, Callable.From(value));
		}
	}

	#endregion
}
