// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumPointCloudShading
{
	// Engine object used for calling engine methods
	protected Resource _object;

	public Resource NativeObject => _object;

	public CesiumPointCloudShading() : this(NativeName)
	{
	}
	protected CesiumPointCloudShading(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumPointCloudShading(Variant variant) : this((Resource) variant)
	{
	}
	protected CesiumPointCloudShading([NotNull] Resource @object)
	{
		_object = @object;
	}

	public static implicit operator Resource(CesiumPointCloudShading self) => self?._object;
	public static implicit operator Variant(CesiumPointCloudShading self) => self?._object;
	public static explicit operator CesiumPointCloudShading(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Resource.PropertyName
	{
		public static readonly StringName Attenuation = "attenuation";
		public static readonly StringName GeometricErrorScale = "geometric_error_scale";
		public static readonly StringName MaximumAttenuation = "maximum_attenuation";
		public static readonly StringName BaseResolution = "base_resolution";
	}

	public class MethodName : Resource.MethodName
	{
		public static readonly StringName SetAttenuation = "set_attenuation";
		public static readonly StringName GetAttenuation = "get_attenuation";
		public static readonly StringName SetGeometricErrorScale = "set_geometric_error_scale";
		public static readonly StringName GetGeometricErrorScale = "get_geometric_error_scale";
		public static readonly StringName SetMaximumAttenuation = "set_maximum_attenuation";
		public static readonly StringName GetMaximumAttenuation = "get_maximum_attenuation";
		public static readonly StringName SetBaseResolution = "set_base_resolution";
		public static readonly StringName GetBaseResolution = "get_base_resolution";
		public static readonly StringName ResolveGeometricError = "resolve_geometric_error";
		public static readonly StringName ResolveParameters = "resolve_parameters";
		public static readonly StringName ApplyToMaterial = "apply_to_material";
	}

	public class SignalName : Resource.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumPointCloudShading";

	#region Properties

	public bool Attenuation
	{
		get => (bool)_object.Get(PropertyName.Attenuation);
		set => _object.Set(PropertyName.Attenuation, value);
	}

	public float GeometricErrorScale
	{
		get => (float)_object.Get(PropertyName.GeometricErrorScale);
		set => _object.Set(PropertyName.GeometricErrorScale, value);
	}

	public float MaximumAttenuation
	{
		get => (float)_object.Get(PropertyName.MaximumAttenuation);
		set => _object.Set(PropertyName.MaximumAttenuation, value);
	}

	public float BaseResolution
	{
		get => (float)_object.Get(PropertyName.BaseResolution);
		set => _object.Set(PropertyName.BaseResolution, value);
	}

	#endregion

	#region Methods

	public void SetAttenuation(bool @enabled)
	{
		_object.Call(MethodName.SetAttenuation, @enabled);
	}

	public bool GetAttenuation()
	{
		return (bool)_object.Call(MethodName.GetAttenuation);
	}

	public void SetGeometricErrorScale(float @scale)
	{
		_object.Call(MethodName.SetGeometricErrorScale, @scale);
	}

	public float GetGeometricErrorScale()
	{
		return (float)_object.Call(MethodName.GetGeometricErrorScale);
	}

	public void SetMaximumAttenuation(float @pixels)
	{
		_object.Call(MethodName.SetMaximumAttenuation, @pixels);
	}

	public float GetMaximumAttenuation()
	{
		return (float)_object.Call(MethodName.GetMaximumAttenuation);
	}

	public void SetBaseResolution(float @meters)
	{
		_object.Call(MethodName.SetBaseResolution, @meters);
	}

	public float GetBaseResolution()
	{
		return (float)_object.Call(MethodName.GetBaseResolution);
	}

	public float ResolveGeometricError(float @tile_geometric_error, Godot.Vector3 @dimensions, int @point_count)
	{
		return (float)_object.Call(MethodName.ResolveGeometricError, @tile_geometric_error, @dimensions, @point_count);
	}

	public Godot.Collections.Dictionary ResolveParameters(bool @uses_additive_refinement, float @tile_geometric_error, Godot.Vector3 @dimensions, int @point_count, int @diameter, float @maximum_screen_space_error)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.ResolveParameters, @uses_additive_refinement, @tile_geometric_error, @dimensions, @point_count, @diameter, @maximum_screen_space_error);
	}

	public bool ApplyToMaterial(Material @material, bool @uses_additive_refinement, float @tile_geometric_error, Godot.Vector3 @dimensions, int @point_count, int @diameter, float @maximum_screen_space_error)
	{
		return (bool)_object.Call(MethodName.ApplyToMaterial, @material, @uses_additive_refinement, @tile_geometric_error, @dimensions, @point_count, @diameter, @maximum_screen_space_error);
	}

	#endregion
}
