// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumRasterOverlayBinding
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public RefCounted NativeObject => _object;

	public CesiumRasterOverlayBinding() : this(NativeName)
	{
	}
	protected CesiumRasterOverlayBinding(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumRasterOverlayBinding(Variant variant) : this((RefCounted) variant)
	{
	}
	protected CesiumRasterOverlayBinding([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(CesiumRasterOverlayBinding self) => self?._object;
	public static implicit operator Variant(CesiumRasterOverlayBinding self) => self?._object;
	public static explicit operator CesiumRasterOverlayBinding(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName TilePrimitive = "tile_primitive";
		public static readonly StringName OverlayKey = "overlay_key";
		public static readonly StringName Texture = "texture";
		public static readonly StringName Material = "material";
		public static readonly StringName TextureCoordinateId = "texture_coordinate_id";
		public static readonly StringName TextureCoordinateIndex = "texture_coordinate_index";
		public static readonly StringName Translation = "translation";
		public static readonly StringName Scale = "scale";
		public static readonly StringName Attached = "attached";
		public static readonly StringName ShaderParameterPrefix = "shader_parameter_prefix";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetTilePrimitive = "get_tile_primitive";
		public static readonly StringName GetOverlayKey = "get_overlay_key";
		public static readonly StringName GetTexture = "get_texture";
		public static readonly StringName GetMaterial = "get_material";
		public static readonly StringName GetTextureCoordinateId = "get_texture_coordinate_id";
		public static readonly StringName GetTextureCoordinateIndex = "get_texture_coordinate_index";
		public static readonly StringName GetTranslation = "get_translation";
		public static readonly StringName GetScale = "get_scale";
		public static readonly StringName TransformTextureCoordinate = "transform_texture_coordinate";
		public static readonly StringName IsAttached = "is_attached";
		public static readonly StringName GetShaderParameterPrefix = "get_shader_parameter_prefix";
		public static readonly StringName ApplyToMaterial = "apply_to_material";
		public static readonly StringName ClearFromMaterial = "clear_from_material";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumRasterOverlayBinding";

	#region Properties

	public CesiumLoadedTilePrimitive TilePrimitive
	{
		get => (CesiumLoadedTilePrimitive)_object.Get(PropertyName.TilePrimitive);
	}

	public string OverlayKey
	{
		get => (string)_object.Get(PropertyName.OverlayKey);
	}

	public Texture2D Texture
	{
		get => (Texture2D)_object.Get(PropertyName.Texture);
	}

	public Material Material
	{
		get => (Material)_object.Get(PropertyName.Material);
	}

	public int TextureCoordinateId
	{
		get => (int)_object.Get(PropertyName.TextureCoordinateId);
	}

	public int TextureCoordinateIndex
	{
		get => (int)_object.Get(PropertyName.TextureCoordinateIndex);
	}

	public Godot.Vector2 Translation
	{
		get => (Godot.Vector2)_object.Get(PropertyName.Translation);
	}

	public Godot.Vector2 Scale
	{
		get => (Godot.Vector2)_object.Get(PropertyName.Scale);
	}

	public bool Attached
	{
		get => (bool)_object.Get(PropertyName.Attached);
	}

	public string ShaderParameterPrefix
	{
		get => (string)_object.Get(PropertyName.ShaderParameterPrefix);
	}

	#endregion

	#region Methods

	public CesiumLoadedTilePrimitive GetTilePrimitive()
	{
		return (CesiumLoadedTilePrimitive)_object.Call(MethodName.GetTilePrimitive);
	}

	public string GetOverlayKey()
	{
		return (string)_object.Call(MethodName.GetOverlayKey);
	}

	public Texture2D GetTexture()
	{
		return (Texture2D)_object.Call(MethodName.GetTexture);
	}

	public Material GetMaterial()
	{
		return (Material)_object.Call(MethodName.GetMaterial);
	}

	public int GetTextureCoordinateId()
	{
		return (int)_object.Call(MethodName.GetTextureCoordinateId);
	}

	public int GetTextureCoordinateIndex()
	{
		return (int)_object.Call(MethodName.GetTextureCoordinateIndex);
	}

	public Godot.Vector2 GetTranslation()
	{
		return (Godot.Vector2)_object.Call(MethodName.GetTranslation);
	}

	public Godot.Vector2 GetScale()
	{
		return (Godot.Vector2)_object.Call(MethodName.GetScale);
	}

	public Godot.Vector2 TransformTextureCoordinate(Godot.Vector2 @texture_coordinate)
	{
		return (Godot.Vector2)_object.Call(MethodName.TransformTextureCoordinate, @texture_coordinate);
	}

	public bool IsAttached()
	{
		return (bool)_object.Call(MethodName.IsAttached);
	}

	public string GetShaderParameterPrefix()
	{
		return (string)_object.Call(MethodName.GetShaderParameterPrefix);
	}

	public bool ApplyToMaterial(Material @material)
	{
		return (bool)_object.Call(MethodName.ApplyToMaterial, @material);
	}

	public bool ClearFromMaterial(Material @material)
	{
		return (bool)_object.Call(MethodName.ClearFromMaterial, @material);
	}

	#endregion
}
