// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumTileDebugVisualizer
{
	// Engine object used for calling engine methods
	protected Node3D _object;

	public Node3D NativeObject => _object;

	public CesiumTileDebugVisualizer() : this(NativeName)
	{
	}
	protected CesiumTileDebugVisualizer(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumTileDebugVisualizer(Variant variant) : this((Node3D) variant)
	{
	}
	protected CesiumTileDebugVisualizer([NotNull] Node3D @object)
	{
		_object = @object;
	}

	public static implicit operator Node3D(CesiumTileDebugVisualizer self) => self?._object;
	public static implicit operator Variant(CesiumTileDebugVisualizer self) => self?._object;
	public static explicit operator CesiumTileDebugVisualizer(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node3D.PropertyName
	{
		public static readonly StringName Tileset = "tileset";
		public static readonly StringName VisualizationEnabled = "visualization_enabled";
		public static readonly StringName ShowLabels = "show_labels";
		public static readonly StringName ShowRefinementRelationships = "show_refinement_relationships";
		public static readonly StringName MaximumLabels = "maximum_labels";
		public static readonly StringName DrawnStateCount = "drawn_state_count";
		public static readonly StringName DrawnFrameNumber = "drawn_frame_number";
	}

	public class MethodName : Node3D.MethodName
	{
		public static readonly StringName SetTileset = "set_tileset";
		public static readonly StringName GetTileset = "get_tileset";
		public static readonly StringName SetVisualizationEnabled = "set_visualization_enabled";
		public static readonly StringName GetVisualizationEnabled = "get_visualization_enabled";
		public static readonly StringName SetShowLabels = "set_show_labels";
		public static readonly StringName GetShowLabels = "get_show_labels";
		public static readonly StringName SetShowRefinementRelationships = "set_show_refinement_relationships";
		public static readonly StringName GetShowRefinementRelationships = "get_show_refinement_relationships";
		public static readonly StringName SetMaximumLabels = "set_maximum_labels";
		public static readonly StringName GetMaximumLabels = "get_maximum_labels";
		public static readonly StringName GetDrawnStateCount = "get_drawn_state_count";
		public static readonly StringName GetDrawnFrameNumber = "get_drawn_frame_number";
	}

	public class SignalName : Node3D.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumTileDebugVisualizer";

	#region Properties

	public GodotObject Tileset
	{
		get => (GodotObject)_object.Get(PropertyName.Tileset);
		set => _object.Set(PropertyName.Tileset, value);
	}

	public bool VisualizationEnabled
	{
		get => (bool)_object.Get(PropertyName.VisualizationEnabled);
		set => _object.Set(PropertyName.VisualizationEnabled, value);
	}

	public bool ShowLabels
	{
		get => (bool)_object.Get(PropertyName.ShowLabels);
		set => _object.Set(PropertyName.ShowLabels, value);
	}

	public bool ShowRefinementRelationships
	{
		get => (bool)_object.Get(PropertyName.ShowRefinementRelationships);
		set => _object.Set(PropertyName.ShowRefinementRelationships, value);
	}

	public int MaximumLabels
	{
		get => (int)_object.Get(PropertyName.MaximumLabels);
		set => _object.Set(PropertyName.MaximumLabels, value);
	}

	public int DrawnStateCount
	{
		get => (int)_object.Get(PropertyName.DrawnStateCount);
	}

	public int DrawnFrameNumber
	{
		get => (int)_object.Get(PropertyName.DrawnFrameNumber);
	}

	#endregion

	#region Methods

	public void SetTileset(Cesium3DTileset @tileset)
	{
		_object.Call(MethodName.SetTileset, @tileset);
	}

	public Cesium3DTileset GetTileset()
	{
		return (Cesium3DTileset)_object.Call(MethodName.GetTileset);
	}

	public void SetVisualizationEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetVisualizationEnabled, @enabled);
	}

	public bool GetVisualizationEnabled()
	{
		return (bool)_object.Call(MethodName.GetVisualizationEnabled);
	}

	public void SetShowLabels(bool @show_labels)
	{
		_object.Call(MethodName.SetShowLabels, @show_labels);
	}

	public bool GetShowLabels()
	{
		return (bool)_object.Call(MethodName.GetShowLabels);
	}

	public void SetShowRefinementRelationships(bool @show_relationships)
	{
		_object.Call(MethodName.SetShowRefinementRelationships, @show_relationships);
	}

	public bool GetShowRefinementRelationships()
	{
		return (bool)_object.Call(MethodName.GetShowRefinementRelationships);
	}

	public void SetMaximumLabels(int @maximum_labels)
	{
		_object.Call(MethodName.SetMaximumLabels, @maximum_labels);
	}

	public int GetMaximumLabels()
	{
		return (int)_object.Call(MethodName.GetMaximumLabels);
	}

	public int GetDrawnStateCount()
	{
		return (int)_object.Call(MethodName.GetDrawnStateCount);
	}

	public int GetDrawnFrameNumber()
	{
		return (int)_object.Call(MethodName.GetDrawnFrameNumber);
	}

	#endregion
}
