// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGDAssetBuilder
{
	// Engine object used for calling engine methods
	protected Node3D _object;

	public Node3D NativeObject => _object;

	public CesiumGDAssetBuilder() : this(NativeName)
	{
	}
	protected CesiumGDAssetBuilder(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGDAssetBuilder(Variant variant) : this((Node3D) variant)
	{
	}
	protected CesiumGDAssetBuilder([NotNull] Node3D @object)
	{
		_object = @object;
	}

	public static implicit operator Node3D(CesiumGDAssetBuilder self) => self?._object;
	public static implicit operator Variant(CesiumGDAssetBuilder self) => self?._object;
	public static explicit operator CesiumGDAssetBuilder(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node3D.PropertyName
	{
		public static readonly StringName GeorefCameraScript = "georef_camera_script";
	}

	public class MethodName : Node3D.MethodName
	{
		public static readonly StringName InstantiateDynamicCam = "instantiate_dynamic_cam";
		public static readonly StringName InstantiateOrbitCam = "instantiate_orbit_cam";
		public static readonly StringName InstantiateTileset = "instantiate_tileset";
		public static readonly StringName FindOrCreateGlobe = "find_or_create_globe";
		public static readonly StringName GetGeoreferenceCameraScript = "get_georeference_camera_script";
		public static readonly StringName SetGeoreferenceCameraScript = "set_georeference_camera_script";
		public static readonly StringName FindAllTilesets = "find_all_tilesets";
	}

	public class SignalName : Node3D.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumGDAssetBuilder";

	#region Properties

	public GodotObject GeorefCameraScript
	{
		get => (GodotObject)_object.Get(PropertyName.GeorefCameraScript);
		set => _object.Set(PropertyName.GeorefCameraScript, value);
	}

	#endregion

	#region Methods

	public void InstantiateDynamicCam()
	{
		_object.Call(MethodName.InstantiateDynamicCam);
	}

	public void InstantiateOrbitCam()
	{
		_object.Call(MethodName.InstantiateOrbitCam);
	}

	public void InstantiateTileset(int @assetId, string @assetType, string @_unnamed_arg2)
	{
		_object.Call(MethodName.InstantiateTileset, @assetId, @assetType, @_unnamed_arg2);
	}

	public CesiumGeoreference FindOrCreateGlobe()
	{
		return (CesiumGeoreference)_object.Call(MethodName.FindOrCreateGlobe);
	}

	public Variant GetGeoreferenceCameraScript()
	{
		return (Variant)_object.Call(MethodName.GetGeoreferenceCameraScript);
	}

	public void SetGeoreferenceCameraScript(Variant @script)
	{
		_object.Call(MethodName.SetGeoreferenceCameraScript, @script);
	}

	public Godot.Collections.Array FindAllTilesets()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.FindAllTilesets);
	}

	#endregion
}
