// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumTileMapServiceRasterOverlay : CesiumRasterOverlay
{
	public CesiumTileMapServiceRasterOverlay() : base(NativeName)
	{
	}
	protected CesiumTileMapServiceRasterOverlay(StringName @class) : base(@class)
	{
	}
	protected CesiumTileMapServiceRasterOverlay(Variant variant) : base(variant)
	{
	}
	protected CesiumTileMapServiceRasterOverlay([NotNull] Node3D @object) : base(@object)
	{
	}

	public static implicit operator Node3D(CesiumTileMapServiceRasterOverlay self) => self?._object;
	public static implicit operator Variant(CesiumTileMapServiceRasterOverlay self) => self?._object;
	public static explicit operator CesiumTileMapServiceRasterOverlay(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public new class PropertyName : CesiumRasterOverlay.PropertyName
	{
		public static readonly StringName Url = "url";
		public static readonly StringName SpecifyZoomLevels = "specify_zoom_levels";
		public static readonly StringName MinimumLevel = "minimum_level";
		public static readonly StringName MaximumLevel = "maximum_level";
		public static readonly StringName RequestHeaders = "request_headers";
	}

	public new class MethodName : CesiumRasterOverlay.MethodName
	{
		public static readonly StringName SetUrl = "set_url";
		public static readonly StringName GetUrl = "get_url";
		public static readonly StringName SetSpecifyZoomLevels = "set_specify_zoom_levels";
		public static readonly StringName GetSpecifyZoomLevels = "get_specify_zoom_levels";
		public static readonly StringName SetMinimumLevel = "set_minimum_level";
		public static readonly StringName GetMinimumLevel = "get_minimum_level";
		public static readonly StringName SetMaximumLevel = "set_maximum_level";
		public static readonly StringName GetMaximumLevel = "get_maximum_level";
		public static readonly StringName SetRequestHeaders = "set_request_headers";
		public static readonly StringName GetRequestHeaders = "get_request_headers";
	}

	public new class SignalName : CesiumRasterOverlay.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumTileMapServiceRasterOverlay";

	#region Properties

	public string Url
	{
		get => (string)_object.Get(PropertyName.Url);
		set => _object.Set(PropertyName.Url, value);
	}

	public bool SpecifyZoomLevels
	{
		get => (bool)_object.Get(PropertyName.SpecifyZoomLevels);
		set => _object.Set(PropertyName.SpecifyZoomLevels, value);
	}

	public int MinimumLevel
	{
		get => (int)_object.Get(PropertyName.MinimumLevel);
		set => _object.Set(PropertyName.MinimumLevel, value);
	}

	public int MaximumLevel
	{
		get => (int)_object.Get(PropertyName.MaximumLevel);
		set => _object.Set(PropertyName.MaximumLevel, value);
	}

	public Godot.Collections.Dictionary RequestHeaders
	{
		get => (Godot.Collections.Dictionary)_object.Get(PropertyName.RequestHeaders);
		set => _object.Set(PropertyName.RequestHeaders, value);
	}

	#endregion

	#region Methods

	public void SetUrl(string @url)
	{
		_object.Call(MethodName.SetUrl, @url);
	}

	public string GetUrl()
	{
		return (string)_object.Call(MethodName.GetUrl);
	}

	public void SetSpecifyZoomLevels(bool @value)
	{
		_object.Call(MethodName.SetSpecifyZoomLevels, @value);
	}

	public bool GetSpecifyZoomLevels()
	{
		return (bool)_object.Call(MethodName.GetSpecifyZoomLevels);
	}

	public void SetMinimumLevel(int @value)
	{
		_object.Call(MethodName.SetMinimumLevel, @value);
	}

	public int GetMinimumLevel()
	{
		return (int)_object.Call(MethodName.GetMinimumLevel);
	}

	public void SetMaximumLevel(int @value)
	{
		_object.Call(MethodName.SetMaximumLevel, @value);
	}

	public int GetMaximumLevel()
	{
		return (int)_object.Call(MethodName.GetMaximumLevel);
	}

	public void SetRequestHeaders(Godot.Collections.Dictionary @headers)
	{
		_object.Call(MethodName.SetRequestHeaders, @headers);
	}

	public Godot.Collections.Dictionary GetRequestHeaders()
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetRequestHeaders);
	}

	#endregion
}
