// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumTileExcluder
{
	// Engine object used for calling engine methods
	protected Node _object;

	public Node NativeObject => _object;

	public CesiumTileExcluder() : this(NativeName)
	{
	}
	protected CesiumTileExcluder(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumTileExcluder(Variant variant) : this((Node) variant)
	{
	}
	protected CesiumTileExcluder([NotNull] Node @object)
	{
		_object = @object;
	}

	public static implicit operator Node(CesiumTileExcluder self) => self?._object;
	public static implicit operator Variant(CesiumTileExcluder self) => self?._object;
	public static explicit operator CesiumTileExcluder(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : Node.PropertyName
	{
		public static readonly StringName Enabled = "enabled";
		public static readonly StringName Predicate = "predicate";
		public static readonly StringName AddedToTileset = "added_to_tileset";
		public static readonly StringName FrameCount = "frame_count";
		public static readonly StringName EvaluationCount = "evaluation_count";
		public static readonly StringName ExcludedCount = "excluded_count";
		public static readonly StringName InvalidResultCount = "invalid_result_count";
		public static readonly StringName LastFrameEvaluationCount = "last_frame_evaluation_count";
		public static readonly StringName LastFrameExcludedCount = "last_frame_excluded_count";
	}

	public class MethodName : Node.MethodName
	{
		public static readonly StringName SetEnabled = "set_enabled";
		public static readonly StringName GetEnabled = "get_enabled";
		public static readonly StringName SetPredicate = "set_predicate";
		public static readonly StringName GetPredicate = "get_predicate";
		public static readonly StringName AddToTileset = "add_to_tileset";
		public static readonly StringName RemoveFromTileset = "remove_from_tileset";
		public static readonly StringName Refresh = "refresh";
		public static readonly StringName IsAddedToTileset = "is_added_to_tileset";
		public static readonly StringName GetFrameCount = "get_frame_count";
		public static readonly StringName GetEvaluationCount = "get_evaluation_count";
		public static readonly StringName GetExcludedCount = "get_excluded_count";
		public static readonly StringName GetInvalidResultCount = "get_invalid_result_count";
		public static readonly StringName GetLastFrameEvaluationCount = "get_last_frame_evaluation_count";
		public static readonly StringName GetLastFrameExcludedCount = "get_last_frame_excluded_count";
		public static readonly StringName ResetStatistics = "reset_statistics";
	}

	public class SignalName : Node.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumTileExcluder";

	#region Properties

	public bool Enabled
	{
		get => (bool)_object.Get(PropertyName.Enabled);
		set => _object.Set(PropertyName.Enabled, value);
	}

	public Godot.Callable Predicate
	{
		get => (Godot.Callable)_object.Get(PropertyName.Predicate);
		set => _object.Set(PropertyName.Predicate, value);
	}

	public bool AddedToTileset
	{
		get => (bool)_object.Get(PropertyName.AddedToTileset);
	}

	public int FrameCount
	{
		get => (int)_object.Get(PropertyName.FrameCount);
	}

	public int EvaluationCount
	{
		get => (int)_object.Get(PropertyName.EvaluationCount);
	}

	public int ExcludedCount
	{
		get => (int)_object.Get(PropertyName.ExcludedCount);
	}

	public int InvalidResultCount
	{
		get => (int)_object.Get(PropertyName.InvalidResultCount);
	}

	public int LastFrameEvaluationCount
	{
		get => (int)_object.Get(PropertyName.LastFrameEvaluationCount);
	}

	public int LastFrameExcludedCount
	{
		get => (int)_object.Get(PropertyName.LastFrameExcludedCount);
	}

	#endregion

	#region Methods

	public void SetEnabled(bool @enabled)
	{
		_object.Call(MethodName.SetEnabled, @enabled);
	}

	public bool GetEnabled()
	{
		return (bool)_object.Call(MethodName.GetEnabled);
	}

	public void SetPredicate(Godot.Callable @predicate)
	{
		_object.Call(MethodName.SetPredicate, @predicate);
	}

	public Godot.Callable GetPredicate()
	{
		return (Godot.Callable)_object.Call(MethodName.GetPredicate);
	}

	public Godot.Error AddToTileset(Cesium3DTileset @tileset = default)
	{
		return (Godot.Error)(int)_object.Call(MethodName.AddToTileset, @tileset);
	}

	public void RemoveFromTileset(Cesium3DTileset @tileset = default)
	{
		_object.Call(MethodName.RemoveFromTileset, @tileset);
	}

	public void Refresh()
	{
		_object.Call(MethodName.Refresh);
	}

	public bool IsAddedToTileset()
	{
		return (bool)_object.Call(MethodName.IsAddedToTileset);
	}

	public int GetFrameCount()
	{
		return (int)_object.Call(MethodName.GetFrameCount);
	}

	public int GetEvaluationCount()
	{
		return (int)_object.Call(MethodName.GetEvaluationCount);
	}

	public int GetExcludedCount()
	{
		return (int)_object.Call(MethodName.GetExcludedCount);
	}

	public int GetInvalidResultCount()
	{
		return (int)_object.Call(MethodName.GetInvalidResultCount);
	}

	public int GetLastFrameEvaluationCount()
	{
		return (int)_object.Call(MethodName.GetLastFrameEvaluationCount);
	}

	public int GetLastFrameExcludedCount()
	{
		return (int)_object.Call(MethodName.GetLastFrameExcludedCount);
	}

	public void ResetStatistics()
	{
		_object.Call(MethodName.ResetStatistics);
	}

	#endregion
}
