// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace CesiumForGodot;

public class CesiumGltfInstancedComponent
{
	// Engine object used for calling engine methods
	protected MultiMeshInstance3D _object;

	public MultiMeshInstance3D NativeObject => _object;

	public CesiumGltfInstancedComponent() : this(NativeName)
	{
	}
	protected CesiumGltfInstancedComponent(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected CesiumGltfInstancedComponent(Variant variant) : this((MultiMeshInstance3D) variant)
	{
	}
	protected CesiumGltfInstancedComponent([NotNull] MultiMeshInstance3D @object)
	{
		_object = @object;
	}

	public static implicit operator MultiMeshInstance3D(CesiumGltfInstancedComponent self) => self?._object;
	public static implicit operator Variant(CesiumGltfInstancedComponent self) => self?._object;
	public static explicit operator CesiumGltfInstancedComponent(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : MultiMeshInstance3D.PropertyName
	{
		public static readonly StringName RendererPrimitiveIndex = "renderer_primitive_index";
		public static readonly StringName InstanceCount = "instance_count";
		public static readonly StringName InstanceFeatures = "instance_features";
	}

	public class MethodName : MultiMeshInstance3D.MethodName
	{
		public static readonly StringName GetRendererPrimitiveIndex = "get_renderer_primitive_index";
		public static readonly StringName GetInstanceCount = "get_instance_count";
		public static readonly StringName GetInstanceFeatures = "get_instance_features";
	}

	public class SignalName : MultiMeshInstance3D.SignalName
	{

	}

	private static readonly StringName NativeName = "CesiumGltfInstancedComponent";

	#region Properties

	public int RendererPrimitiveIndex
	{
		get => (int)_object.Get(PropertyName.RendererPrimitiveIndex);
	}

	public int InstanceCount
	{
		get => (int)_object.Get(PropertyName.InstanceCount);
	}

	public CesiumPrimitiveFeatures InstanceFeatures
	{
		get => (CesiumPrimitiveFeatures)_object.Get(PropertyName.InstanceFeatures);
	}

	#endregion

	#region Methods

	public int GetRendererPrimitiveIndex()
	{
		return (int)_object.Call(MethodName.GetRendererPrimitiveIndex);
	}

	public int GetInstanceCount()
	{
		return (int)_object.Call(MethodName.GetInstanceCount);
	}

	public CesiumPrimitiveFeatures GetInstanceFeatures()
	{
		return (CesiumPrimitiveFeatures)_object.Call(MethodName.GetInstanceFeatures);
	}

	#endregion
}
