<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>CesiumCSharpTwoDog.Tests</RootNamespace>
    <GodotProjectDir>..</GodotProjectDir>
    <TwoDogVariant>debug</TwoDogVariant>
    <TwoDogRemoveDuplicateGodotAnalyzers>true</TwoDogRemoveDuplicateGodotAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="2dog.xunit" Version="$(TwoDogVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="../CesiumCSharpTwoDog.csproj" />
  </ItemGroup>
</Project>
